Repository iotaledger/identity, pull requests merged in 2021-12, with the labels that each got.

#516 Add `identity-diff` derive feature gate
  bindings/wasm/docs/api-reference.md
  identity-diff/Cargo.toml
  identity-diff/README.md
  identity-diff/derive/Cargo.toml
  identity-diff/src/lib.rs
  identity-diff/tests/derive_enum_test.rs
  identity-diff/tests/derive_struct_test.rs
Labels: Chore

#520 Add `FmtJson` trait
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/tangle/explorer.rs
  identity-account/src/storage/memstore.rs
  identity-account/src/stronghold/records.rs
  identity-account/src/types/generation.rs
  identity-account/src/utils/shared.rs
  identity-core/src/common/bitset.rs
  identity-core/src/common/one_or_many.rs
  identity-core/src/common/timestamp.rs
  identity-core/src/common/url.rs
  identity-core/src/convert/json.rs
  identity-core/src/convert/mod.rs
  identity-core/src/crypto/merkle_tree/proof.rs
  identity-core/src/crypto/signature/signature.rs
  identity-credential/src/credential/credential.rs
  identity-credential/src/presentation/presentation.rs
  identity-did/src/did/did.rs
  identity-did/src/did/did_url.rs
  identity-did/src/document/core_document.rs
  identity-did/src/service/service.rs
  identity-did/src/service/service_endpoint.rs
  identity-did/src/utils/ordered_set.rs
  identity-did/src/verification/method_data.rs
  identity-did/src/verification/method_ref.rs
  identity-did/src/verification/verification_method.rs
  identity-diff/src/hashmap.rs
  identity-diff/src/hashset.rs
  identity-diff/src/macros.rs
  identity-diff/src/option.rs
  identity-diff/src/string.rs
  identity-diff/src/vec.rs
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/chain/integration_chain.rs
  identity-iota/src/did/iota_did.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/document/iota_verification_method.rs
  identity-iota/src/tangle/client_builder.rs
  libjose/src/error.rs
  libjose/src/jwe/algorithm.rs
  libjose/src/jwe/compression.rs
Labels: Chore

#523 Fix lint warnings
  identity-account/src/account/account.rs
  identity-did/src/resolution/resource.rs
Labels: Chore, No changelog, Rust

#525 Bump `iota-client` version to 1.1
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  identity-account/Cargo.toml
  identity-comm/Cargo.toml
  identity-core/Cargo.toml
  identity-credential/Cargo.toml
  identity-did/Cargo.toml
  identity-did/src/resolution/resource.rs
  identity-diff/Cargo.toml
  identity-diff/derive/Cargo.toml
  identity-iota/Cargo.toml
  identity-iota/src/did/doc/iota_document.rs
  identity/Cargo.toml
Labels: Rust, Patch

#488 Add changelog and release workflows
  .github/.github_changelog_generator
  .github/actions/publish/publish-wasm/action.yml
  .github/actions/release/bump-versions/action.yml
  .github/actions/release/changelog-generator/action.yml
  .github/workflows/enforce-pr-labels.yml
  .github/workflows/publish-dev.yml
  .github/workflows/publish.yml
  .github/workflows/rust-automatic-release-and-publish.yml
  .github/workflows/rust-create-release-pr.yml
  .github/workflows/shared-create-dev-release-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
  .github/workflows/shared-release.yml
  .github/workflows/wasm-automatic-release-and-publish.yml
  .github/workflows/wasm-create-release-pr.yml
  bindings/wasm/.github_changelog_generator
Labels: No changelog

#527 Add missing workflow condition
  .github/workflows/shared-release.yml
Labels: No changelog

#528 Update `iota-client` dependency
  identity-iota/Cargo.toml
Labels: No changelog, Rust, Patch

#522 Enable access to the low-level API from the `Account`
  examples/Cargo.toml
  examples/README.md
  examples/account/lazy.rs
  examples/account/unchecked.rs
  identity-account/src/account/account.rs
  identity-account/src/account/mod.rs
  identity-account/src/account/publish_options.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/updates.rs
  identity-account/src/updates/update.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/tangle/publish.rs
Labels: Enhancement, Breaking change, Rust

#536 Fix workflow release version
  .github/workflows/shared-release.yml
Labels: No changelog

#537 Update `iota-client` version
  identity-iota/Cargo.toml
Labels: No changelog, Rust, Patch

#541 Fix `Timestamp` in the Wasm bindings
  bindings/wasm/tests/wasm.rs
  identity-core/Cargo.toml
  identity-core/src/common/timestamp.rs
  identity/Cargo.toml
Labels: Wasm, Patch

#543 Remove `chrono` dev-dependency in Wasm bindings
  bindings/wasm/Cargo.toml
Labels: Wasm, No changelog

#545 Ignore `serde_cbor` unmaintained advisory in audit
  .cargo/audit.toml
  .github/workflows/audit.yml
Labels: Chore, No changelog

#533 Add workflow document
  README.md
  documentation/docs/workflow.md
  documentation/sidebars.js
Labels: Documentation

#519 Filter out DiffMessages updating signing methods
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/tangle/publish.rs
Labels: Bug, Added, Rust

#550 Disable issues for changelogs
  .github/.github_changelog_generator
  bindings/wasm/.github_changelog_generator
Labels: No changelog

#551 Rename Wasm `VerifiableCredential`, `VerifiablePresentation`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/did/wasm_document.rs
Labels: Wasm, Breaking change

#548 Add signature `created`, `expires`, `challenge`, `domain`, `purpose`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/src/crypto/mod.rs
  bindings/wasm/src/crypto/wasm_proof_purpose.rs
  bindings/wasm/src/crypto/wasm_signature_options.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  bindings/wasm/src/did/wasm_method_scope.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_verifier_options.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/tests/wasm.rs
  examples/account/signing.rs
  examples/low-level-api/common.rs
  examples/low-level-api/create_vc.rs
  examples/low-level-api/create_vp.rs
  examples/low-level-api/merkle_key.rs
  examples/low-level-api/revoke_vc.rs
  identity-account/src/account/account.rs
  identity-account/src/crypto/remote.rs
  identity-account/src/identity/identity_state.rs
  identity-core/src/crypto/mod.rs
  identity-core/src/crypto/signature/mod.rs
  identity-core/src/crypto/signature/signature.rs
  identity-core/src/crypto/signature/signature_options.rs
  identity-core/src/crypto/signature/traits/core.rs
  identity-core/src/error.rs
  identity-did/src/document/core_document.rs
  identity-did/src/error.rs
  identity-did/src/verifiable/document.rs
  identity-did/src/verifiable/document_signer.rs
  identity-did/src/verifiable/document_verifier.rs
  identity-did/src/verifiable/mod.rs
  identity-did/src/verifiable/properties.rs
  identity-did/src/verifiable/revocation.rs
  identity-did/src/verifiable/tests.rs
  identity-did/src/verifiable/verifier_options.rs
  identity-did/src/verification/method_scope.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/credential/validator.rs
  identity-iota/src/diff/diff_iota_document_metadata.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/document/iota_document_metadata.rs
  identity/benches/diff_chain.rs
Labels: Wasm, Breaking change, Rust

#560 fix hotfix changelog
  .github/workflows/shared-create-hotfix-pr.yml
Labels: No changelog

#561 fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch

#544 Add account synchronization method
  identity-account/src/account/account.rs
  identity-account/src/tests/account.rs
Labels: Enhancement, Added, Rust

#565 fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch
