Repository iotaledger/identity, pull requests merged in 2021-11, with the labels that each got.

#379 Add IOTA DIDComm protocols specification
  documentation/docs/decentralized_identifiers/overview.md
  documentation/docs/specs/did/iota_did_method_spec.md
  documentation/docs/specs/did/merkle_key_collection.md
  documentation/docs/specs/did/overview.md
  documentation/docs/specs/didcomm/CHANGELOG.md
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/didcomm/resources/credential-info.md
  documentation/docs/specs/didcomm/resources/problem-reports.md
  documentation/sidebars.js
  documentation/static/img/didcomm/authentication.drawio.svg
  documentation/static/img/didcomm/connection.drawio.svg
  documentation/static/img/didcomm/issuance.drawio.svg
  documentation/static/img/didcomm/post.drawio.svg
  documentation/static/img/didcomm/presentation.drawio.svg
  documentation/static/img/didcomm/revocation-options.drawio.svg
  documentation/static/img/didcomm/revocation.drawio.svg
  documentation/static/img/didcomm/signing.drawio.svg
  documentation/static/img/didcomm/termination.drawio.svg
Labels: Documentation, DID Comm

#478 Fix broken wiki links
  bindings/wasm/README.md
  documentation/docs/decentralized_identity.md
  documentation/docs/getting_started/create_and_publish.mdx
Labels: Documentation

#458 Update document signing key constraints and methods
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_diff.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/tests/wasm.rs
  documentation/docs/specs/did/iota_did_method_spec.md
  examples/low-level-api/common.rs
  examples/low-level-api/create_did.rs
  examples/low-level-api/create_vc.rs
  examples/low-level-api/create_vp.rs
  examples/low-level-api/diff_chain.rs
  examples/low-level-api/manipulate_did.rs
  examples/low-level-api/merkle_key.rs
  examples/low-level-api/private_tangle.rs
  examples/low-level-api/resolution.rs
  examples/low-level-api/resolve_history.rs
  examples/low-level-api/revoke_vc.rs
  identity-account/src/account/account.rs
  identity-account/src/events/command.rs
  identity-account/src/identity/identity_create.rs
  identity-account/src/identity/identity_state.rs
  identity-account/src/storage/stronghold.rs
  identity-account/src/tests/commands.rs
  identity-account/src/tests/lazy.rs
  identity-account/src/types/key_location.rs
  identity-core/src/crypto/signature/traits/core.rs
  identity-did/src/did/did.rs
  identity-did/src/did/did_url.rs
  identity-did/src/document/core_document.rs
  identity-did/src/utils/ordered_set.rs
  identity-did/src/verifiable/document.rs
  identity-did/src/verifiable/tests.rs
  identity-did/src/verification/method_query.rs
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/chain/integration_chain.rs
  identity-iota/src/credential/validator.rs
  identity-iota/src/did/doc/iota_document.rs
  identity-iota/src/did/doc/iota_verification_method.rs
  identity-iota/src/did/doc/mod.rs
  identity-iota/src/did/mod.rs
  identity-iota/src/error.rs
  identity/benches/benchmark.rs
  identity/benches/diff_chain.rs
Labels: Enhancement, Improvement, Breaking

#481 Enable deep equality in `OrderedSet`
  identity-account/src/tests/lazy.rs
  identity-did/src/did/did_url.rs
  identity-did/src/diff/did_key_diff.rs
  identity-did/src/diff/diff_document.rs
  identity-did/src/diff/mod.rs
  identity-did/src/diff/ordered_set.rs
  identity-did/src/document/builder.rs
  identity-did/src/document/core_document.rs
  identity-did/src/resolution/impls.rs
  identity-did/src/resolution/resource.rs
  identity-did/src/utils/did_key.rs
  identity-did/src/utils/key_comparable.rs
  identity-did/src/utils/mod.rs
  identity-did/src/utils/ordered_set.rs
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/did/doc/iota_document.rs
  identity/benches/diff_chain.rs
Labels: Bug, Breaking

#485 Add ServiceEndpoint sets and maps
  bindings/wasm/examples/src/resolve_history.js
  examples/low-level-api/resolve_history.rs
  identity-account/src/events/command.rs
  identity-account/src/identity/identity_state.rs
  identity-did/Cargo.toml
  identity-did/src/diff/diff_document.rs
  identity-did/src/diff/diff_service.rs
  identity-did/src/error.rs
  identity-did/src/resolution/impls.rs
  identity-did/src/service/builder.rs
  identity-did/src/service/mod.rs
  identity-did/src/service/service.rs
  identity-did/src/service/service_endpoint.rs
  identity-did/src/utils/key_comparable.rs
Labels: Enhancement, Breaking

#466 Add message compression and versioning
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/src/tangle/config.rs
  bindings/wasm/src/tangle/message.rs
  bindings/wasm/src/tangle/mod.rs
  examples/low-level-api/private_tangle.rs
  identity-iota/Cargo.toml
  identity-iota/src/error.rs
  identity-iota/src/tangle/client.rs
  identity-iota/src/tangle/client_builder.rs
  identity-iota/src/tangle/message/compression_brotli.rs
  identity-iota/src/tangle/message/message_encoding.rs
  identity-iota/src/tangle/message/message_ext.rs
  identity-iota/src/tangle/message/message_index.rs
  identity-iota/src/tangle/message/message_version.rs
  identity-iota/src/tangle/message/mod.rs
  identity-iota/src/tangle/message_ext.rs
  identity-iota/src/tangle/mod.rs
Labels: Breaking

#490 Fix credential validation failing for documents with diff updates
  identity-iota/src/credential/validator.rs
Labels: Bug

#462 Refactor the `Account` state
  bindings/wasm/src/did/wasm_verification_method.rs
  examples/account/create_did.rs
  examples/account/manipulate_did.rs
  examples/low-level-api/common.rs
  examples/low-level-api/manipulate_did.rs
  examples/low-level-api/resolve_history.rs
  examples/low-level-api/revoke_vc.rs
  identity-account/src/account/account.rs
  identity-account/src/error.rs
  identity-account/src/events/commit.rs
  identity-account/src/events/context.rs
  identity-account/src/events/event.rs
  identity-account/src/events/update.rs
  identity-account/src/identity/chain_state.rs
  identity-account/src/identity/identity_snapshot.rs
  identity-account/src/identity/identity_state.rs
  identity-account/src/identity/mod.rs
  identity-account/src/lib.rs
  identity-account/src/storage/memstore.rs
  identity-account/src/storage/stronghold.rs
  identity-account/src/storage/traits.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/commands.rs
  identity-account/src/tests/lazy.rs
  identity-account/src/tests/mod.rs
  identity-account/src/tests/updates.rs
  identity-account/src/types/key_location.rs
  identity-account/src/updates/error.rs
  identity-account/src/updates/macros.rs
  identity-account/src/updates/mod.rs
  identity-account/src/updates/update.rs
  identity-core/src/common/mod.rs
  identity-core/src/common/unix_timestamp.rs
  identity-did/src/document/core_document.rs
  identity-did/src/utils/ordered_set.rs
  identity-did/src/verification/method_relationship.rs
  identity-did/src/verification/method_scope.rs
  identity-did/src/verification/mod.rs
  identity-iota/src/did/doc/iota_document.rs
  identity-iota/src/did/doc/iota_verification_method.rs
  identity-iota/src/tangle/mod.rs
  identity-iota/src/tangle/publish.rs
  identity/src/lib.rs
Labels: Breaking

#503 Update iota-client dependency
  bindings/wasm/Cargo.toml
  identity-iota/Cargo.toml
Labels: Bug

#501 Annotate Wasm async function return types
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/chain/mod.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/mod.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/receipt.rs
Labels: Binding, WASM

#509 Replace `jest` with `mocha`
  bindings/wasm/cypress/integration/browser_test.js
  bindings/wasm/examples/src/node.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/test.js
  bindings/wasm/examples/src/utils.js
  bindings/wasm/examples/src/web.js
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: Bug

#496 Add `ExplorerUrl`
  bindings/wasm/Cargo.toml
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/config.js
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolution.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/examples/src/utils.js
  bindings/wasm/examples/src/utils_web.js
  bindings/wasm/examples/webpack.config.js
  bindings/wasm/src/error.rs
  bindings/wasm/src/tangle/explorer.rs
  bindings/wasm/src/tangle/mod.rs
  bindings/wasm/src/tangle/network.rs
  examples/README.md
  examples/account/config.rs
  examples/account/create_did.rs
  examples/account/lazy.rs
  examples/account/manipulate_did.rs
  examples/account/multiple_identities.rs
  examples/account/signing.rs
  examples/low-level-api/create_did.rs
  examples/low-level-api/diff_chain.rs
  examples/low-level-api/manipulate_did.rs
  examples/low-level-api/private_tangle.rs
  examples/low-level-api/revoke_vc.rs
  identity-iota/src/did/macros.rs
  identity-iota/src/tangle/explorer.rs
  identity-iota/src/tangle/mod.rs
  identity-iota/src/tangle/network.rs
  identity-iota/src/tangle/receipt.rs
Labels: Bug, Breaking

#510 Enforce Ed25519 private key length
  identity-core/src/crypto/key/pair.rs
  identity-core/src/crypto/proof/jcs_ed25519.rs
  identity-core/src/crypto/signature/ed25519.rs
  identity-core/src/utils/ed25519.rs
Labels: Documentation, Breaking

#511 Rename `DocumentDiff` to `DiffMessage`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/tangle/client.rs
  examples/account/config.rs
  examples/low-level-api/diff_chain.rs
  examples/low-level-api/private_tangle.rs
  examples/low-level-api/resolve_history.rs
  identity-account/src/account/account.rs
  identity-account/src/identity/identity_state.rs
  identity-account/src/updates/update.rs
  identity-did/src/did/did_url.rs
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/chain/document_history.rs
  identity-iota/src/chain/integration_chain.rs
  identity-iota/src/credential/validator.rs
  identity-iota/src/did/did/mod.rs
  identity-iota/src/did/iota_did.rs
  identity-iota/src/did/mod.rs
  identity-iota/src/did/segments.rs
  identity-iota/src/document/diff_message.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/document/iota_verification_method.rs
  identity-iota/src/document/mod.rs
  identity-iota/src/document/properties.rs
  identity-iota/src/lib.rs
  identity-iota/src/resolver.rs
  identity-iota/src/tangle/client.rs
  identity-iota/src/tangle/client_map.rs
  identity-iota/src/tangle/explorer.rs
  identity-iota/src/tangle/message/compression_brotli.rs
  identity-iota/src/tangle/message/message_ext.rs
  identity-iota/src/tangle/network.rs
  identity-iota/src/tangle/publish.rs
  identity-iota/src/tangle/receipt.rs
  identity-iota/src/tangle/traits.rs
  identity/benches/diff_chain.rs
  identity/src/lib.rs
Labels: Chore, Breaking

#506 Deterministic ordering of competing messages
  identity-iota/Cargo.toml
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_history.rs
  identity-iota/src/chain/integration_chain.rs
  identity-iota/src/chain/milestone.rs
  identity-iota/src/chain/mod.rs
  identity-iota/src/error.rs
  identity-iota/src/tangle/client.rs
Labels: Bug, Breaking

#513 Fix `txm` version in GitHub Actions
  .github/workflows/examples.yml
Labels: Bug

#512 Improve client error messages
  identity-iota/src/chain/integration_chain.rs
  identity-iota/src/error.rs
  identity-iota/src/tangle/client.rs
Labels: Chore
