Repository iotaledger/identity, pull requests merged in 2021-03, with the labels that each got.

#150 Update wasm deps
  .github/workflows/build-and-test.yml
  bindings/wasm/package.json
  bindings/wasm/webpack.config.js
  bindings/wasm/yarn.lock
Labels: WASM, binding

#149 Ensure consistent timestamp precision
  identity-core/src/common/timestamp.rs
Labels: bug

#152 Use crypto.rs
  bindings/wasm/Cargo.toml
  bindings/wasm/src/document.rs
  examples/Cargo.toml
  examples/merkle_key.rs
  identity-core/Cargo.toml
  identity-core/src/convert/json.rs
  identity-core/src/crypto/ed25519.rs
  identity-core/src/crypto/merkle_key/base.rs
  identity-core/src/crypto/merkle_key/impls.rs
  identity-core/src/crypto/merkle_key/mod.rs
  identity-core/src/crypto/merkle_key/tests.rs
  identity-core/src/crypto/merkle_key/traits.rs
  identity-core/src/crypto/merkle_tree/digest.rs
  identity-core/src/crypto/merkle_tree/merkle.rs
  identity-core/src/crypto/merkle_tree/node.rs
  identity-core/src/error.rs
  identity-core/src/utils/generate_ed25519.rs
  identity-iota/Cargo.toml
  identity-iota/src/did/url/did.rs
Labels: enhancement, improvement

#173 Added general intro to mdbook
  docs/SUMMARY.md
  docs/intro_ssi.md
  docs/introduction.md
  docs/overview/advanced/did_messages.md
  docs/overview/did/README.md
Labels: Documentation

#174 Include README.md as crate documentation
  identity-core/Cargo.toml
  identity-core/README.md
  identity-core/src/lib.rs
  identity-credential/Cargo.toml
  identity-credential/README.md
  identity-credential/src/lib.rs
  identity-did/Cargo.toml
  identity-did/README.md
  identity-did/src/lib.rs
  identity-diff/Cargo.toml
  identity-diff/README.md
  identity-diff/src/lib.rs
  identity-iota/Cargo.toml
  identity-iota/README.md
  identity-iota/src/lib.rs
  identity/Cargo.toml
  identity/README.md
  identity/src/lib.rs
Labels: Documentation

#178 Docs/didcomms spec
  docs/DID Communications Research and Specification/Interactions and Messages.md
Labels: DID Comm, Documentation, Enhancement, Improvement

#164 Docs/readme
  README.md
Labels: Documentation, Improvement

#191 Update readme with Chrysalis Phase 2 warning
  .meta/identity_banner.png
  README.md
Labels: Documentation
