Repository iotaledger/identity, pull requests merged in 2021-07, with the labels that each got.

#290 Reimpl `Key` with generics
  identity-core/src/crypto/key/key.rs
Labels: Improvement, Meeting

#294 replace deleted method readDocument(id) with resolve(id)
  bindings/wasm/examples/resolution.js
Labels: WASM

#297 Disable riker logging
  identity-account/src/stronghold/context.rs
Labels: Improvement

#318 Fix pipeline download failures
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/scripts/coverage.sh
Labels: Bug

#317 Wasm examples browser
  bindings/wasm/examples/.gitignore
  bindings/wasm/examples/README.md
  bindings/wasm/examples/browser/create_did.js
  bindings/wasm/examples/browser/create_vc.js
  bindings/wasm/examples/browser/create_vp.js
  bindings/wasm/examples/browser/index.html
  bindings/wasm/examples/browser/main.js
  bindings/wasm/examples/browser/mainpulate_did.js
  bindings/wasm/examples/browser/merkle_key.js
  bindings/wasm/examples/browser/resolve.js
  bindings/wasm/examples/browser/revocation.js
  bindings/wasm/examples/browser/utils.js
  bindings/wasm/examples/node/config.js
  bindings/wasm/examples/node/create_did.js
  bindings/wasm/examples/node/create_vc.js
  bindings/wasm/examples/node/create_vp.js
  bindings/wasm/examples/node/explorer_util.js
  bindings/wasm/examples/node/manipulate_did.js
  bindings/wasm/examples/node/merkle_key.js
  bindings/wasm/examples/node/node.js
  bindings/wasm/examples/node/resolution.js
  bindings/wasm/examples/node/revocation.js
  bindings/wasm/examples/web.js
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: WASM

#291 Add features to account to allow wasm compilation
  Cargo.toml
  identity-account/Cargo.toml
  identity-account/src/account/builder.rs
  identity-account/src/error.rs
  identity-account/src/lib.rs
  identity-account/src/storage/mod.rs
Labels: Improvement, WASM

#319 Fix cyclic dependency
  identity-core/Cargo.toml
Labels: Bug

#329 Impl type that mimics a thread-safe `Cell`
  identity-core/src/crypto/signature/signature.rs
Labels: Bug
