Repository iotaledger/identity, pull requests merged in 2022-11, with the labels that each got.

#1069 Fix clippy lints
  examples/1_advanced/1_did_issues_nft.rs
  identity_core/src/common/one_or_many.rs
  identity_core/src/common/one_or_set.rs
  identity_core/src/common/url.rs
  identity_core/src/crypto/key/type_.rs
  identity_core/src/crypto/proof/proof.rs
  identity_core/src/crypto/proof/proof_value.rs
  identity_core/src/utils/base_encoding.rs
  identity_credential/src/credential/credential.rs
  identity_credential/src/validator/credential_validator.rs
  identity_credential/src/validator/test_utils.rs
  identity_did/src/did/did.rs
  identity_did/src/did/did_url.rs
  identity_did/src/revocation/bitmap.rs
  identity_did/src/verification/method_type.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/error.rs
  identity_resolver/src/resolution/tests/resolution_errors.rs
Labels: Breaking change, Rust

#1070 Add v. credentials and presentations examples
  examples/0_basic/1_update_did.rs
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/0_basic/4_delete_did.rs
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/1_advanced/0_did_controls_did.rs
  examples/1_advanced/1_did_issues_nft.rs
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
  examples/1_advanced/5_alias_output_history.rs
  examples/1_advanced/6_custom_resolution.rs
  examples/Cargo.toml
  examples/utils/utils.rs
  identity_core/src/crypto/proof/proof.rs
  libjose/src/jwk/key.rs
  libjose/src/utils/crypto/concat_kdf.rs
  libjose/tests/rfc.rs
Labels: Added, Chore, Rust

#1074 Temporarily pin `iota-types` version
  bindings/wasm/Cargo.toml
  examples/Cargo.toml
  identity_iota_core/Cargo.toml
Labels: No changelog, Patch

#1075 Add wasm credentials and presentations examples
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/0_basic/5_create_vc.ts
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/util.ts
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/README.md
Labels: Wasm, Added, Chore

#1067 More identifier checks in `CoreDocument`
  bindings/stronghold-nodejs/Cargo.lock
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/resolver/wasm_resolver.rs
  bindings/wasm/tests/core.ts
  bindings/wasm/tests/iota.ts
  examples/0_basic/1_update_did.rs
  examples/1_advanced/5_alias_output_history.rs
  examples_legacy/account/unchecked.rs
  identity_account/src/tests/account.rs
  identity_account/src/updates/update.rs
  identity_core/src/common/ordered_set.rs
  identity_credential/src/validator/credential_validator.rs
  identity_did/Cargo.toml
  identity_did/benches/deserialize_document.rs
  identity_did/src/diff/diff_document.rs
  identity_did/src/document/builder.rs
  identity_did/src/document/core_document.rs
  identity_did/src/document/mod.rs
  identity_did/src/error.rs
  identity_iota_client_legacy/src/chain/document_chain.rs
  identity_iota_client_legacy/src/tangle/message/message_ext.rs
  identity_iota_client_legacy/src/tangle/publish.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/error.rs
  identity_iota_core/src/state_metadata/document.rs
  identity_iota_core_legacy/src/document/iota_document.rs
  identity_iota_core_legacy/src/error.rs
Labels: Wasm, Breaking change, Rust

#1076 Add revocation examples
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/7_revoke_vc.ts
  examples/0_basic/7_revoke_vc.rs
  examples/Cargo.toml
  examples/README.md
Labels: Wasm, Added, Chore, Rust

#1085 Make `StateMetadataDocument` public
  identity_iota_core/src/state_metadata/document.rs
  identity_iota_core/src/state_metadata/mod.rs
Labels: Added, Rust

#1084 Remove legacy account examples
  bindings/wasm/cypress/e2e/.gitkeep
  bindings/wasm/cypress/e2e/createIdentity.cy.js
  bindings/wasm/cypress/e2e/keyExchange.cy.js
  bindings/wasm/cypress/e2e/manipulateIdentity.cy.js
  bindings/wasm/cypress/e2e/privateTangle.cy.js
  bindings/wasm/cypress/e2e/resolveHistory.cy.js
  bindings/wasm/cypress/e2e/resolveIdentity.cy.js
  bindings/wasm/examples-account/README.md
  bindings/wasm/examples-account/src/config.ts
  bindings/wasm/examples-account/src/create_did.ts
  bindings/wasm/examples-account/src/create_vc.ts
  bindings/wasm/examples-account/src/create_vp.ts
  bindings/wasm/examples-account/src/custom_storage.ts
  bindings/wasm/examples-account/src/encryption.ts
  bindings/wasm/examples-account/src/lazy.ts
  bindings/wasm/examples-account/src/manipulate_did.ts
  bindings/wasm/examples-account/src/multiple_identities.ts
  bindings/wasm/examples-account/src/node.ts
  bindings/wasm/examples-account/src/revoke_vc.ts
  bindings/wasm/examples-account/src/signing.ts
  bindings/wasm/examples-account/src/tests/config.ts
  bindings/wasm/examples-account/src/tests/create_did.ts
  bindings/wasm/examples-account/src/tests/create_vc.ts
  bindings/wasm/examples-account/src/tests/create_vp.ts
  bindings/wasm/examples-account/src/tests/encryption.ts
  bindings/wasm/examples-account/src/tests/lazy.ts
  bindings/wasm/examples-account/src/tests/manipulate_did.ts
  bindings/wasm/examples-account/src/tests/multiple_identities.ts
  bindings/wasm/examples-account/src/tests/revoke_vc.ts
  bindings/wasm/examples-account/src/tests/signing.ts
  bindings/wasm/examples-account/src/tests/unchecked.ts
  bindings/wasm/examples-account/src/unchecked.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/tests/legacy/account.ts
Labels: Chore, No changelog

#1081 Use alias instead of relative paths in examples
  bindings/wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/0_basic/5_create_vc.ts
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
  bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/tsconfig.json
  documentation/docs/tutorials/validate_university_degree.mdx
Labels: Documentation, Chore, No changelog

#1089 Fix TS Linting
  bindings/wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/0_basic/5_create_vc.ts
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
  bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: Wasm, Chore, No changelog

#1083 Use rust stable toolchain in CI
  .github/workflows/build-and-test.yml
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/scripts/coverage.sh
  .github/workflows/shared-build-wasm.yml
  .github/workflows/test-docs-build.yml
Labels: Chore, No changelog

#1092 Add Rust changelog for v0.7.0-alpha.4
  CHANGELOG.md
Labels: No changelog, Rust

#1093 Downgrade `identity_iota_core` dev dependency to path only
  identity_agent/Cargo.toml
Labels: No changelog, Rust

#1095 Do not publish agent for now
  identity_agent/Cargo.toml
Labels: No changelog, Rust
