Repository iotaledger/identity, pull requests merged in 2022-09, with the labels that each got.

#987 Remove deprecated `cargo read-manifest`
  .github/workflows/build-and-test.yml
Labels: No changelog

#995 Fix broken wasm bindings compilation
  identity_iota_client/Cargo.toml
Labels: Wasm, Patch

#986 Update `create DID` wiki page
  documentation/docs/concepts/decentralized_identifiers/alias.md
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/overview.md
  documentation/sidebars.js
Labels: Documentation

#999 Disable nodejs-stronghold bindings in CI
  .github/workflows/build-and-test.yml
  .github/workflows/wasm-automatic-release-and-publish.yml
Labels: No changelog

#1002 Remove advanced concepts wiki section
  documentation/docs/concepts/advanced/did_messages.mdx
  documentation/docs/concepts/advanced/overview.md
  documentation/docs/concepts/advanced/storage_interface.mdx
  documentation/docs/introduction.md
  documentation/sidebars.js
Labels: Documentation

#997 Add deletion wiki article
  documentation/docs/concepts/decentralized_identifiers/delete.mdx
  documentation/docs/specs/did/iota_did_method_spec.md
  documentation/sidebars.js
  documentation/src/components/CodeSnippetComponent/index.js
  documentation/src/components/CodeSnippetComponent/styles.css
Labels: Documentation

#992 Update resolution wiki page
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/specs/did/iota_did_method_spec.md
  documentation/yarn.lock
Labels: Documentation

#970 Generalized Resolver
  Cargo.toml
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-stardust/README.md
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/resolver/constructor_input.rs
  bindings/wasm/src/resolver/mixed_resolver.rs
  bindings/wasm/src/resolver/mod.rs
  bindings/wasm/src/resolver/supported_document_types.rs
  bindings/wasm/src/stardust/mod.rs
  bindings/wasm/tests/resolver.ts
  examples/0_basic/2_resolve_did.rs
  examples/Cargo.toml
  identity_credential/src/validator/mod.rs
  identity_credential/src/validator/validator_document.rs
  identity_credential/tests/fixtures/signed_presentation/README.md
  identity_credential/tests/fixtures/signed_presentation/issuer_bar_doc.json
  identity_credential/tests/fixtures/signed_presentation/issuer_iota_doc.json
  identity_credential/tests/fixtures/signed_presentation/presentation.json
  identity_credential/tests/fixtures/signed_presentation/secret_keys.rs
  identity_credential/tests/fixtures/signed_presentation/subject_foo_doc.json
  identity_did/src/did/did.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_iota_core/src/did/iota_did.rs
  identity_resolver/Cargo.toml
  identity_resolver/src/error.rs
  identity_resolver/src/lib.rs
  identity_resolver/src/resolution/commands.rs
  identity_resolver/src/resolution/mod.rs
  identity_resolver/src/resolution/resolver.rs
  identity_resolver/src/resolution/tests/mod.rs
  identity_resolver/src/resolution/tests/presentation_validation_errors.rs
  identity_resolver/src/resolution/tests/resolution_errors.rs
  identity_resolver/src/resolution/tests/send_sync.rs
  identity_resolver/src/resolution/tests/successful_presentation_validation.rs
  identity_resolver/src/resolution/tests/valid_presentation_data.rs
  identity_stardust/Cargo.toml
  identity_stardust/src/client/identity_client.rs
  identity_stardust/src/client/iota_client.rs
  identity_stardust/src/did/stardust_did.rs
  identity_stardust/src/document/stardust_document.rs
Labels: Wasm, Breaking change, Rust

#1004 Update Wasm credential, presentation validators for Stardust
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/create_vc.ts
  bindings/wasm/examples-account/src/create_vp.ts
  bindings/wasm/examples-account/src/revoke_vc.ts
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/credential/presentation_validator.rs
  bindings/wasm/src/credential/types.rs
  bindings/wasm/src/resolver/mod.rs
  bindings/wasm/src/resolver/supported_document_types.rs
  bindings/wasm/tests/credentials.ts
Labels: Wasm, Breaking change

#1005 Stardust Refactor (Part 3)
  identity_agent/Cargo.toml
  identity_agent/benches/didcomm.rs
  identity_agent/src/didcomm/agent.rs
  identity_agent/src/tests/mod.rs
Labels: No changelog, Rust

#1007 Feature-gate `Resolver`
  bindings/wasm/Cargo.toml
  bindings/wasm/src/error.rs
  bindings/wasm/src/resolver/mixed_resolver.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
Labels: Breaking change, Rust

#1001 Stardust Private Tangle Example
  examples/0_basic/0_create_did.rs
  examples/0_basic/1_update_did.rs
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/0_basic/4_delete_did.rs
  examples/1_advanced/0_did_controls_did.rs
  examples/1_advanced/1_did_issues_nft.rs
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
  examples/1_advanced/4_key_exchange.rs
  examples/README.md
  examples/utils/utils.rs
Labels: Documentation, Rust, Patch

#1012 Support case insensitive serialization of `RentStructure`
  bindings/wasm/src/iota/identity_client_ext.rs
Labels: Bug, Wasm, Rust, Patch

#998 Add alias output history example
  examples/1_advanced/5_alias_output_history.rs
  examples/Cargo.toml
  examples/README.md
Labels: No changelog

#1008 Update `update` wiki page
  bindings/wasm/examples/src/ex1_update_did.ts
  documentation/docs/concepts/decentralized_identifiers/update.mdx
  examples/0_basic/1_update_did.rs
Labels: Documentation

#1016 Add 0.7.0-alpha release blurb
  .github/releases/v0.7.0-alpha.1.md
  .github/releases/wasm-v0.7.0-alpha.1.md
Labels: No changelog

#1019 Use iota scoped package
  bindings/wasm/README.md
  bindings/wasm/examples/src/ex0_create_did.ts
  bindings/wasm/lib/tsconfig.json
  bindings/wasm/lib/tsconfig.web.json
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
Labels: No changelog

#1022 Use cargo-license-template
  .github/workflows/format.yml
  .license_template_ignore
  bindings/wasm/src/iota/iota_verification_method.rs
  examples/utils/utils.rs
  rustfmt.toml
Labels: No changelog, Rust

#1026 Chore/rename mixed resolver
  bindings/wasm/docs/api-reference.md
  bindings/wasm/package-lock.json
  bindings/wasm/src/resolver/constructor_input.rs
  bindings/wasm/src/resolver/mod.rs
  bindings/wasm/src/resolver/wasm_resolver.rs
  bindings/wasm/tests/resolver.ts
  identity_credential/Cargo.toml
  identity_credential/src/validator/credential_validator.rs
Labels: Wasm, Breaking change, Rust

#1028 reorg workspace members, error on mismatched dependencies
  .github/actions/publish/publish-rust/action.yml
  Cargo.toml
  examples_legacy/Cargo.toml
  identity_account/Cargo.toml
  identity_account_storage/Cargo.toml
  identity_iota_client_legacy/Cargo.toml
  identity_iota_core_legacy/Cargo.toml
Labels: No changelog

#1029 Pin agent dev-dependencies to crates versions
  identity_agent/Cargo.toml
  identity_agent/benches/agent.rs
  identity_agent/src/tests/handler.rs
  identity_agent/src/tests/remote_account/handler.rs
  identity_agent/src/tests/remote_account/requests.rs
  identity_agent/src/tests/remote_account/tests.rs
Labels: Rust, Patch

#1030 Revert "changelog and versions (#1015)"
  CHANGELOG.md
  bindings/stronghold-nodejs/Cargo.toml
  bindings/wasm/Cargo.toml
  examples/Cargo.toml
  examples_legacy/Cargo.toml
  identity_account/Cargo.toml
  identity_account_storage/Cargo.toml
  identity_agent/Cargo.toml
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_did/Cargo.toml
  identity_diff/Cargo.toml
  identity_diff/derive/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_client_legacy/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_core_legacy/Cargo.toml
  identity_resolver/Cargo.toml
Labels: No changelog

#1031 Remove `identity_agent` reexport
  Cargo.toml
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
Labels: Breaking change, Rust

#1033 Bump agent versions during release
  .github/actions/release/bump-versions/action.yml
Labels: No changelog, Rust

#1034 Remove keywords to satisfy crates.io requirement
  identity_iota_core/Cargo.toml
Labels: No changelog, Rust

#1035 Fix stronghold-nodejs build
  bindings/stronghold-nodejs/Cargo.lock
  identity_account_storage/Cargo.toml
  identity_iota_core_legacy/Cargo.toml
Labels: No changelog, Rust

#1018 Port advanced Stardust examples to Wasm
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/0_create_did.ts
  bindings/wasm/examples/src/tests/0_did_controls_did.ts
  bindings/wasm/examples/src/tests/1_did_issues_nft.ts
  bindings/wasm/examples/src/tests/1_update_did.ts
  bindings/wasm/examples/src/tests/2_nft_owns_did.ts
  bindings/wasm/examples/src/tests/2_resolve_did.ts
  bindings/wasm/examples/src/tests/3_deactivate_did.ts
  bindings/wasm/examples/src/tests/3_did_issues_tokens.ts
  bindings/wasm/examples/src/tests/4_delete_did.ts
  bindings/wasm/examples/src/tests/4_key_exchange.ts
  bindings/wasm/examples/src/util.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/iota/iota_did.rs
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/delete.mdx
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/concepts/decentralized_identifiers/update.mdx
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
Labels: Documentation, Wasm, Added

#1036 Bump versions of legacy crates
  .github/actions/release/bump-versions/action.yml
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/Cargo.toml
  identity_account/Cargo.toml
  identity_account_storage/Cargo.toml
  identity_iota_client_legacy/Cargo.toml
  identity_iota_core_legacy/Cargo.toml
Labels: No changelog

#1024 Expose iteration over verification relationship fields
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  identity_account/src/tests/account.rs
  identity_account/src/tests/updates.rs
  identity_credential/src/validator/credential_validator.rs
  identity_credential/src/validator/presentation_validator.rs
  identity_did/src/document/core_document.rs
  identity_iota_client_legacy/src/tangle/resolver.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core_legacy/src/document/iota_document.rs
Labels: Wasm, Chore, Breaking change, Rust

#1040 Remove legacy example tests from CI
  .github/workflows/build-and-test.yml
Labels: No changelog

#1023 Set Controller and Governor Addresses
  bindings/wasm/src/iota/iota_document.rs
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/document/iota_document_metadata.rs
  identity_iota_core/src/state_metadata/document.rs
Labels: Enhancement, Wasm, Added, Rust

#1021 Example: Custom `Resolver` configuration.
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/5_custom_resolution.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  examples/1_advanced/6_custom_resolution.rs
  examples/Cargo.toml
  examples/README.md
  identity_resolver/src/resolution/resolver.rs
Labels: Documentation, Wasm, Chore, Rust

#1042 Check default and no-default-features in CI
  .github/workflows/build-and-test.yml
Labels: No changelog

#1041 Fix `IotaDocument.unpackFromOutput` parameter type
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/iota/identity_client_ext.rs
  bindings/wasm/src/iota/iota_document.rs
Labels: Wasm, Patch

#943 Use a private tangle in CI
  .github/actions/private-tangle/setup/action.yml
  .github/actions/private-tangle/tear-down/action.yml
  .github/workflows/build-and-test.yml
  README.md
  bindings/wasm/README.md
  bindings/wasm/cypress/e2e/privateTangle.cy.js
  bindings/wasm/examples/src/util.ts
  examples/0_basic/0_create_did.rs
  examples/utils/utils.rs
  identity_iota/README.md
Labels: No changelog

#1043 Add private network wiki info
  documentation/docs/concepts/decentralized_identifiers/create.mdx
Labels: Documentation

#1051 Remove docs version info
  documentation/docusaurus.config.js
Labels: No changelog

#1050 WIP Update `iota-client` to version `2.0.0`
  bindings/wasm/Cargo.toml
  bindings/wasm/README.md
  bindings/wasm/build/lints.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
  bindings/wasm/examples/src/1_advanced/5_custom_resolution.ts
  bindings/wasm/lib/iota_identity_client.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/error.rs
  bindings/wasm/src/iota/identity_client.rs
  bindings/wasm/src/iota/iota_document.rs
  examples/0_basic/1_update_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/0_basic/4_delete_did.rs
  examples/1_advanced/0_did_controls_did.rs
  examples/1_advanced/1_did_issues_nft.rs
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
  examples/1_advanced/4_key_exchange.rs
  examples/1_advanced/5_alias_output_history.rs
  examples/Cargo.toml
  examples/utils/utils.rs
  identity_iota/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/error.rs
  identity_resolver/Cargo.toml
Labels: Wasm, Breaking change, Rust

#1047 Update Resolution wiki article Part 1
  bindings/wasm/src/resolver/wasm_resolver.rs
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
Labels: Wasm, Rust, Patch

#1053 Disable changelog generator for dev releases
  .github/workflows/shared-create-dev-release-pr.yml
Labels: No changelog

#1054 Disable legacy version bump
  .github/actions/release/bump-versions/action.yml
Labels: No changelog

#1056 Update readme, wiki and changelogs
  CHANGELOG.md
  README.md
  bindings/wasm/CHANGELOG.md
  bindings/wasm/README.md
  documentation/docs/getting_started/install.mdx
  documentation/docs/libraries/rust/getting_started.md
  identity_iota/README.md
Labels: No changelog
