Repository iotaledger/identity, pull requests merged in 2022-07, with the labels that each got.

#933 Link Rust API reference in Wiki
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/scripts/coverage.sh
  bindings/wasm/src/lib.rs
  documentation/docs/concepts/advanced/storage_interface.mdx
  documentation/docs/libraries/rust/api_reference.md
  documentation/docs/libraries/rust/getting_started.md
  documentation/sidebars.js
  examples/low-level-api/key_exchange.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/did/macros.rs
  identity_iota_core/src/document/iota_document.rs
Labels: Documentation

#934 Fix Rust API reference links in wiki
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/getting_started/create_and_publish.mdx
Labels: Documentation

#932 Remove documentation field for identity_iota
  identity_iota/Cargo.toml
Labels: Documentation

#936 Fix brittle agent test
  identity_agent/Cargo.toml
  identity_agent/src/tests/handler.rs
Labels: No changelog, Rust

#935 Generalise `CredentialValidator`, `PresentationValidator` to support arbitrary DID Documents
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/credential/presentation_validator.rs
  bindings/wasm/src/credential/validation_options.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/tangle/resolver.rs
  examples/account/create_vc.rs
  examples/account/create_vp.rs
  examples/account/revoke_vc.rs
  identity_account_storage/src/storage/memstore.rs
  identity_account_storage/src/stronghold/tests.rs
  identity_core/src/crypto/proof/jcs_ed25519.rs
  identity_core/src/crypto/signature/core.rs
  identity_credential/Cargo.toml
  identity_credential/README.md
  identity_credential/src/credential/revocation_bitmap_status.rs
  identity_credential/src/error.rs
  identity_credential/src/lib.rs
  identity_credential/src/validator/credential_validator.rs
  identity_credential/src/validator/errors.rs
  identity_credential/src/validator/mod.rs
  identity_credential/src/validator/presentation_validator.rs
  identity_credential/src/validator/test_utils.rs
  identity_credential/src/validator/validation_options.rs
  identity_credential/src/validator/validator_document.rs
  identity_did/src/document/core_document.rs
  identity_did/src/document/mod.rs
  identity_did/src/document/traits.rs
  identity_did/src/revocation/bitmap.rs
  identity_iota/src/lib.rs
  identity_iota_client/Cargo.toml
  identity_iota_client/README.md
  identity_iota_client/src/error.rs
  identity_iota_client/src/lib.rs
  identity_iota_client/src/tangle/resolver.rs
  identity_iota_core/src/document/iota_document.rs
Labels: Wasm, Breaking change, Rust

#925 Fix doc links
  .github/workflows/test-docs-build.yml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/wasm_account/account_builder.rs
  bindings/wasm/src/crypto/wasm_ed25519.rs
  bindings/wasm/src/did/wasm_document.rs
Labels: Documentation

#937 Add Rust documentation check to GitHub Actions
  .github/workflows/test-docs-build.yml
Labels: No changelog

#940 Stardust DID Method Proof-of-Concept
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/format.yml
  .github/workflows/test-docs-build.yml
  identity_stardust/Cargo.toml
  identity_stardust/README.md
  identity_stardust/examples/create_did.rs
  identity_stardust/src/error.rs
  identity_stardust/src/lib.rs
  identity_stardust/src/stardust_document.rs
Labels: Added, Rust

#944 Change `Service` `type` field to allow sets
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/wasm_account/update/create_service.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/tests/account.ts
  bindings/wasm/tests/document.ts
  identity_account/src/tests/updates.rs
  identity_account/src/updates/update.rs
  identity_core/src/common/key_comparable.rs
  identity_core/src/common/one_or_set.rs
  identity_core/src/common/ordered_set.rs
  identity_credential/src/validator/credential_validator.rs
  identity_credential/src/validator/validator_document.rs
  identity_did/src/diff/diff_service.rs
  identity_did/src/revocation/bitmap.rs
  identity_did/src/service/builder.rs
  identity_did/src/service/service.rs
Labels: Wasm, Breaking change, Rust

#946 Fix stack overflow in `CoreDID` `PartialEq` impl
  identity_did/src/did/did.rs
Labels: Breaking change, Rust

#948 Fix broken links
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/overview.md
Labels: Documentation

#947 State metadata serialization for the stardust DID method
  identity_stardust/Cargo.toml
  identity_stardust/examples/create_did.rs
  identity_stardust/src/error.rs
  identity_stardust/src/lib.rs
  identity_stardust/src/stardust_document.rs
  identity_stardust/src/state_metadata/document.rs
  identity_stardust/src/state_metadata/encoding.rs
  identity_stardust/src/state_metadata/mod.rs
  identity_stardust/src/state_metadata/version.rs
Labels: Added, Rust

#951 Add `StardustDocumentMetadata`, implement `StardustDocument` methods
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/did/wasm_document.rs
  identity_account/src/account/account.rs
  identity_account_storage/Cargo.toml
  identity_account_storage/src/storage/memstore.rs
  identity_account_storage/src/storage/stronghold.rs
  identity_account_storage/src/types/encryption/encryption_algorithm.rs
  identity_core/Cargo.toml
  identity_did/src/document/core_document.rs
  identity_iota_client/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_core/src/document/iota_document.rs
  identity_stardust/Cargo.toml
  identity_stardust/examples/create_did.rs
  identity_stardust/src/document/mod.rs
  identity_stardust/src/document/stardust_document.rs
  identity_stardust/src/document/stardust_document_metadata.rs
  identity_stardust/src/error.rs
  identity_stardust/src/lib.rs
  identity_stardust/src/stardust_document.rs
  identity_stardust/src/state_metadata/document.rs
Labels: Breaking change, Rust

#955 Simplify Wasm JSON conversion code with macro
  .github/workflows/shared-build-wasm.yml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/identity/chain_state.rs
  bindings/wasm/src/account/types/agreement_info.rs
  bindings/wasm/src/account/types/auto_save.rs
  bindings/wasm/src/account/types/cek_algorithm.rs
  bindings/wasm/src/account/types/encrypted_data.rs
  bindings/wasm/src/account/types/encryption_algorithm.rs
  bindings/wasm/src/account/types/key_location.rs
  bindings/wasm/src/account/types/method_content.rs
  bindings/wasm/src/account/types/signature.rs
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/common/timestamp.rs
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/credential/validation_options.rs
  bindings/wasm/src/crypto/key_pair.rs
  bindings/wasm/src/crypto/wasm_proof.rs
  bindings/wasm/src/crypto/wasm_proof_options.rs
  bindings/wasm/src/crypto/wasm_proof_purpose.rs
  bindings/wasm/src/did/wasm_did.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  bindings/wasm/src/did/wasm_method_data.rs
  bindings/wasm/src/did/wasm_method_scope.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/did/wasm_verifier_options.rs
  bindings/wasm/src/macros.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/explorer.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/receipt.rs
  bindings/wasm/src/tangle/resolver.rs
  bindings/wasm/tests/wasm.rs
Labels: Wasm, No changelog, Patch

#949 StardustDID
  README.md
  identity_stardust/Cargo.toml
  identity_stardust/README.md
  identity_stardust/src/did/mod.rs
  identity_stardust/src/did/stardust_did.rs
  identity_stardust/src/error.rs
  identity_stardust/src/lib.rs
  identity_stardust/src/network/mod.rs
  identity_stardust/src/network/network_name.rs
Labels: Added, Rust

#958 Feature-gate `iota-client` dependency, integrate `StardustDID`
  identity_stardust/Cargo.toml
  identity_stardust/examples/create_did.rs
  identity_stardust/src/did/mod.rs
  identity_stardust/src/did/stardust_did.rs
  identity_stardust/src/document/mod.rs
  identity_stardust/src/document/stardust_document.rs
  identity_stardust/src/error.rs
  identity_stardust/src/lib.rs
  identity_stardust/src/state_metadata/document.rs
Labels: Breaking change, Rust

#956 Update wiki DIDComm flowcharts, add banners
  documentation/docs/decentralized_identity.md
  documentation/docs/getting_started/overview.md
  documentation/docs/introduction.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/static/img/Banner/banner_decentralized_identity.svg
  documentation/static/img/Banner/banner_identity.svg
  documentation/static/img/Banner/banner_identity_getting_started.svg
  documentation/static/img/didcomm/authentication.drawio.svg
  documentation/static/img/didcomm/connection.drawio.svg
  documentation/static/img/didcomm/issuance.drawio.svg
  documentation/static/img/didcomm/post.drawio.svg
  documentation/static/img/didcomm/presentation.drawio.svg
  documentation/static/img/didcomm/revocation-options.drawio.svg
  documentation/static/img/didcomm/revocation.drawio.svg
  documentation/static/img/didcomm/signing.drawio.svg
  documentation/static/img/didcomm/termination.drawio.svg
Labels: Documentation

#959 Change CI params to use all-features consistently
  .github/workflows/build-and-test.yml
Labels: No changelog

#962 Update wiki DIDComm flowcharts, add banners (#956)
  documentation/docs/decentralized_identity.md
  documentation/docs/getting_started/overview.md
  documentation/docs/introduction.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/static/img/Banner/banner_decentralized_identity.svg
  documentation/static/img/Banner/banner_identity.svg
  documentation/static/img/Banner/banner_identity_getting_started.svg
  documentation/static/img/didcomm/authentication.drawio.svg
  documentation/static/img/didcomm/connection.drawio.svg
  documentation/static/img/didcomm/issuance.drawio.svg
  documentation/static/img/didcomm/post.drawio.svg
  documentation/static/img/didcomm/presentation.drawio.svg
  documentation/static/img/didcomm/revocation-options.drawio.svg
  documentation/static/img/didcomm/revocation.drawio.svg
  documentation/static/img/didcomm/signing.drawio.svg
  documentation/static/img/didcomm/termination.drawio.svg
Labels: Documentation

#961 Update wiki DIDComm flowcharts, add banners (#956)
  documentation/docs/decentralized_identity.md
  documentation/docs/getting_started/overview.md
  documentation/docs/introduction.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/static/img/Banner/banner_decentralized_identity.svg
  documentation/static/img/Banner/banner_identity.svg
  documentation/static/img/Banner/banner_identity_getting_started.svg
  documentation/static/img/didcomm/authentication.drawio.svg
  documentation/static/img/didcomm/connection.drawio.svg
  documentation/static/img/didcomm/issuance.drawio.svg
  documentation/static/img/didcomm/post.drawio.svg
  documentation/static/img/didcomm/presentation.drawio.svg
  documentation/static/img/didcomm/revocation-options.drawio.svg
  documentation/static/img/didcomm/revocation.drawio.svg
  documentation/static/img/didcomm/signing.drawio.svg
  documentation/static/img/didcomm/termination.drawio.svg
Labels: Documentation
