Repository iotaledger/identity, pull requests merged in 2022-03, with the labels that each got.

#678 Remove legacy build
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/static/index.html
  bindings/wasm/webpack.config.js
Labels: No changelog

#680 Add Wasm `Service` constructor and field getters
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/service.rs
Labels: Wasm, Added

#682 Add `Client` fallback to local PoW option
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/tangle/config.rs
  identity-iota/src/tangle/client_builder.rs
Labels: Wasm, Added, Rust

#689 Add minimal Readme, License, and update package name of stronghold bindings
  .github/workflows/stronghold-bindings.yml
  bindings/stronghold-nodejs/Cargo.toml
  bindings/stronghold-nodejs/LICENSE
  bindings/stronghold-nodejs/README.md
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
Labels: No changelog

#679 Complete `Document` Wasm bindings
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_method_relationship.rs
  bindings/wasm/src/tangle/resolver.rs
  bindings/wasm/tests/wasm.rs
Labels: Wasm, Added

#697 Enable retries for `txm` tests
  bindings/wasm/package.json
  bindings/wasm/tests/txm_readme.js
Labels: No changelog

#698 Simplify test timeout config
  bindings/wasm/examples/src/tests/node/createDiff.js
  bindings/wasm/examples/src/tests/node/createIdentity.js
  bindings/wasm/examples/src/tests/node/createVP.js
  bindings/wasm/examples/src/tests/node/create_vc.js
  bindings/wasm/examples/src/tests/node/manipulateIdentity.js
  bindings/wasm/examples/src/tests/node/merkleKey.js
  bindings/wasm/examples/src/tests/node/privateTangle.js
  bindings/wasm/examples/src/tests/node/resolution.js
  bindings/wasm/examples/src/tests/node/resolveHistory.js
  bindings/wasm/examples/src/tests/node/revokeVC.js
  bindings/wasm/package.json
Labels: No changelog

#599 Feat/credential validation mvp
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/credential/presentation_validator.rs
  bindings/wasm/src/credential/validation_options.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/did/wasm_verifier_options.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/resolver.rs
  bindings/wasm/tests/wasm.rs
  examples/low-level-api/common.rs
  examples/low-level-api/create_vc.rs
  examples/low-level-api/create_vp.rs
  examples/low-level-api/merkle_key.rs
  examples/low-level-api/revoke_vc.rs
  identity-credential/src/credential/builder.rs
  identity-credential/src/error.rs
  identity-iota/Cargo.toml
  identity-iota/src/credential/credential_validator.rs
  identity-iota/src/credential/errors.rs
  identity-iota/src/credential/mod.rs
  identity-iota/src/credential/presentation_validator.rs
  identity-iota/src/credential/test_utils.rs
  identity-iota/src/credential/validation_options.rs
  identity-iota/src/credential/validator.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/document/resolved_iota_document.rs
  identity-iota/src/error.rs
  identity-iota/src/tangle/resolver.rs
  identity-iota/src/tangle/traits.rs
Labels: Wasm, Breaking change, Rust

#701 Use chocolatey instead of scoop in CI
  .github/actions/rust/sccache/setup-sccache/action.yml
Labels: No changelog

#694 Enable Wasm weak references
  .github/actions/publish/publish-wasm/action.yml
  .github/actions/rust/sccache/setup-sccache/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/coverage.yml
  bindings/wasm/README.md
  bindings/wasm/build/lints.js
  bindings/wasm/build/node.js
  bindings/wasm/build/web.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/common/timestamp.rs
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/config.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/resolver.rs
  bindings/wasm/tests/wasm.rs
Labels: Wasm, Patch

#691 Update Stronghold
  identity-account/Cargo.toml
  identity-account/src/error.rs
  identity-account/src/storage/stronghold.rs
  identity-account/src/stronghold/context.rs
  identity-account/src/stronghold/error.rs
  identity-account/src/stronghold/hint.rs
  identity-account/src/stronghold/mod.rs
  identity-account/src/stronghold/records.rs
  identity-account/src/stronghold/result.rs
  identity-account/src/stronghold/snapshot.rs
  identity-account/src/stronghold/status.rs
  identity-account/src/stronghold/store.rs
  identity-account/src/stronghold/tests.rs
  identity-account/src/stronghold/vault.rs
  identity-account/src/utils/fs.rs
Labels: Added, Chore, Rust

#702 Feature gate `StrongholdError` import
  identity-account/src/error.rs
Labels: Bug, Chore, No changelog, Rust

#696 Replace Wasm `Config` with `ClientConfig` interface
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolution.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/package.json
  bindings/wasm/src/did/wasm_method_relationship.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/client_config.rs
  bindings/wasm/src/tangle/config.rs
  bindings/wasm/src/tangle/message.rs
  bindings/wasm/src/tangle/mod.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/resolver.rs
  identity-account/src/tests/account.rs
  identity-iota/src/tangle/client.rs
Labels: Wasm, Breaking change

#705 Add deep clone function in Wasm
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/credential/validation_options.rs
  bindings/wasm/src/crypto/key_collection.rs
  bindings/wasm/src/crypto/key_pair.rs
  bindings/wasm/src/crypto/mod.rs
  bindings/wasm/src/crypto/wasm_proof_purpose.rs
  bindings/wasm/src/crypto/wasm_signature_options.rs
  bindings/wasm/src/did/wasm_did.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  bindings/wasm/src/did/wasm_method_scope.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/did/wasm_verifier_options.rs
  bindings/wasm/src/macros.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/receipt.rs
  bindings/wasm/tests/wasm.rs
Labels: Wasm, Added

#704 Fix link for feature discovery in DIDComm protocols
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/connection.md
Labels: Documentation

#708 Add Stronghold bindings clippy, fmt checks in CI
  .github/actions/rust/sccache/setup-sccache/action.yml
  .github/workflows/clippy.yml
  .github/workflows/format.yml
  bindings/stronghold-nodejs/build.rs
Labels: No changelog

#707 Generify `Account::client` over `Rc`, `Arc`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/account/wasm_account/account_builder.rs
  bindings/wasm/src/account/wasm_account/update/attach_method_relationships.rs
  bindings/wasm/src/account/wasm_account/update/create_method.rs
  bindings/wasm/src/account/wasm_account/update/create_service.rs
  bindings/wasm/src/account/wasm_account/update/detach_method_relationships.rs
  bindings/wasm/src/account/wasm_account/update/set_also_known_as.rs
  bindings/wasm/src/account/wasm_account/update/set_controller.rs
  identity-account/src/account/account.rs
  identity-account/src/account/builder.rs
  identity-account/src/account/config.rs
  identity-account/src/identity/identity_updater.rs
  identity-account/src/updates/macros.rs
  identity-account/src/updates/update.rs
  identity-iota/src/tangle/client.rs
  identity-iota/src/tangle/mod.rs
  identity-iota/src/tangle/resolver.rs
  identity-iota/src/tangle/traits.rs
Labels: Added, Rust

#712 Update iota.rs to include timeout bugfix
  Cargo.toml
  identity-comm/Cargo.toml
  identity-iota/Cargo.toml
  identity/Cargo.toml
  identity/src/lib.rs
Labels: Bug, Rust, Patch

#690 Run stronghold bindings in build-and-test and prepare release
  .github/actions/publish/publish-stronghold-nodejs/action.yml
  .github/actions/publish/publish-wasm/action.yml
  .github/actions/release/bump-versions/action.yml
  .github/actions/rust/rust-setup/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  .github/workflows/shared-build-wasm.yml
  .github/workflows/stronghold-bindings.yml
  .github/workflows/wasm-automatic-release-and-publish.yml
  .gitignore
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
  bindings/wasm/build/node.js
  bindings/wasm/build/utils/generatePackage.js
  bindings/wasm/build/web.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/config.ts
  bindings/wasm/examples-account/src/create_did.ts
  bindings/wasm/examples-account/src/lazy.ts
  bindings/wasm/examples-account/src/manipulate_did.ts
  bindings/wasm/examples-account/src/memory_storage.ts
  bindings/wasm/examples-account/src/multiple_identities.ts
  bindings/wasm/examples-account/src/unchecked.ts
  bindings/wasm/package.json
  bindings/wasm/src/account/identity/chain_state.rs
  bindings/wasm/src/account/identity/identity_state.rs
  bindings/wasm/src/account/storage/traits.rs
  bindings/wasm/src/account/types/auto_save.rs
  bindings/wasm/src/account/types/identity_setup.rs
  bindings/wasm/src/account/types/method_secret.rs
  bindings/wasm/src/account/types/signature.rs
  bindings/wasm/src/account/wasm_account/account_builder.rs
  bindings/wasm/src/account/wasm_account/update/create_method.rs
  bindings/wasm/src/common/timestamp.rs
  bindings/wasm/src/crypto/key_collection.rs
  bindings/wasm/src/crypto/mod.rs
  bindings/wasm/src/crypto/wasm_proof_purpose.rs
  bindings/wasm/src/did/wasm_method_scope.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_verifier_options.rs
  identity-account/src/account/config.rs
  identity-account/src/types/method_secret.rs
  identity-core/src/crypto/key/collection.rs
Labels: No changelog

#717 Fix/bindings pr comments
  bindings/stronghold-nodejs/Cargo.toml
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/README.md
  bindings/wasm/examples-account/src/config.ts
  bindings/wasm/examples-account/src/memory_storage.ts
  bindings/wasm/examples-account/src/multiple_identities.ts
  bindings/wasm/examples-account/src/signing.ts
  bindings/wasm/examples-account/src/tests/multiple_identities.ts
  bindings/wasm/src/account/wasm_account/account_builder.rs
  bindings/wasm/src/account/wasm_account/update/delete_method.rs
  bindings/wasm/src/core/ed25519.rs
  bindings/wasm/src/core/mod.rs
  bindings/wasm/src/core/secret_key.rs
  bindings/wasm/src/error.rs
  identity-account-storage/Cargo.toml
  identity-account-storage/src/storage/traits.rs
  identity-account-storage/src/types/signature.rs
  identity-account/Cargo.toml
  identity-core/Cargo.toml
  identity-core/src/crypto/key/key.rs
  identity/Cargo.toml
Labels: No changelog

#706 Replace Wasm getters and setters with methods
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/unchecked.ts
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolution.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/src/account/types/key_location.rs
  bindings/wasm/src/account/types/signature.rs
  bindings/wasm/src/crypto/key_pair.rs
  bindings/wasm/src/did/wasm_did.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/src/tangle/receipt.rs
Labels: Wasm, Breaking change

#723 Update iota.rs to lower `zeroize` version requirement
  identity-iota/Cargo.toml
Labels: Bug, No changelog, Rust

#725 Install cargo-edit for Wasm releases, fix version bump in CI
  .github/actions/release/bump-versions/action.yml
Labels: No changelog

#728 Move DID Document proof outside metadata
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  documentation/docs/specs/did/iota_did_method_spec.md
  identity-iota-core/src/diff/diff_iota_document.rs
  identity-iota-core/src/diff/diff_iota_document_metadata.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota-core/src/document/iota_document_metadata.rs
  identity-iota/src/chain/document_chain.rs
Labels: Wasm, Breaking change, Rust

#732 Remove `publicKeyJwk`
  identity-did/src/diff/method_data.rs
  identity-did/src/verification/method_data.rs
Labels: Wasm, Rust, Removed

#730 Add v0.5.0-dev.5 release blurb
  .github/releases/v0.5.0-dev.5.md
  .github/releases/wasm-v0.5.0-dev.5.md
Labels: No changelog

#736 Remove Wasm prepublish step
  bindings/wasm/package.json
Labels: No changelog

#743 Fix stronghold triples
  bindings/stronghold-nodejs/package.json
Labels: No changelog

#751 Revert release changes
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
Labels: No changelog

#733 Remove `Storage::set_password`
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/wasm/examples-account/src/memory_storage.ts
  bindings/wasm/src/account/storage/traits.rs
  identity-account-storage/src/storage/memstore.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account-storage/src/storage/traits.rs
Labels: Wasm, Rust, Removed

#752 Fix Stronghold nodejs binding dist artifact
  .github/actions/publish/publish-stronghold-nodejs/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
Labels: No changelog

#734 Change Wasm key types to `UInt8Array`
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_vc.js
  bindings/wasm/examples/src/create_vp.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/src/account/storage/traits.rs
  bindings/wasm/src/account/types/method_secret.rs
  bindings/wasm/src/account/types/signature.rs
  bindings/wasm/src/core/ed25519.rs
  bindings/wasm/src/core/secret_key.rs
  bindings/wasm/src/crypto/key_collection.rs
  bindings/wasm/src/crypto/key_pair.rs
  bindings/wasm/src/crypto/wasm_x25519.rs
  bindings/wasm/src/did/wasm_did.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/tests/wasm.rs
Labels: Enhancement, Wasm, Breaking change

#760 Fix `Uint8Array` references
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/storage/traits.rs
  bindings/wasm/src/account/types/method_secret.rs
  bindings/wasm/src/core/secret_key.rs
  bindings/wasm/src/crypto/key_pair.rs
  bindings/wasm/src/did/wasm_method_data.rs
Labels: Wasm, Patch

#709 Combine resolve_method functions
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/tests/wasm.rs
  examples/low-level-api/key_exchange.rs
  identity-account/src/account/account.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/updates.rs
  identity-account/src/updates/update.rs
  identity-did/src/document/core_document.rs
  identity-did/src/verifiable/document_signer.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota/src/tangle/publish.rs
Labels: Chore, Breaking change, Rust

#759 Deprecate diff chain features
  bindings/wasm/cypress/integration/createDiff.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/index.html
  bindings/wasm/examples/src/node.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/tests/node/createDiff.js
  bindings/wasm/examples/src/web.js
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/chain/document_history.rs
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/resolver.rs
  examples/Cargo.toml
  examples/README.md
  examples/low-level-api/diff_chain.rs
  examples/low-level-api/resolve_history.rs
  identity-account-storage/src/identity/chain_state.rs
  identity-account-storage/src/lib.rs
  identity-account/src/account/account.rs
  identity-account/src/account/publish_options.rs
  identity-account/src/lib.rs
  identity-core/src/error.rs
  identity-core/src/lib.rs
  identity-did/src/lib.rs
  identity-diff/src/lib.rs
  identity-diff/tests/derive_enum_test.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota-core/src/error.rs
  identity-iota-core/src/lib.rs
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/chain/document_history.rs
  identity-iota/src/document/resolved_iota_document.rs
  identity-iota/src/lib.rs
  identity-iota/src/tangle/client.rs
  identity-iota/src/tangle/publish.rs
  identity-iota/src/tangle/resolver.rs
  identity/benches/benchmark.rs
  identity/benches/diff_chain.rs
  identity/src/lib.rs
Labels: Wasm, Rust, Deprecated

#738 Refactor Storage Signature
  bindings/stronghold-nodejs/Cargo.toml
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/account/types/signature.rs
  identity-account-storage/Cargo.toml
  identity-account-storage/src/crypto/remote.rs
  identity-account-storage/src/storage/memstore.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account-storage/src/types/signature.rs
  identity-core/Cargo.toml
  identity-core/src/crypto/key/key.rs
  identity/Cargo.toml
Labels: Enhancement, Wasm, Breaking change, Rust

#763 Fix stronghold.ts key types
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/wasm/docs/api-reference.md
Labels: Bug

#754 Add release description for `v0.5.0-dev.6`
  .github/releases/v0.5.0-dev.6.md
  .github/releases/wasm-v0.5.0-dev.6.md
Labels: No changelog

#767 Fix stronghold.ts
  bindings/wasm/src/account/storage/traits.rs
Labels: No changelog

#765 Fail on rollup ts errors
  .github/workflows/build-and-test.yml
  bindings/stronghold-nodejs/package.json
  bindings/stronghold-nodejs/rollup.config.js
Labels: No changelog

#766 Add stronghold readme example
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  bindings/stronghold-nodejs/README.md
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
  bindings/stronghold-nodejs/tests/txm_readme.js
Labels: No changelog

#770 Remove diff chain example from documentation to fix wiki
  documentation/docs/advanced/did_messages.mdx
Labels: No changelog

#764 Replace `MethodSecret` with `MethodContent` enum
  bindings/stronghold-nodejs/examples/src/tests/multiple_identities.ts
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/config.ts
  bindings/wasm/examples-account/src/create_did.ts
  bindings/wasm/examples-account/src/lazy.ts
  bindings/wasm/examples-account/src/manipulate_did.ts
  bindings/wasm/examples-account/src/multiple_identities.ts
  bindings/wasm/examples-account/src/signing.ts
  bindings/wasm/package.json
  bindings/wasm/src/account/types/identity_setup.rs
  bindings/wasm/src/account/types/method_content.rs
  bindings/wasm/src/account/types/method_secret.rs
  bindings/wasm/src/account/types/mod.rs
  bindings/wasm/src/account/wasm_account/account_builder.rs
  bindings/wasm/src/account/wasm_account/update/create_method.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/tests/account.js
  bindings/wasm/tests/wasm.rs
  examples/account/manipulate_did.rs
  examples/account/multiple_identities.rs
  examples/account/signing.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account/src/account/account.rs
  identity-account/src/account/builder.rs
  identity-account/src/identity/identity_setup.rs
  identity-account/src/identity/mod.rs
  identity-account/src/lib.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/updates.rs
  identity-account/src/types/identity_setup.rs
  identity-account/src/types/identity_updater.rs
  identity-account/src/types/method_content.rs
  identity-account/src/types/method_secret.rs
  identity-account/src/types/mod.rs
  identity-account/src/updates/error.rs
  identity-account/src/updates/macros.rs
  identity-account/src/updates/mod.rs
  identity-account/src/updates/update.rs
  identity-did/src/verification/verification_method.rs
  identity/src/lib.rs
Labels: Wasm, Breaking change, Rust

#772 Expose Ed25519, X25519 length constants
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/core/ed25519.rs
  bindings/wasm/src/core/mod.rs
  bindings/wasm/src/core/secret_key.rs
  bindings/wasm/src/crypto/mod.rs
  bindings/wasm/src/crypto/wasm_ed25519.rs
  bindings/wasm/src/crypto/wasm_x25519.rs
  bindings/wasm/src/lib.rs
  identity-account-storage/Cargo.toml
  identity-account-storage/src/storage/memstore.rs
  identity-account/Cargo.toml
  identity-account/src/account/account.rs
  identity-account/src/error.rs
  identity-account/src/updates/update.rs
  identity-core/src/crypto/key/ed25519.rs
  identity-core/src/crypto/key/mod.rs
  identity-core/src/crypto/key/pair.rs
  identity-core/src/crypto/key/x25519.rs
  identity-core/src/crypto/mod.rs
  identity-core/src/crypto/signature/mod.rs
  identity-core/src/utils/ed25519.rs
  identity-core/src/utils/mod.rs
Labels: Wasm, Added, Rust

#753 Change document metadata `created`, `updated` to be optional
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_document_metadata.rs
  examples/account/unchecked.rs
  examples/low-level-api/common.rs
  examples/low-level-api/manipulate_did.rs
  examples/low-level-api/resolve_history.rs
  examples/low-level-api/revoke_vc.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/updates.rs
  identity-account/src/updates/update.rs
  identity-diff/src/option.rs
  identity-iota-core/src/diff/diff_iota_document_metadata.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota-core/src/document/iota_document_metadata.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/resolver.rs
  identity/benches/diff_chain.rs
Labels: Wasm, Breaking change, Rust

#775 Improve `attach_` and `detach_method_relationships` in wasm bindings
  bindings/wasm/src/account/wasm_account/update/attach_method_relationships.rs
  bindings/wasm/src/account/wasm_account/update/detach_method_relationships.rs
  examples/account/manipulate_did.rs
Labels: Wasm, Chore, No changelog

#774 Remove `AccountStorage`
  README.md
  bindings/stronghold-nodejs/.license_template
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/account/wasm_account/account_builder.rs
  examples/account/config.rs
  examples/account/create_did.rs
  examples/account/lazy.rs
  examples/account/manipulate_did.rs
  examples/account/multiple_identities.rs
  examples/account/signing.rs
  examples/account/unchecked.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account/Cargo.toml
  identity-account/src/account/builder.rs
  identity-account/src/tests/account.rs
Labels: Rust, Removed

#729 Refactor `KeyLocation`
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
  bindings/stronghold-nodejs/src/account/identity/did_location_tuple.rs
  bindings/stronghold-nodejs/src/account/identity/document.rs
  bindings/stronghold-nodejs/src/account/identity/mod.rs
  bindings/stronghold-nodejs/src/account/mod.rs
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/stronghold-nodejs/src/account/types/key_type.rs
  bindings/stronghold-nodejs/src/account/types/mod.rs
  bindings/stronghold-nodejs/src/did/napi_did.rs
  bindings/stronghold-nodejs/src/error.rs
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/memory_storage.ts
  bindings/wasm/src/account/identity/identity_state.rs
  bindings/wasm/src/account/identity/mod.rs
  bindings/wasm/src/account/storage/traits.rs
  bindings/wasm/src/account/types/generation.rs
  bindings/wasm/src/account/types/key_location.rs
  bindings/wasm/src/account/types/mod.rs
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/tests/wasm.rs
  identity-account-storage/Cargo.toml
  identity-account-storage/src/crypto/remote.rs
  identity-account-storage/src/error.rs
  identity-account-storage/src/identity/identity_state.rs
  identity-account-storage/src/identity/mod.rs
  identity-account-storage/src/storage/memstore.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account-storage/src/storage/traits.rs
  identity-account-storage/src/stronghold/client_path.rs
  identity-account-storage/src/stronghold/error.rs
  identity-account-storage/src/stronghold/mod.rs
  identity-account-storage/src/stronghold/snapshot.rs
  identity-account-storage/src/stronghold/store.rs
  identity-account-storage/src/stronghold/tests.rs
  identity-account-storage/src/stronghold/vault.rs
  identity-account-storage/src/types/generation.rs
  identity-account-storage/src/types/key_location.rs
  identity-account-storage/src/types/mod.rs
  identity-account/src/account/account.rs
  identity-account/src/error.rs
  identity-account/src/tests/account.rs
  identity-account/src/tests/mod.rs
  identity-account/src/tests/updates.rs
  identity-account/src/tests/util.rs
  identity-account/src/types/method_content.rs
  identity-account/src/updates/update.rs
  identity/src/lib.rs
Labels: Breaking change, Rust

#779 Add 0.5.0 release description
  .github/releases/v0.5.0.md
  .github/releases/wasm-v0.5.0.md
Labels: No changelog

#780 Update Wasm Readme examples
  bindings/wasm/README.md
Labels: No changelog

#783 Fix release description formatting
  .github/releases/v0.5.0.md
  .github/releases/wasm-v0.5.0.md
Labels: No changelog
