Repository iotaledger/identity, pull requests merged in 2022-01, with the labels that each got.

#569 Fix clippy lints
  .github/workflows/coverage.yml
  .github/workflows/format.yml
  .github/workflows/scripts/coverage.sh
  identity-account/src/account/builder.rs
  identity-account/src/account/publish_options.rs
  identity-account/src/updates/macros.rs
  identity-account/src/updates/update.rs
  identity-core/src/crypto/key/collection.rs
  identity-core/src/crypto/signature/signature_options.rs
  identity-did/src/did/did_url.rs
  identity-did/src/verifiable/document_signer.rs
  identity-did/src/verifiable/document_verifier.rs
  identity-did/src/verifiable/verifier_options.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/tangle/client_builder.rs
Labels: No changelog, Rust

#572 Manual changelog descriptions
  .github/actions/release/changelog-generator/action.yml
  .github/releases/v0.3.0.md
  .github/releases/v0.5.0-dev.1.md
  .github/releases/wasm-v0.5.0-dev.1.md
  .github/workflows/scripts/populate-changelog-descriptions.sh
Labels: No changelog

#575 Fix script path for changelog descriptions
  .github/actions/release/changelog-generator/action.yml
Labels: No changelog

#576 Fix changelog path for release descriptions
  .github/actions/release/changelog-generator/action.yml
Labels: No changelog

#578 fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch

#580 Use own docker image for changelog generator
  .github/actions/release/changelog-generator/action.yml
Labels: No changelog

#579 Enable local proof-of-work fallback
  identity-iota/Cargo.toml
  identity-iota/src/tangle/client_builder.rs
Labels: Wasm, Rust, Patch

#581 Enable local proof-of-work fallback
  identity-iota/Cargo.toml
Labels: Wasm, Patch

#583 Fix workflow variables
  .github/workflows/shared-release.yml
Labels: No changelog

#584 Fix workflow variables
  .github/workflows/shared-release.yml
Labels: No changelog

#559 Add description for epic branch merges
  documentation/docs/workflow.md
Labels: Documentation

#553 Fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch

#587 Fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch

#588 Fix node-fetch conflict when multiple versions are included
  bindings/wasm/build/node.js
Labels: Wasm, Patch

#590 Ignore changelog tags not on dev or main
  .github/workflows/shared-create-dev-release-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
Labels: No changelog

#591 Ignore tags not on dev or main
  .github/workflows/shared-create-dev-release-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
Labels: No changelog

#598 Remove JSON string escaping in diff messages
  .github/releases/v0.5.0-dev.3.md
  .github/releases/wasm-v0.5.0-dev.3.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_diff_message.rs
  bindings/wasm/src/did/wasm_document.rs
  documentation/docs/specs/did/iota_did_method_spec.md
  identity-did/src/diff/diff_service.rs
  identity-iota/src/diff/diff_message.rs
Labels: Wasm, Breaking change, Rust

#600 Fix `ResolvedDocument.integrationMessageId`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_resolved_document.rs
Labels: Wasm, Patch

#604 Change `Account::state` visibility to `pub(crate)`
  bindings/wasm/src/lib.rs
  examples/account/create_did.rs
  identity-account/src/account/account.rs
Labels: Rust, Removed

#611 Fix diff properties (de)serialization
  bindings/wasm/examples/src/diff_chain.js
  documentation/docs/specs/did/iota_did_method_spec.md
  examples/low-level-api/diff_chain.rs
  identity-did/src/diff/diff_document.rs
  identity-did/src/diff/diff_method.rs
  identity-did/src/diff/diff_service.rs
  identity-diff/src/object.rs
  identity-iota/src/diff/diff_iota_document_metadata.rs
  identity-iota/src/tangle/message/compression_brotli.rs
  identity-iota/src/tangle/message/message_ext.rs
Labels: Wasm, Rust, Patch

#612 Fix `Window` undefined error
  identity-iota/Cargo.toml
Labels: Wasm, Patch

#606 Remove `DocumentVerifier`
  bindings/wasm/src/did/wasm_document.rs
  examples/account/signing.rs
  identity-did/src/document/core_document.rs
  identity-did/src/verifiable/document_verifier.rs
  identity-did/src/verifiable/mod.rs
  identity-did/src/verifiable/tests.rs
  identity-iota/src/credential/validator.rs
  identity-iota/src/document/iota_document.rs
Labels: Breaking change, Rust

#605 Fix dependent diff updates being rejected
  bindings/wasm/examples/src/diff_chain.js
  examples/low-level-api/diff_chain.rs
  identity-did/src/diff/diff_document.rs
  identity-did/src/diff/diff_method.rs
  identity-diff/derive/src/model.rs
  identity-diff/src/object.rs
  identity-iota/Cargo.toml
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/diff/diff_iota_document_metadata.rs
  identity-iota/src/document/iota_document.rs
  identity-iota/src/document/iota_document_metadata.rs
  identity-iota/src/tangle/message/compression_brotli.rs
  identity-iota/src/tangle/message/message_ext.rs
Labels: Wasm, Breaking change, Rust

#617 Use node-fetch >= 2.6.7
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: Wasm, Patch

#616 Add union type parameters
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/create_did.js
  bindings/wasm/examples/src/diff_chain.js
  bindings/wasm/examples/src/manipulate_did.js
  bindings/wasm/examples/src/merkle_key.js
  bindings/wasm/examples/src/private_tangle.js
  bindings/wasm/examples/src/resolve_history.js
  bindings/wasm/examples/src/revoke_vc.js
  bindings/wasm/package.json
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_did.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/tangle/client.rs
  bindings/wasm/src/tangle/network.rs
  bindings/wasm/tests/wasm.rs
Labels: Wasm, Breaking change

#621 Use latest version of wasm-pack
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#620 Fix changelog labels
  .github/.github_changelog_generator
  bindings/wasm/.github_changelog_generator
Labels: No changelog

#626 Upgrade cypress
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#629 Pin wasm-pack version to 0.10.1
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#628 Update mocha to the latest version
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#623 Support verification methods with the same fragment
  identity-did/src/verification/method_query.rs
  identity-iota/src/document/iota_document.rs
Labels: Wasm, Rust, Patch

#627 Upgrade webpack and libs
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#630 Update http-server to 14.1.0
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#632 Change `also_known_as` type to `OrderedSet`
  identity-did/src/diff/diff_document.rs
  identity-did/src/document/core_document.rs
  identity-iota/src/document/iota_document.rs
Labels: Wasm, Breaking change, Rust

#634 Rename `MethodQuery` to `DIDUrlQuery`, move `OrderedSet`, `KeyComparable`
  identity-account/src/tests/account.rs
  identity-account/src/tests/updates.rs
  identity-account/src/updates/update.rs
  identity-core/src/common/key_comparable.rs
  identity-core/src/common/mod.rs
  identity-core/src/common/ordered_set.rs
  identity-core/src/common/url.rs
  identity-core/src/error.rs
  identity-did/src/did/did_url.rs
  identity-did/src/diff/diff_document.rs
  identity-did/src/diff/diff_service.rs
  identity-did/src/diff/mod.rs
  identity-did/src/diff/ordered_set.rs
  identity-did/src/document/core_document.rs
  identity-did/src/error.rs
  identity-did/src/resolution/impls.rs
  identity-did/src/service/service.rs
  identity-did/src/service/service_endpoint.rs
  identity-did/src/utils/did_url_query.rs
  identity-did/src/utils/key_comparable.rs
  identity-did/src/utils/mod.rs
  identity-did/src/utils/queryable.rs
  identity-did/src/verifiable/document_signer.rs
  identity-did/src/verification/method_ref.rs
  identity-did/src/verification/mod.rs
  identity-did/src/verification/verification_method.rs
  identity-diff/src/lib.rs
  identity-iota/src/document/iota_document.rs
Labels: Breaking change, Rust

#637 Update jsdoc-to-markdown to 7.1.1
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog
