Repository iotaledger/identity, pull requests merged in 2022-06, with the labels that each got.

#866 Remove rust cheatsheet, rework intro
  documentation/docs/introduction.md
  documentation/docs/libraries/rust/cheat_sheet.md
  documentation/sidebars.js
Labels: Documentation

#862 Remove unused resolution code
  bindings/wasm/src/lib.rs
  identity-did/src/error.rs
  identity-did/src/lib.rs
  identity-did/src/resolution/dereference.rs
  identity-did/src/resolution/document_metadata.rs
  identity-did/src/resolution/error_kind.rs
  identity-did/src/resolution/impls.rs
  identity-did/src/resolution/input_metadata.rs
  identity-did/src/resolution/mod.rs
  identity-did/src/resolution/resolution.rs
  identity-did/src/resolution/resolution_metadata.rs
  identity-did/src/resolution/resource.rs
  identity-did/src/resolution/traits.rs
  identity-iota/src/lib.rs
  identity-iota/src/resolver.rs
  identity/src/lib.rs
Labels: Rust, Removed

#809 Add Diffie-Hellman key exchange to Account
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/Cargo.toml
  bindings/stronghold-nodejs/examples/src/tests/encryption.ts
  bindings/stronghold-nodejs/examples/src/tests/storage_test_suite.ts
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/src/account/storage/stronghold.rs
  bindings/stronghold-nodejs/src/account/types/cek_algorithm.rs
  bindings/stronghold-nodejs/src/account/types/encrypted_data.rs
  bindings/stronghold-nodejs/src/account/types/encryption_algorithm.rs
  bindings/stronghold-nodejs/src/account/types/mod.rs
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/README.md
  bindings/wasm/examples-account/src/custom_storage.ts
  bindings/wasm/examples-account/src/encryption.ts
  bindings/wasm/examples-account/src/node.ts
  bindings/wasm/examples-account/src/tests/encryption.ts
  bindings/wasm/src/account/storage/test_suite.rs
  bindings/wasm/src/account/storage/traits.rs
  bindings/wasm/src/account/types/agreement_info.rs
  bindings/wasm/src/account/types/cek_algorithm.rs
  bindings/wasm/src/account/types/encrypted_data.rs
  bindings/wasm/src/account/types/encryption_algorithm.rs
  bindings/wasm/src/account/types/mod.rs
  bindings/wasm/src/account/wasm_account/account.rs
  examples/Cargo.toml
  examples/README.md
  examples/account/encryption.rs
  identity-account-storage/Cargo.toml
  identity-account-storage/src/error.rs
  identity-account-storage/src/storage/memstore.rs
  identity-account-storage/src/storage/mod.rs
  identity-account-storage/src/storage/stronghold.rs
  identity-account-storage/src/storage/test_suite.rs
  identity-account-storage/src/storage/traits.rs
  identity-account-storage/src/stronghold/tests.rs
  identity-account-storage/src/types/encryption/cek_algorithm.rs
  identity-account-storage/src/types/encryption/encrypted_data.rs
  identity-account-storage/src/types/encryption/encryption_algorithm.rs
  identity-account-storage/src/types/encryption/mod.rs
  identity-account-storage/src/types/mod.rs
  identity-account/Cargo.toml
  identity-account/src/account/account.rs
  identity/Cargo.toml
Labels: Enhancement, Wasm, Breaking change, Rust

#871 Change `DIDUrl::join` to borrow self
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_did_url.rs
  identity-did/Cargo.toml
  identity-did/src/did/did_url.rs
Labels: Wasm, Breaking change, Rust

#870 Add `BaseEncoding` to replace `encode_b58`, `decode_b58`, `encode_multibase`, `decode_multibase`
  bindings/wasm/cypress/integration/resolveIdentity.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/node.js
  bindings/wasm/examples/src/resolve_did.js
  bindings/wasm/examples/src/tests/node/resolveIdentity.js
  bindings/wasm/examples/src/web.js
  bindings/wasm/package-lock.json
  identity-account-storage/Cargo.toml
  identity-account-storage/src/crypto/remote.rs
  identity-account-storage/src/stronghold/tests.rs
  identity-core/Cargo.toml
  identity-core/src/crypto/key/ed25519.rs
  identity-core/src/crypto/key/x25519.rs
  identity-core/src/crypto/proof/jcs_ed25519.rs
  identity-core/src/error.rs
  identity-core/src/utils/base_encoding.rs
  identity-did/src/verification/method_data.rs
  identity-iota-core/src/did/iota_did.rs
  identity-iota-core/src/document/iota_document.rs
Labels: Breaking change, Rust

#874 Add Rust publish workflow
  .github/actions/publish/publish-rust/action.yml
  .github/workflows/rust-publish-to-crates.yml
Labels: No changelog

#875 Fix crates.io workflow path
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#876 Fix crates.io workflow dry-run condition
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#877 Change `remove_service` to return boolean
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_document.rs
  examples/low-level-api/resolve_history.rs
  identity-account/src/updates/update.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota/src/chain/diff_chain.rs
Labels: Wasm, Breaking change, Rust

#861 Add `RevocationBitmap2022`, bump MSRV to 1.60
  .github/workflows/coverage.yml
  .github/workflows/scripts/coverage.sh
  README.md
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples-account/src/revoke_vc.ts
  bindings/wasm/src/account/wasm_account/account.rs
  bindings/wasm/src/account/wasm_account/mod.rs
  bindings/wasm/src/credential/credential_builder.rs
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/credential/types.rs
  bindings/wasm/src/credential/validation_options.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_did_url.rs
  bindings/wasm/src/did/wasm_document.rs
  bindings/wasm/src/did/wasm_service.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/revocation/bitmap.rs
  bindings/wasm/src/revocation/mod.rs
  bindings/wasm/tests/credentials.ts
  examples/account/revoke_vc.rs
  identity-account/Cargo.toml
  identity-account/src/account/account.rs
  identity-account/src/error.rs
  identity-core/src/error.rs
  identity-core/src/utils/base_encoding.rs
  identity-credential/Cargo.toml
  identity-credential/src/credential/builder.rs
  identity-credential/src/credential/credential.rs
  identity-credential/src/credential/mod.rs
  identity-credential/src/credential/revocation_bitmap_status.rs
  identity-credential/src/credential/status.rs
  identity-credential/src/error.rs
  identity-did/Cargo.toml
  identity-did/src/did/did_url.rs
  identity-did/src/error.rs
  identity-did/src/lib.rs
  identity-did/src/revocation/bitmap.rs
  identity-did/src/revocation/mod.rs
  identity-iota-core/Cargo.toml
  identity-iota-core/src/document/iota_document.rs
  identity-iota-core/src/error.rs
  identity-iota/Cargo.toml
  identity-iota/src/credential/credential_validator.rs
  identity-iota/src/credential/errors.rs
  identity-iota/src/credential/mod.rs
  identity-iota/src/credential/validation_options.rs
  identity/Cargo.toml
  identity/src/lib.rs
Labels: Wasm, Breaking change, Rust

#880 Fix Wasm version bump
  .github/actions/release/bump-versions/action.yml
Labels: No changelog

#873 Update the crate description for `identity-credential`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/credential_builder.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/credential/presentation_builder.rs
  identity-credential/Cargo.toml
  identity-credential/README.md
  identity-credential/src/credential/credential.rs
  identity-credential/src/lib.rs
  identity-credential/src/presentation/presentation.rs
Labels: Documentation

#884 Update Readme roadmap
  README.md
Labels: Documentation

#885 Fix title of DID on private Tangle
  documentation/docs/concepts/decentralized_identifiers/private_tangle.mdx
Labels: Documentation

#886 Fix title of DID on private Tangle (#885)
  documentation/docs/concepts/decentralized_identifiers/private_tangle.mdx
Labels: Documentation

#883 Update crate description for `identity-core`
  identity-core/Cargo.toml
  identity-core/README.md
  identity-core/src/common/ordered_set.rs
  identity-core/src/common/timestamp.rs
  identity-core/src/crypto/proof/proof.rs
  identity-core/src/crypto/proof/proof_options.rs
  identity-core/src/lib.rs
  identity-core/src/utils/base_encoding.rs
Labels: Documentation

#888 Update `identity-iota-core` description
  identity-iota-core/Cargo.toml
  identity-iota-core/README.md
  identity-iota-core/src/did/mod.rs
  identity-iota-core/src/diff/diff_iota_document.rs
  identity-iota-core/src/diff/diff_iota_document_metadata.rs
  identity-iota-core/src/diff/diff_message.rs
  identity-iota-core/src/document/iota_document.rs
  identity-iota-core/src/document/mod.rs
  identity-iota-core/src/lib.rs
  identity-iota-core/src/tangle/mod.rs
  identity-iota-core/src/tangle/network.rs
  identity/src/lib.rs
Labels: Documentation

#889 Update `identity-iota` description
  identity-iota/Cargo.toml
  identity-iota/README.md
  identity-iota/src/chain/diff_chain.rs
  identity-iota/src/chain/document_chain.rs
  identity-iota/src/chain/mod.rs
  identity-iota/src/credential/mod.rs
  identity-iota/src/credential/validation_options.rs
  identity-iota/src/document/mod.rs
  identity-iota/src/lib.rs
  identity-iota/src/tangle/explorer.rs
  identity-iota/src/tangle/mod.rs
  identity-iota/src/tangle/resolver.rs
  identity/src/lib.rs
Labels: Documentation

#891 Update root README.md, `identity` description
  README.md
  identity/Cargo.toml
  identity/README.md
  identity/src/lib.rs
Labels: Documentation

#893 Change Readme link to new project board
  README.md
Labels: Documentation

#892 Update `identity-did` description
  identity-did/Cargo.toml
  identity-did/README.md
  identity-did/src/did/did.rs
  identity-did/src/did/did_url.rs
  identity-did/src/did/error.rs
  identity-did/src/did/mod.rs
  identity-did/src/document/builder.rs
  identity-did/src/document/core_document.rs
  identity-did/src/error.rs
  identity-did/src/lib.rs
  identity-did/src/revocation/mod.rs
  identity-did/src/service/mod.rs
  identity-did/src/service/service.rs
  identity-did/src/service/service_endpoint.rs
  identity-did/src/utils/mod.rs
  identity-did/src/verifiable/mod.rs
  identity-did/src/verifiable/verifier_options.rs
  identity-did/src/verification/verification_method.rs
Labels: Documentation

#890 Update `identity_account_storage` description
  identity-account-storage/Cargo.toml
  identity-account-storage/README.md
  identity-account-storage/src/lib.rs
Labels: Documentation

#894 Update `identity-diff`, `identity-diff-derive` descriptions
  identity-diff/Cargo.toml
  identity-diff/README.md
  identity-diff/derive/Cargo.toml
  identity-diff/derive/README.md
  identity-diff/derive/src/lib.rs
  identity-diff/src/lib.rs
Labels: Documentation

#887 Update `identity-account` description
  identity-account/Cargo.toml
  identity-account/README.md
  identity-account/src/account/account.rs
  identity-account/src/account/builder.rs
  identity-account/src/account/publish_options.rs
  identity-account/src/error.rs
  identity-account/src/lib.rs
Labels: Documentation

#896 Fixed typo "verfiers" -> "verifiers" in `examples/account/revoke_vc.rs`
  examples/account/revoke_vc.rs
Labels: Documentation

#897 Add release blurb for 0.6.0
  .github/releases/v0.6.0.md
  .github/releases/wasm-v0.6.0.md
Labels: Documentation

#898 Enable Rust publish
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#899 Fix Rust crates publish
  .github/workflows/rust-publish-to-crates.yml
Labels: No changelog

#900 Attempt to fix CI, log Rust publish inputs
  .github/actions/publish/publish-rust/action.yml
  .github/workflows/rust-publish-to-crates.yml
Labels: No changelog

#901 Fix Rust publish boolean parameter
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#902 Force Rust publish
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#903 Bump examples version
  .github/actions/publish/publish-rust/action.yml
  examples/Cargo.toml
Labels: No changelog

#906 Bump examples version in GitHub Actions
  .github/actions/release/bump-versions/action.yml
Labels: No changelog

#910 Update package name
  documentation/package.json
  documentation/yarn.lock
Labels: Documentation

#879 Add `RevocationBitmap2022` specification
  bindings/wasm/examples-account/src/revoke_vc.ts
  documentation/docs/concepts/verifiable_credentials/create.mdx
  documentation/docs/concepts/verifiable_credentials/revocation.mdx
  documentation/docs/concepts/verifiable_credentials/revoke.mdx
  documentation/docs/specs/overview.md
  documentation/docs/specs/revocation_bitmap_2022.md
  documentation/sidebars.js
  examples/account/revoke_vc.rs
Labels: Documentation, Patch

#913 Add version path
  documentation/docusaurus.config.js
Labels: Documentation

#915 Remove localhost from link (#914)
  documentation/docs/introduction.md
Labels: Documentation

#917 Avoid the include! macro
  identity_core/src/crypto/proof/jcs_ed25519.rs
  identity_core/tests/fixtures/jcs_ed25519/test_vector_1.json
  identity_core/tests/fixtures/jcs_ed25519/test_vector_2.json
Labels: Chore, No changelog

#916 Fix cargo check with `--no-default-features`
  identity_account/Cargo.toml
  identity_account/src/account/account.rs
  identity_account_storage/src/storage/memstore.rs
  identity_account_storage/src/storage/traits.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_iota_client/Cargo.toml
  identity_iota_client/src/credential/credential_validator.rs
  identity_iota_core/src/document/iota_document.rs
Labels: Breaking change, No changelog, Rust

#322 Implement the Identity Agent
  Cargo.toml
  identity_agent/Cargo.toml
  identity_agent/README.md
  identity_agent/benches/agent.rs
  identity_agent/benches/didcomm.rs
  identity_agent/src/agent/agent.rs
  identity_agent/src/agent/agent_builder.rs
  identity_agent/src/agent/agent_state.rs
  identity_agent/src/agent/config.rs
  identity_agent/src/agent/endpoint.rs
  identity_agent/src/agent/errors.rs
  identity_agent/src/agent/handler.rs
  identity_agent/src/agent/mod.rs
  identity_agent/src/agent/request.rs
  identity_agent/src/agent/request_context.rs
  identity_agent/src/didcomm/agent.rs
  identity_agent/src/didcomm/agent_builder.rs
  identity_agent/src/didcomm/dcpm.rs
  identity_agent/src/didcomm/handler.rs
  identity_agent/src/didcomm/mod.rs
  identity_agent/src/didcomm/request.rs
  identity_agent/src/didcomm/thread_id.rs
  identity_agent/src/lib.rs
  identity_agent/src/p2p/behaviour.rs
  identity_agent/src/p2p/event_loop.rs
  identity_agent/src/p2p/message.rs
  identity_agent/src/p2p/mod.rs
  identity_agent/src/p2p/net_commander.rs
  identity_agent/src/tests/didcomm.rs
  identity_agent/src/tests/handler.rs
  identity_agent/src/tests/mod.rs
  identity_agent/src/tests/presentation.rs
  identity_agent/src/tests/remote_account/error.rs
  identity_agent/src/tests/remote_account/handler.rs
  identity_agent/src/tests/remote_account/mod.rs
  identity_agent/src/tests/remote_account/requests.rs
  identity_agent/src/tests/remote_account/tests.rs
  identity_core/src/common/one_or_many.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
Labels: Added, Rust

#924 Fix broken links
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/overview.md
Labels: Documentation

#926 Fix broken links (#924)
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/overview.md
Labels: Documentation

#927 Use latest version of tutorial
  documentation/docs/tutorials/overview.md
  documentation/docs/tutorials/validate_university_degree.mdx
  documentation/static/img/identity_tutorial_chart.png
  documentation/static/img/sequence-diagram.png
Labels: Documentation

#929 Use compressed sequence diagram
  documentation/static/img/sequence-diagram.png
Labels: Documentation

#930 Update stronghold to 0.6.4
  identity_account_storage/Cargo.toml
  identity_account_storage/src/storage/stronghold.rs
Labels: Rust, Patch
