Repository iotaledger/identity, pull requests merged in 2023-05, with the labels that each got.

#1161 Replace `iota-client` with `iota-sdk`
  README.md
  bindings/wasm/Cargo.toml
  bindings/wasm/build/web.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/iota/identity_client.rs
  bindings/wasm/src/iota/identity_client_ext.rs
  bindings/wasm/src/iota/iota_did.rs
  bindings/wasm/src/iota/iota_document.rs
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  examples/0_basic/0_create_did.rs
  examples/0_basic/1_update_did.rs
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/0_basic/4_delete_did.rs
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/1_advanced/0_did_controls_did.rs
  examples/1_advanced/1_did_issues_nft.rs
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
  examples/1_advanced/4_key_exchange.rs
  examples/1_advanced/5_alias_output_history.rs
  examples/1_advanced/6_custom_resolution.rs
  examples/1_advanced/7_domain_linkage.rs
  examples/Cargo.toml
  examples/utils/utils.rs
  identity_core/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota/README.md
  identity_iota_client_legacy/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/error.rs
  identity_iota_core/src/lib.rs
  identity_iota_core_legacy/Cargo.toml
  identity_jose/Cargo.toml
  identity_resolver/Cargo.toml
  identity_storage/Cargo.toml
Labels: Chore, Rust, Patch

#1162 Fix workflow outputs
  .github/workflows/shared-release.yml
Labels: No changelog

#1158 Setup fresh NAPI install
  .github/actions/publish/publish-stronghold-nodejs/action.yml
  .github/actions/publish/publish-wasm/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  .github/workflows/wasm-publish-to-npm.yml
  bindings/stronghold-nodejs/.gitignore
  bindings/stronghold-nodejs/.license_template
  bindings/stronghold-nodejs/.npmignore
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/Cargo.toml
  bindings/stronghold-nodejs/README.md
  bindings/stronghold-nodejs/__test__/index.spec.mjs
  bindings/stronghold-nodejs/__test__/readme.spec.mjs
  bindings/stronghold-nodejs/examples/src/stronghold.ts
  bindings/stronghold-nodejs/examples/src/tests/config.ts
  bindings/stronghold-nodejs/examples/src/tests/create_did.ts
  bindings/stronghold-nodejs/examples/src/tests/encryption.ts
  bindings/stronghold-nodejs/examples/src/tests/lazy.ts
  bindings/stronghold-nodejs/examples/src/tests/manipulate_did.ts
  bindings/stronghold-nodejs/examples/src/tests/multiple_identities.ts
  bindings/stronghold-nodejs/examples/src/tests/signing.ts
  bindings/stronghold-nodejs/examples/src/tests/storage_test_suite.ts
  bindings/stronghold-nodejs/examples/src/tests/unchecked.ts
  bindings/stronghold-nodejs/js/stronghold.ts
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
  bindings/stronghold-nodejs/rollup.config.mjs
  bindings/stronghold-nodejs/rsutfmt.toml
  bindings/stronghold-nodejs/src/error.rs
  bindings/stronghold-nodejs/src/lib.rs
  bindings/stronghold-nodejs/src/stronghold.rs
  bindings/stronghold-nodejs/src/types/derive.rs
  bindings/stronghold-nodejs/src/types/did_location_tuple.rs
  bindings/stronghold-nodejs/src/types/did_type.rs
  bindings/stronghold-nodejs/src/types/key_type.rs
  bindings/stronghold-nodejs/src/types/mod.rs
  bindings/stronghold-nodejs/tests/txm_readme.js
Labels: No changelog

#1163 Fix workflow paths
  .github/workflows/build-and-test.yml
  .github/workflows/wasm-publish-to-npm.yml
Labels: No changelog

#1165 Fix npm dry-run condition
  .github/actions/publish/publish-wasm/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  bindings/stronghold-nodejs/package.json
Labels: No changelog

#1168 Remove `identity_agent` & `identity_comm`
  Cargo.toml
  identity_agent/Cargo.toml
  identity_agent/README.md
  identity_agent/benches/agent.rs
  identity_agent/benches/didcomm.rs
  identity_agent/src/agent/agent.rs
  identity_agent/src/agent/agent_builder.rs
  identity_agent/src/agent/agent_state.rs
  identity_agent/src/agent/config.rs
  identity_agent/src/agent/endpoint.rs
  identity_agent/src/agent/errors.rs
  identity_agent/src/agent/handler.rs
  identity_agent/src/agent/mod.rs
  identity_agent/src/agent/request.rs
  identity_agent/src/agent/request_context.rs
  identity_agent/src/didcomm/agent.rs
  identity_agent/src/didcomm/agent_builder.rs
  identity_agent/src/didcomm/dcpm.rs
  identity_agent/src/didcomm/handler.rs
  identity_agent/src/didcomm/mod.rs
  identity_agent/src/didcomm/request.rs
  identity_agent/src/didcomm/thread_id.rs
  identity_agent/src/lib.rs
  identity_agent/src/p2p/behaviour.rs
  identity_agent/src/p2p/event_loop.rs
  identity_agent/src/p2p/message.rs
  identity_agent/src/p2p/mod.rs
  identity_agent/src/p2p/net_commander.rs
  identity_agent/src/tests/didcomm.rs
  identity_agent/src/tests/handler.rs
  identity_agent/src/tests/mod.rs
  identity_agent/src/tests/presentation.rs
  identity_agent/src/tests/remote_account/error.rs
  identity_agent/src/tests/remote_account/handler.rs
  identity_agent/src/tests/remote_account/mod.rs
  identity_agent/src/tests/remote_account/requests.rs
  identity_agent/src/tests/remote_account/tests.rs
  identity_comm/Cargo.toml
  identity_comm/README.md
  identity_comm/src/envelope/encrypted.rs
  identity_comm/src/envelope/mod.rs
  identity_comm/src/envelope/plaintext.rs
  identity_comm/src/envelope/signed.rs
  identity_comm/src/envelope/traits.rs
  identity_comm/src/error.rs
  identity_comm/src/lib.rs
  identity_comm/src/message/mod.rs
  identity_comm/src/message/traits.rs
  identity_comm/src/types.rs
Labels: Breaking change, Rust

#1164 Test `JWTCredentialValidator`
  identity_credential/src/revocation/document_ext.rs
  identity_storage/Cargo.toml
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/test_utils.rs
Labels: Chore, No changelog, Rust

#1173 Polish JWK thumbprint and document extension API
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/jose/jws_header.rs
  bindings/wasm/src/verification/custom_verification.rs
  bindings/wasm/src/verification/wasm_verification_method.rs
  bindings/wasm/tests/storage.ts
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_document/src/document/core_document.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/error.rs
  identity_jose/examples/jws_encoding_decoding.rs
  identity_jose/src/jwk/key.rs
  identity_jose/src/jws/custom_verification/error.rs
  identity_jose/src/jws/custom_verification/jws_verifier.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/header.rs
  identity_jose/src/jwt/header_set.rs
  identity_jose/src/tests/rfc7515.rs
  identity_jose/src/tests/rfc7638.rs
  identity_jose/src/tests/rfc7797.rs
  identity_jose/src/tests/rfc8037.rs
  identity_jose/src/tests/roundtrip.rs
  identity_storage/src/key_id_storage/method_digest.rs
  identity_storage/src/storage/error.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/mod.rs
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/test_utils.rs
  identity_verification/src/verification_method/method.rs
Labels: Enhancement, Wasm, Added, Rust
