Repository iotaledger/identity, pull requests merged in 2023-08, with the labels that each got.

#1202 Upgrade `client-wasm` to `sdk-wasm`
  bindings/wasm/README.md
  bindings/wasm/cypress/support/setup.js
  bindings/wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/examples/src/0_basic/5_create_vc.ts
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/examples/src/1_advanced/0_did_controls_did.ts
  bindings/wasm/examples/src/1_advanced/1_did_issues_nft.ts
  bindings/wasm/examples/src/1_advanced/2_nft_owns_did.ts
  bindings/wasm/examples/src/1_advanced/3_did_issues_tokens.ts
  bindings/wasm/examples/src/1_advanced/4_custom_resolution.ts
  bindings/wasm/examples/src/1_advanced/5_domain_linkage.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/util.ts
  bindings/wasm/examples/tsconfig.web.json
  bindings/wasm/lib/iota_identity_client.ts
  bindings/wasm/lib/jwk_storage.ts
  bindings/wasm/lib/tsconfig.json
  bindings/wasm/lib/tsconfig.web.json
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/iota/identity_client.rs
  bindings/wasm/src/iota/identity_client_ext.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/tsconfig.json
Labels: Wasm, Breaking change

#1174 Update identity 0.6 to Stronghold 2.0
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/src/types/key_type.rs
  bindings/wasm/build/lints.js
  bindings/wasm/docs/api-reference.md
  identity_account_storage/Cargo.toml
  identity_account_storage/src/storage/stronghold.rs
  identity_account_storage/src/stronghold/error.rs
  identity_account_storage/src/stronghold/tests.rs
  identity_account_storage/src/stronghold/wrapper.rs
  identity_iota/src/lib.rs
Labels: Wasm, Chore, Rust, Patch

#1208 Bump `iota-sdk` and other dependencies
  Cargo.toml
  README.md
  bindings/wasm/Cargo.toml
  bindings/wasm/lib/iota_identity_client.ts
  bindings/wasm/src/iota/identity_client.rs
  bindings/wasm/src/iota/identity_client_ext.rs
  bindings/wasm/src/iota/iota_document.rs
  examples/0_basic/0_create_did.rs
  examples/0_basic/1_update_did.rs
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/0_basic/4_delete_did.rs
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/1_advanced/0_did_controls_did.rs
  examples/1_advanced/1_did_issues_nft.rs
  examples/1_advanced/2_nft_owns_did.rs
  examples/1_advanced/3_did_issues_tokens.rs
  examples/1_advanced/4_alias_output_history.rs
  examples/1_advanced/5_custom_resolution.rs
  examples/1_advanced/6_domain_linkage.rs
  examples/Cargo.toml
  examples/utils/utils.rs
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_credential/src/credential/credential.rs
  identity_credential/src/domain_linkage/domain_linkage_configuration.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_did/Cargo.toml
  identity_document/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota/README.md
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/lib.rs
  identity_iota_core/src/network/network_name.rs
  identity_jose/Cargo.toml
  identity_jose/examples/jws_encoding_decoding.rs
  identity_jose/src/jws/custom_verification/jws_verifier.rs
  identity_jose/src/tests/ed25519.rs
  identity_resolver/Cargo.toml
  identity_storage/Cargo.toml
  identity_storage/src/key_storage/memstore.rs
Labels: Breaking change, Rust

#1215 Respect passed branch for Wasm build
  .github/workflows/shared-build-wasm.yml
  .github/workflows/wasm-publish-to-npm.yml
Labels: No changelog

#1220 Fix broken links in Wasm Api-reference
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/storage/key_id_storage.rs
  bindings/wasm/src/storage/wasm_storage.rs
Labels: Documentation

#1221 Fix broken links
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/storage/jwk_gen_output.rs
Labels: Documentation, No changelog

#1216 Hotfix/v0.6.3
  .github/releases/v0.6.3.md
  CHANGELOG.md
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/Cargo.toml
  bindings/wasm/Cargo.toml
  identity_account/Cargo.toml
  identity_account_storage/Cargo.toml
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_did/Cargo.toml
  identity_diff/Cargo.toml
  identity_diff/derive/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_client/Cargo.toml
  identity_iota_core/Cargo.toml
Labels: No changelog

#1222 Add lints for all crates
  identity_core/src/lib.rs
  identity_did/src/lib.rs
  identity_document/src/lib.rs
  identity_iota/src/lib.rs
  identity_jose/src/error.rs
  identity_jose/src/jose/mod.rs
  identity_jose/src/jose/traits.rs
  identity_jose/src/jwk/curve/ec.rs
  identity_jose/src/jwk/curve/ecdh.rs
  identity_jose/src/jwk/curve/ecx.rs
  identity_jose/src/jwk/curve/ed.rs
  identity_jose/src/jwk/curve/mod.rs
  identity_jose/src/jwk/key_params.rs
  identity_jose/src/jwk/key_set.rs
  identity_jose/src/jws/algorithm.rs
  identity_jose/src/jws/charset.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/encoding/encoder.rs
  identity_jose/src/jws/recipient.rs
  identity_jose/src/jwt/header_set.rs
  identity_jose/src/jwt/mod.rs
  identity_jose/src/jwu/serde.rs
  identity_jose/src/lib.rs
  identity_storage/src/key_storage/jwk_storage.rs
  identity_verification/src/error.rs
  identity_verification/src/jose/mod.rs
  identity_verification/src/lib.rs
  identity_verification/src/verification_method/material.rs
  identity_verification/src/verification_method/method_ref.rs
  identity_verification/src/verification_method/method_relationship.rs
  identity_verification/src/verification_method/method_scope.rs
  identity_verification/src/verification_method/method_type.rs
Labels: Breaking change, Rust

#1223 Bring `JwkDocumentExt` names in line with Wasm
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/0_basic/8_stronghold.rs
  examples/1_advanced/6_domain_linkage.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/presentation_validation.rs
Labels: Wasm, Breaking change, Rust

#1227 Mark error enums as non-exhaustive
  bindings/wasm/src/iota/iota_metadata_encoding.rs
  identity_core/src/common/one_or_set.rs
  identity_core/src/convert/base_encoding.rs
  identity_credential/src/domain_linkage/error.rs
  identity_credential/src/error.rs
  identity_credential/src/revocation/error.rs
  identity_credential/src/validator/vc_jwt_validation/error.rs
  identity_document/src/error.rs
  identity_iota_core/src/state_metadata/encoding.rs
  identity_iota_core/src/state_metadata/version.rs
  identity_jose/src/error.rs
  identity_jose/src/tests/es256.rs
  identity_storage/src/key_id_storage/method_digest.rs
  identity_storage/src/key_storage/ed25519.rs
  identity_verification/src/error.rs
Labels: Breaking change, Rust
