Repository iotaledger/identity, pull requests merged in 2023-07, with the labels that each got.

#1196 Polish `identity_core`
  identity_core/Cargo.toml
  identity_core/README.md
  identity_core/src/common/fragment.rs
  identity_core/src/common/mod.rs
  identity_core/src/common/timestamp.rs
  identity_core/src/common/url.rs
  identity_core/src/convert/base_encoding.rs
  identity_core/src/convert/json.rs
  identity_core/src/convert/mod.rs
  identity_core/src/error.rs
  identity_core/src/lib.rs
  identity_core/src/utils/mod.rs
  identity_core/tests/fixtures/jcs_ed25519/test_vector_1.json
  identity_core/tests/fixtures/jcs_ed25519/test_vector_2.json
  identity_credential/src/credential/credential.rs
  identity_credential/src/presentation/jwt_presentation.rs
  identity_credential/src/revocation/bitmap.rs
  identity_credential/src/validator/test_utils.rs
  identity_document/src/document/core_document.rs
  identity_iota/src/lib.rs
  identity_iota_core/src/document/iota_document.rs
  identity_verification/src/verification_method/material.rs
  identity_verification/src/verification_method/mod.rs
  identity_verification/src/verification_method/traits.rs
Labels: Breaking change, Rust

#1197 Polish `identity_did` & `identity_verification`
  identity_did/src/error.rs
  identity_verification/src/error.rs
  identity_verification/src/verification_method/builder.rs
  identity_verification/src/verification_method/material.rs
  identity_verification/src/verification_method/method.rs
  identity_verification/src/verification_method/method_type.rs
Labels: Breaking change, Rust

#1198 Polish `identity_document`
  identity_document/src/document/core_document.rs
  identity_document/src/error.rs
  identity_document/src/service/service.rs
  identity_document/src/service/service_endpoint.rs
  identity_document/src/utils/did_url_query.rs
  identity_document/src/verifiable/properties.rs
  identity_document/src/verifiable/verifier_options.rs
Labels: Breaking change, Rust

#1186 Make JWT presentations generic
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/mod.rs
  bindings/wasm/src/credential/jwt_credential_validation/options.rs
  bindings/wasm/src/credential/jwt_credential_validation/unknown_credential.rs
  bindings/wasm/src/credential/jwt_presentation/jwt_presentation.rs
  bindings/wasm/src/credential/jwt_presentation/jwt_presentation_builder.rs
  bindings/wasm/src/credential/jwt_presentation_validation/decoded_jwt_presentation.rs
  bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
  bindings/wasm/src/credential/jwt_presentation_validation/options.rs
  bindings/wasm/src/credential/types.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/storage.ts
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  identity_core/src/common/single_struct_error.rs
  identity_credential/src/credential/jwt_serialization.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/presentation/jwt_presentation.rs
  identity_credential/src/presentation/jwt_presentation_builder.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/validator/options.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validation_options.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_credential/src/validator/vp_jwt_validation/decoded_jwt_presentation.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validation_options.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validator.rs
  identity_jose/src/jws/decoder.rs
  identity_resolver/src/resolution/tests/resolution.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/tests/presentation_validation.rs
Labels: Added, Rust, Patch

#1199 Use `Record` type for unknown credentials in Wasm
  bindings/wasm/src/common/types.rs
  bindings/wasm/src/credential/jwt_credential_validation/unknown_credential.rs
  bindings/wasm/src/credential/jwt_presentation/jwt_presentation_builder.rs
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/storage.ts
Labels: Wasm, No changelog

#1200 Rename `JwtPresentation` to `Presentation`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/src/credential/jwt_presentation/mod.rs
  bindings/wasm/src/credential/jwt_presentation/presentation.rs
  bindings/wasm/src/credential/jwt_presentation/presentation_builder.rs
  bindings/wasm/src/credential/jwt_presentation_validation/decoded_jwt_presentation.rs
  bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/storage.ts
  examples/0_basic/6_create_vp.rs
  identity_credential/src/credential/credential.rs
  identity_credential/src/credential/policy.rs
  identity_credential/src/error.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/presentation/mod.rs
  identity_credential/src/presentation/presentation.rs
  identity_credential/src/presentation/presentation_builder.rs
  identity_credential/src/validator/vc_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/decoded_jwt_presentation.rs
  identity_credential/src/validator/vp_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validation_options.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validator.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/tests/presentation_validation.rs
Labels: Wasm, Chore, Breaking change, Rust

#1201 Polish `identity_jose`
  identity_core/src/common/one_or_many.rs
  identity_core/src/convert/base_encoding.rs
  identity_jose/Cargo.toml
  identity_jose/examples/jws_encoding_decoding.rs
  identity_jose/src/error.rs
  identity_jose/src/jose/cty.rs
  identity_jose/src/jose/mod.rs
  identity_jose/src/jose/typ.rs
  identity_jose/src/jwk/key.rs
  identity_jose/src/jwk/key_operation.rs
  identity_jose/src/jwk/key_params.rs
  identity_jose/src/jwk/key_set.rs
  identity_jose/src/jwk/mod.rs
  identity_jose/src/jws/algorithm.rs
  identity_jose/src/jws/charset.rs
  identity_jose/src/jws/custom_verification/jws_verifier.rs
  identity_jose/src/jws/custom_verification/mod.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/encoding/encoder.rs
  identity_jose/src/jws/encoding/mod.rs
  identity_jose/src/jws/encoding/utils.rs
  identity_jose/src/jws/header.rs
  identity_jose/src/jws/mod.rs
  identity_jose/src/jws/recipient.rs
  identity_jose/src/jwt/claims.rs
  identity_jose/src/jwt/header.rs
  identity_jose/src/jwt/header_set.rs
  identity_jose/src/jwt/mod.rs
  identity_jose/src/jwt/profile/core.rs
  identity_jose/src/jwt/profile/mod.rs
  identity_jose/src/jwu/base64.rs
Labels: Added, Rust

#1203 Polish `identity_iota_core`
  bindings/wasm/lib/iota_identity_client.ts
  bindings/wasm/src/iota/iota_did.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/iota/iota_document_metadata.rs
  bindings/wasm/tests/iota.ts
  identity_document/src/document/core_document.rs
  identity_iota_core/Cargo.toml
  identity_iota_core/README.md
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/document/iota_document_metadata.rs
  identity_iota_core/src/error.rs
  identity_iota_core/src/lib.rs
  identity_iota_core/src/network/network_name.rs
  identity_iota_core/src/state_metadata/document.rs
  identity_iota_core/src/state_metadata/encoding.rs
  identity_iota_core/src/state_metadata/version.rs
Labels: Wasm, Breaking change, Rust

#1205 Polish `identity_credential`
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/src/revocation/bitmap.rs
  examples/0_basic/7_revoke_vc.rs
  identity_credential/src/credential/credential.rs
  identity_credential/src/credential/evidence.rs
  identity_credential/src/credential/issuer.rs
  identity_credential/src/credential/jwt.rs
  identity_credential/src/credential/mod.rs
  identity_credential/src/credential/policy.rs
  identity_credential/src/credential/refresh.rs
  identity_credential/src/credential/schema.rs
  identity_credential/src/credential/status.rs
  identity_credential/src/credential/subject.rs
  identity_credential/src/domain_linkage/domain_linkage_configuration.rs
  identity_credential/src/domain_linkage/error.rs
  identity_credential/src/domain_linkage/mod.rs
  identity_credential/src/lib.rs
  identity_credential/src/presentation/jwt_presentation_options.rs
  identity_credential/src/presentation/mod.rs
  identity_credential/src/presentation/presentation.rs
  identity_credential/src/revocation/bitmap.rs
  identity_credential/src/revocation/document_ext.rs
  identity_credential/src/revocation/mod.rs
  identity_credential/src/validator/mod.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validation_options.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_credential/src/validator/vc_jwt_validation/decoded_jwt_credential.rs
  identity_credential/src/validator/vc_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validation_options.rs
  identity_storage/src/storage/tests/credential_validation.rs
Labels: Wasm, Breaking change, Rust

#1207 Rename `CredentialValidator` to `JwtCredentialValidator`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/1_advanced/5_domain_linkage.ts
  bindings/wasm/src/credential/domain_linkage_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/options.rs
  bindings/wasm/src/error.rs
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/1_advanced/6_domain_linkage.rs
  identity_credential/README.md
  identity_credential/src/domain_linkage/domain_linkage_configuration.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validation_options.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_credential/src/validator/vc_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/error.rs
  identity_credential/src/validator/vp_jwt_validation/jwt_presentation_validator.rs
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/presentation_validation.rs
Labels: Chore, No changelog, Rust

#1209 Improve `Proof`
  README.md
  bindings/wasm/package-lock.json
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/credential_builder.rs
  bindings/wasm/src/credential/jwt_presentation_validation/decoded_jwt_presentation.rs
  bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/presentation/mod.rs
  bindings/wasm/src/credential/presentation/presentation.rs
  bindings/wasm/src/credential/presentation/presentation_builder.rs
  bindings/wasm/src/credential/proof.rs
  bindings/wasm/tests/credentials.ts
  identity_credential/src/credential/builder.rs
  identity_credential/src/credential/credential.rs
  identity_credential/src/credential/jwt_serialization.rs
  identity_credential/src/credential/mod.rs
  identity_credential/src/credential/proof.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/presentation/presentation.rs
Labels: Enhancement, Wasm, Added, Rust
