Repository iotaledger/identity, pull requests merged in 2023-02, with the labels that each got.

#1111 Remove outdated lint
  bindings/wasm/build/lints.js
Labels: Chore, No changelog

#1112 Refactor `MethodType` to make it extensible
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  identity_credential/src/presentation/builder.rs
  identity_document/src/diff/diff_document.rs
  identity_document/src/document/builder.rs
  identity_document/src/document/core_document.rs
  identity_document/src/verifiable/document_signer.rs
  identity_document/src/verifiable/tests.rs
  identity_iota_client_legacy/src/chain/document_chain.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core_legacy/src/document/iota_document.rs
  identity_verification/src/verification_method/builder.rs
  identity_verification/src/verification_method/diff/diff_method.rs
  identity_verification/src/verification_method/diff/method_type.rs
  identity_verification/src/verification_method/method.rs
  identity_verification/src/verification_method/method_type.rs
Labels: Wasm, Breaking change, Rust

#1105 Add JSON Object Signing and Encryption capabilities
  Cargo.toml
  identity_jose/Cargo.toml
  identity_jose/src/error.rs
  identity_jose/src/jose/cty.rs
  identity_jose/src/jose/mod.rs
  identity_jose/src/jose/traits.rs
  identity_jose/src/jose/typ.rs
  identity_jose/src/jwk/curve/ec.rs
  identity_jose/src/jwk/curve/ecdh.rs
  identity_jose/src/jwk/curve/ecx.rs
  identity_jose/src/jwk/curve/ed.rs
  identity_jose/src/jwk/curve/mod.rs
  identity_jose/src/jwk/key.rs
  identity_jose/src/jwk/key_operation.rs
  identity_jose/src/jwk/key_params.rs
  identity_jose/src/jwk/key_set.rs
  identity_jose/src/jwk/key_type.rs
  identity_jose/src/jwk/key_use.rs
  identity_jose/src/jwk/mod.rs
  identity_jose/src/jws/algorithm.rs
  identity_jose/src/jws/charset.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/encoder.rs
  identity_jose/src/jws/format.rs
  identity_jose/src/jws/header.rs
  identity_jose/src/jws/mod.rs
  identity_jose/src/jws/recipient.rs
  identity_jose/src/jwt/claims.rs
  identity_jose/src/jwt/header.rs
  identity_jose/src/jwt/header_set.rs
  identity_jose/src/jwt/mod.rs
  identity_jose/src/jwt/profile/core.rs
  identity_jose/src/jwt/profile/mod.rs
  identity_jose/src/jwu/base64.rs
  identity_jose/src/jwu/mod.rs
  identity_jose/src/jwu/serde.rs
  identity_jose/src/lib.rs
  identity_jose/src/tests/ed25519.rs
  identity_jose/src/tests/es256.rs
  identity_jose/src/tests/fixtures/rfc7515.rs
  identity_jose/src/tests/fixtures/rfc7517.rs
  identity_jose/src/tests/fixtures/rfc7638.rs
  identity_jose/src/tests/fixtures/rfc7797.rs
  identity_jose/src/tests/fixtures/rfc8037_ed25519.rs
  identity_jose/src/tests/hs256.rs
  identity_jose/src/tests/mod.rs
  identity_jose/src/tests/rfc7515.rs
  identity_jose/src/tests/rfc7517.rs
  identity_jose/src/tests/rfc7638.rs
  identity_jose/src/tests/rfc7797.rs
  identity_jose/src/tests/rfc8037.rs
  identity_jose/src/tests/roundtrip.rs
Labels: Added, Rust

#1114 Hoist `serde_json` into workspace `Cargo.toml`
  Cargo.toml
  identity_agent/Cargo.toml
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_did/Cargo.toml
  identity_diff/Cargo.toml
  identity_document/Cargo.toml
  identity_verification/Cargo.toml
Labels: Wasm, No changelog, Rust

#1108 Replace deprecated workflow functions
  .github/actions/publish/publish-rust/action.yml
  .github/actions/release/bump-versions/action.yml
  .github/actions/rust/rust-setup/action.yml
  .github/actions/rust/sccache/setup-sccache/action.yml
  .github/actions/rust/sccache/stop-sccache/action.yml
  .github/workflows/audit.yml
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/format.yml
  .github/workflows/rust-automatic-release-and-publish.yml
  .github/workflows/rust-publish-to-crates.yml
  .github/workflows/shared-build-and-test-stronghold-nodejs.yml
  .github/workflows/shared-build-wasm.yml
  .github/workflows/shared-create-dev-release-pr.yml
  .github/workflows/shared-create-hotfix-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
  .github/workflows/shared-release.yml
  .github/workflows/test-docs-build.yml
  .github/workflows/wasm-automatic-release-and-publish.yml
Labels: No changelog

#1119 Chore/v0.5 fix doc links
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/introduction.md
  documentation/docs/libraries/overview.md
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/overview.md
  documentation/docs/tutorials/overview.md
Labels: No changelog

#1118 Add file extension to links
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/introduction.md
  documentation/docs/libraries/overview.md
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/overview.md
  documentation/docs/tutorials/overview.md
Labels: No changelog

#1117 Adapt changes of `iota-client`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/error.rs
  examples/1_advanced/5_alias_output_history.rs
  identity_iota_core/src/client/iota_client.rs
Labels: Wasm, Dependencies, No changelog, Rust

#1121 Update `iota-types`
  bindings/wasm/Cargo.toml
  identity_diff/README.md
  identity_iota_core/Cargo.toml
Labels: Documentation, Rust

#1123 Add README to `identity_jose`
  identity_jose/Cargo.toml
  identity_jose/README.md
Labels: No changelog, Rust

#1124 Remove agent from workspace for 0.7.0-alpha.5 release
  Cargo.toml
Labels: No changelog, Rust

#1125 Reduce number of keywords in `identity_jose`
  identity_jose/Cargo.toml
Labels: No changelog, Rust

#1120 Introduce `IToCoreDocument` and document locks in the bindings.
  bindings/wasm/Cargo.toml
  bindings/wasm/README.md
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/1_advanced/4_key_exchange.ts
  bindings/wasm/examples/src/util.ts
  bindings/wasm/lib/append_functions.ts
  bindings/wasm/lib/index.ts
  bindings/wasm/src/common/imported_document_lock.rs
  bindings/wasm/src/common/mod.rs
  bindings/wasm/src/credential/credential_validator.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/presentation_validator.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_core_did.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/iota/identity_client_ext.rs
  bindings/wasm/src/iota/iota_did.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/iota/mod.rs
  bindings/wasm/src/resolver/constructor_input.rs
  bindings/wasm/src/resolver/mod.rs
  bindings/wasm/src/resolver/supported_document_types.rs
  bindings/wasm/src/resolver/type_definitions.rs
  bindings/wasm/src/resolver/wasm_resolver.rs
  bindings/wasm/tests/core.ts
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/iota.ts
  bindings/wasm/tests/resolver.ts
  bindings/wasm/tests/wasm.rs
  identity_resolver/src/resolution/commands.rs
  identity_resolver/src/resolution/resolver.rs
Labels: Wasm, Added, Rust

#1115 Add Wasm Bindings for Domain Linkage
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/1_advanced/6_domain_linkage.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/6_domain_linkage.ts
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/domain_linkage_configuration.rs
  bindings/wasm/src/credential/domain_linkage_credential_builder.rs
  bindings/wasm/src/credential/domain_linkage_validator.rs
  bindings/wasm/src/credential/linked_domain_service.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/presentation.rs
  bindings/wasm/src/credential/types.rs
  bindings/wasm/src/error.rs
  examples/1_advanced/7_domain_linkage.rs
  identity_credential/Cargo.toml
  identity_credential/src/credential/linked_domain_service.rs
  identity_credential/src/validator/domain_linkage_validator.rs
  identity_credential/src/validator/errors.rs
  identity_iota/Cargo.toml
Labels: Enhancement, Wasm, Added

#1127 Adopt toolchain file and replace toolchain action with manual commands
  .github/actions/rust/rust-setup/action.yml
  .github/workflows/shared-build-wasm.yml
  bindings/wasm/rust-toolchain.toml
  rust-toolchain.toml
Labels: No changelog

#1129 Improve robustness of the Wasm bindings
  .github/workflows/shared-build-wasm.yml
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/lib/append_functions.ts
  bindings/wasm/package.json
  bindings/wasm/src/did/wasm_core_did.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/tests/core.ts
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/iota.ts
  bindings/wasm/tests/resolver.ts
  bindings/wasm/tests/wasm.rs
Labels: Bug, Wasm, Chore, No changelog

#1116 Implement `JwkStorage`
  Cargo.toml
  bindings/wasm/Cargo.toml
  bindings/wasm/build/replace_paths.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/lib/index.ts
  bindings/wasm/lib/jose/ec_curve.ts
  bindings/wasm/lib/jose/ed_curve.ts
  bindings/wasm/lib/jose/index.ts
  bindings/wasm/lib/jose/jwk_operation.ts
  bindings/wasm/lib/jose/jwk_type.ts
  bindings/wasm/lib/jose/jwk_use.ts
  bindings/wasm/lib/jose/jws_algorithm.ts
  bindings/wasm/lib/tsconfig.json
  bindings/wasm/lib/tsconfig.web.json
  bindings/wasm/src/common/types.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/jose/jwk.rs
  bindings/wasm/src/jose/mod.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/storage/jwk_gen_output.rs
  bindings/wasm/src/storage/jwk_storage.rs
  bindings/wasm/src/storage/mod.rs
  bindings/wasm/tests/jose.ts
  bindings/wasm/tests/storage.ts
  identity_agent/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_jose/src/error.rs
  identity_jose/src/jwk/key.rs
  identity_jose/src/jwk/key_params.rs
  identity_jose/src/jwk/key_type.rs
  identity_jose/src/jws/algorithm.rs
  identity_storage/Cargo.toml
  identity_storage/README.md
  identity_storage/src/key_storage/jwk_storage.rs
  identity_storage/src/key_storage/key_gen.rs
  identity_storage/src/key_storage/key_id.rs
  identity_storage/src/key_storage/key_storage_error.rs
  identity_storage/src/key_storage/key_type.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/key_storage/mod.rs
  identity_storage/src/lib.rs
Labels: Added, Rust

#1130 Reintroduce cypress tests
  bindings/wasm/build/replace_paths.js
  bindings/wasm/cypress.config.ts
  bindings/wasm/cypress/e2e/.gitkeep
  bindings/wasm/cypress/e2e/0_basic/0_create_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/1_update_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/2_resolve_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/3_deactivate_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/4_delete_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/5_create_vc.cy.js
  bindings/wasm/cypress/e2e/0_basic/6_create_vp.cy.js
  bindings/wasm/cypress/e2e/0_basic/7_revoke_vc.cy.js
  bindings/wasm/cypress/e2e/1_advanced/0_did_controls_did.cy.js
  bindings/wasm/cypress/e2e/1_advanced/1_did_issues_nft.cy.js
  bindings/wasm/cypress/e2e/1_advanced/2_nft_owns_did.cy.js
  bindings/wasm/cypress/e2e/1_advanced/3_did_issues_tokens.cy.js
  bindings/wasm/cypress/e2e/1_advanced/4_key_exchange.cy.js
  bindings/wasm/cypress/e2e/1_advanced/5_custom_resolution.cy.js
  bindings/wasm/cypress/e2e/1_advanced/6_domain_linkage.cy.js
  bindings/wasm/cypress/support/setup.js
  bindings/wasm/examples/src/util.ts
  bindings/wasm/examples/tsconfig.web.json
  bindings/wasm/lib/index.ts
  bindings/wasm/lib/tsconfig.json
  bindings/wasm/lib/tsconfig.web.json
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#1131 Also run dprint action for `js`, `ts` and `json`
  .github/workflows/format.yml
  bindings/wasm/build/replace_paths.js
  bindings/wasm/cypress.config.ts
  bindings/wasm/cypress/e2e/0_basic/0_create_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/1_update_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/2_resolve_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/3_deactivate_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/4_delete_did.cy.js
  bindings/wasm/cypress/e2e/0_basic/5_create_vc.cy.js
  bindings/wasm/cypress/e2e/0_basic/6_create_vp.cy.js
  bindings/wasm/cypress/e2e/0_basic/7_revoke_vc.cy.js
  bindings/wasm/cypress/e2e/1_advanced/0_did_controls_did.cy.js
  bindings/wasm/cypress/e2e/1_advanced/1_did_issues_nft.cy.js
  bindings/wasm/cypress/e2e/1_advanced/2_nft_owns_did.cy.js
  bindings/wasm/cypress/e2e/1_advanced/3_did_issues_tokens.cy.js
  bindings/wasm/cypress/e2e/1_advanced/4_key_exchange.cy.js
  bindings/wasm/cypress/e2e/1_advanced/5_custom_resolution.cy.js
  bindings/wasm/cypress/e2e/1_advanced/6_domain_linkage.cy.js
  bindings/wasm/cypress/support/setup.js
  bindings/wasm/examples/src/util.ts
  dprint.json
Labels: No changelog
