Repository iotaledger/identity, pull requests merged in 2023-03, with the labels that each got.

#1136 pin `form_urlencoded`
  identity_did/Cargo.toml
  identity_document/Cargo.toml
  identity_iota_client_legacy/Cargo.toml
Labels: Dependencies, Rust, Patch

#1139 Update workflow pattern
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/format.yml
  .github/workflows/test-docs-build.yml
Labels: No changelog

#1133 Split (JWS) `Decoder` functionality.
  identity_jose/Cargo.toml
  identity_jose/examples/jws_encoding_decoding.rs
  identity_jose/src/error.rs
  identity_jose/src/jws/algorithm.rs
  identity_jose/src/jws/custom_verification/error.rs
  identity_jose/src/jws/custom_verification/jws_verifier.rs
  identity_jose/src/jws/custom_verification/mod.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/format.rs
  identity_jose/src/jws/mod.rs
  identity_jose/src/jwt/header_set.rs
  identity_jose/src/jwu/serde.rs
  identity_jose/src/tests/ed25519.rs
  identity_jose/src/tests/es256.rs
  identity_jose/src/tests/hs256.rs
  identity_jose/src/tests/rfc7515.rs
  identity_jose/src/tests/rfc7797.rs
  identity_jose/src/tests/rfc8037.rs
  identity_jose/src/tests/roundtrip.rs
Labels: Breaking change, Rust

#1138 Pin `form_urlencoded`
  .github/workflows/build-and-test.yml
  bindings/stronghold-nodejs/.gitignore
  bindings/stronghold-nodejs/Cargo.lock
  bindings/stronghold-nodejs/examples/build/replace_paths.js
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/COPYING
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/COPYING.LESSER
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/README.md
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/dist/rollup-plugin-dts.cjs
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/dist/rollup-plugin-dts.d.ts
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/dist/rollup-plugin-dts.mjs
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/package-lock.json
  bindings/stronghold-nodejs/examples/build/rollup-plugin-dts/package.json
  bindings/stronghold-nodejs/examples/tsconfig.json
  bindings/stronghold-nodejs/package-lock.json
  bindings/stronghold-nodejs/package.json
  bindings/stronghold-nodejs/rollup.config.mjs
  identity_did/Cargo.toml
  identity_iota_client/Cargo.toml
Labels: Rust, Patch

#1141 Move release config flag
  examples/Cargo.toml
Labels: No changelog, Rust

#1134 implement `KeyIdStorage` in Rust
  identity_storage/Cargo.toml
  identity_storage/src/error.rs
  identity_storage/src/key_id_storage/key_id_storage.rs
  identity_storage/src/key_id_storage/key_id_storage_error.rs
  identity_storage/src/key_id_storage/memstore.rs
  identity_storage/src/key_id_storage/method_digest.rs
  identity_storage/src/key_id_storage/mod.rs
  identity_storage/src/key_storage/jwk_storage.rs
  identity_storage/src/key_storage/key_storage_error.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/lib.rs
Labels: Added, Rust

#1143 Add initial PublicKeyJwk support
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/did/wasm_method_data.rs
  bindings/wasm/src/did/wasm_method_type.rs
  bindings/wasm/src/did/wasm_verification_method.rs
  bindings/wasm/src/jose/jwk.rs
  identity_core/Cargo.toml
  identity_core/src/common/one_or_set.rs
  identity_core/src/common/ordered_set.rs
  identity_core/src/common/timestamp.rs
  identity_core/src/common/url.rs
  identity_core/src/error.rs
  identity_core/src/lib.rs
  identity_credential/src/credential/domain_linkage_configuration.rs
  identity_credential/src/credential/policy.rs
  identity_did/Cargo.toml
  identity_did/src/did.rs
  identity_did/src/did_url.rs
  identity_diff/src/option.rs
  identity_document/Cargo.toml
  identity_document/src/document/mod.rs
  identity_document/src/lib.rs
  identity_document/src/verifiable/properties.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_jose/Cargo.toml
  identity_jose/src/jwk/diff/key.rs
  identity_jose/src/jwk/diff/key_operations.rs
  identity_jose/src/jwk/diff/key_params/ec.rs
  identity_jose/src/jwk/diff/key_params/mod.rs
  identity_jose/src/jwk/diff/key_params/oct.rs
  identity_jose/src/jwk/diff/key_params/okp.rs
  identity_jose/src/jwk/diff/key_params/rsa.rs
  identity_jose/src/jwk/diff/key_type.rs
  identity_jose/src/jwk/diff/key_use.rs
  identity_jose/src/jwk/diff/mod.rs
  identity_jose/src/jwk/key.rs
  identity_jose/src/jwk/mod.rs
  identity_jose/src/jwt/header.rs
  identity_jose/src/jwt/header_set.rs
  identity_verification/Cargo.toml
  identity_verification/src/error.rs
  identity_verification/src/verification_method/diff/method_data.rs
  identity_verification/src/verification_method/material.rs
  identity_verification/src/verification_method/method.rs
  identity_verification/src/verification_method/method_type.rs
  identity_verification/src/verification_method/mod.rs
Labels: Wasm, Breaking change, Rust

#1144 Adapt StorageError to be more generic
  identity_core/src/common/mod.rs
  identity_core/src/common/single_struct_error.rs
  identity_jose/Cargo.toml
  identity_jose/src/jws/custom_verification/error.rs
  identity_storage/src/key_id_storage/key_id_storage_error.rs
  identity_storage/src/key_id_storage/method_digest.rs
  identity_storage/src/key_storage/key_storage_error.rs
  identity_storage/src/lib.rs
Labels: Breaking change, Rust

#1146 Fix `SingleStructError` path in `mod.rs`
  identity_core/src/common/mod.rs
Labels: Bug, No changelog

#1147 Wasm bindings for `KeyIdStorage`
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/error.rs
  bindings/wasm/src/storage/key_id_storage.rs
  bindings/wasm/src/storage/method_digest.rs
  bindings/wasm/src/storage/mod.rs
  bindings/wasm/tests/key_id_storage.ts
  identity_storage/src/key_id_storage/key_id_storage.rs
  identity_storage/src/key_id_storage/method_digest.rs
Labels: Enhancement, Wasm, Added
