Repository iotaledger/identity, pull requests merged in 2023-09, with the labels that each got.

#1231 Change `verifiable_credential` to type `Vec<CRED>` in `Presentation`
  examples/0_basic/6_create_vp.rs
  identity_credential/src/error.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/presentation/presentation.rs
  identity_credential/src/presentation/presentation_builder.rs
Labels: Wasm, Breaking change, Rust

#1233 Remove `vp` and `vc` from JWT claims in JOSE
  identity_jose/src/jwt/claims.rs
Labels: Chore, No changelog, Rust

#1236 Fix holder claim check in VP
  identity_credential/src/presentation/jwt_serialization.rs
Labels: Rust, Patch

#1235 Fix issuer claim check in VC
  identity_credential/src/credential/jwt_serialization.rs
Labels: Wasm, Rust, Patch

#1237 Allow custom JWT claims for credentials
  bindings/wasm/src/credential/jwt_credential_validation/decoded_jwt_credential.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/tests/storage.ts
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/1_advanced/6_domain_linkage.rs
  identity_credential/src/credential/credential.rs
  identity_credential/src/credential/jwt_serialization.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/presentation/presentation_builder.rs
  identity_credential/src/validator/vc_jwt_validation/credential_jwt_validator.rs
  identity_credential/src/validator/vc_jwt_validation/decoded_jwt_credential.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/presentation_validation.rs
Labels: Wasm, Added, Rust

#1238 Add dedicated EdDSA verifier crate
  Cargo.toml
  bindings/wasm/Cargo.toml
  bindings/wasm/examples/src/0_basic/5_create_vc.ts
  bindings/wasm/examples/src/0_basic/6_create_vp.ts
  bindings/wasm/examples/src/0_basic/7_revoke_vc.ts
  bindings/wasm/examples/src/1_advanced/5_domain_linkage.ts
  bindings/wasm/src/credential/domain_linkage_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/verification/custom_verification.rs
  bindings/wasm/src/verification/jws_verifier.rs
  bindings/wasm/src/verification/mod.rs
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/storage.ts
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/0_basic/8_stronghold.rs
  examples/1_advanced/6_domain_linkage.rs
  examples/Cargo.toml
  identity_credential/Cargo.toml
  identity_credential/src/domain_linkage/domain_linkage_configuration.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/validator/jwt_credential_validation/decoded_jwt_credential.rs
  identity_credential/src/validator/jwt_credential_validation/error.rs
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validation_options.rs
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator.rs
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator_utils.rs
  identity_credential/src/validator/jwt_credential_validation/mod.rs
  identity_credential/src/validator/jwt_presentation_validation/decoded_jwt_presentation.rs
  identity_credential/src/validator/jwt_presentation_validation/error.rs
  identity_credential/src/validator/jwt_presentation_validation/jwt_presentation_validation_options.rs
  identity_credential/src/validator/jwt_presentation_validation/jwt_presentation_validator.rs
  identity_credential/src/validator/jwt_presentation_validation/jwt_presentation_validator_utils.rs
  identity_credential/src/validator/jwt_presentation_validation/mod.rs
  identity_credential/src/validator/mod.rs
  identity_eddsa_verifier/Cargo.toml
  identity_eddsa_verifier/README.md
  identity_eddsa_verifier/src/ed25519_verifier.rs
  identity_eddsa_verifier/src/eddsa_verifier.rs
  identity_eddsa_verifier/src/lib.rs
  identity_iota/Cargo.toml
  identity_jose/Cargo.toml
  identity_jose/src/jws/custom_verification/jws_verifier.rs
  identity_jose/src/tests/rfc8037.rs
  identity_storage/Cargo.toml
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
  identity_storage/src/storage/tests/credential_validation.rs
  identity_storage/src/storage/tests/presentation_validation.rs
  identity_verification/Cargo.toml
Labels: Wasm, Breaking change, Rust

#1239 Allow custom `kid` to be set in JWS
  bindings/wasm/src/common/timestamp.rs
  bindings/wasm/src/did/jws_verification_options.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/storage/signature_options.rs
  bindings/wasm/tests/credentials.ts
  bindings/wasm/tests/storage.ts
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator.rs
  identity_document/src/document/core_document.rs
  identity_document/src/verifiable/jws_verification_options.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/key_storage/stronghold.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/signature_options.rs
  identity_storage/src/storage/tests/api.rs
  identity_storage/src/storage/tests/credential_jws.rs
Labels: Wasm, Breaking change, Rust

#1243 Add dedicated stronghold crate
  Cargo.toml
  examples/0_basic/8_stronghold.rs
  examples/Cargo.toml
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator_utils.rs
  identity_iota/Cargo.toml
  identity_storage/Cargo.toml
  identity_storage/src/key_id_storage/mod.rs
  identity_storage/src/key_id_storage/tests/mod.rs
  identity_storage/src/key_id_storage/tests/stronghold.rs
  identity_storage/src/key_storage/mod.rs
  identity_storage/src/key_storage/tests/mod.rs
  identity_storage/src/key_storage/tests/stronghold.rs
  identity_storage/src/lib.rs
  identity_storage/src/stronghold_storage.rs
  identity_storage/src/test_utils/stronghold_test_utils.rs
  identity_stronghold/Cargo.toml
  identity_stronghold/README.md
  identity_stronghold/src/ed25519.rs
  identity_stronghold/src/lib.rs
  identity_stronghold/src/stronghold_jwk_storage.rs
  identity_stronghold/src/stronghold_key_id.rs
  identity_stronghold/src/tests/mod.rs
  identity_stronghold/src/tests/test_jwk_storage.rs
  identity_stronghold/src/tests/test_key_id_storage.rs
  identity_stronghold/src/tests/utils.rs
Labels: Breaking change, Rust

#1225 Readd examples in 0.6
  Cargo.toml
Labels: No changelog, Rust

#1245 Allow arbitrary JWS header parameters
  bindings/wasm/src/jose/jws_header.rs
  bindings/wasm/src/storage/signature_options.rs
  bindings/wasm/tests/storage.ts
  identity_jose/src/jws/header.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/signature_options.rs
  identity_storage/src/storage/tests/credential_jws.rs
Labels: Wasm, Added, Rust

#1249 Pin `cargo-release` version to `0.21.1`
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#1251 Pin `cargo-release` version to `0.20.1`
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#1248 Fix version in Readme
  README.md
  identity_iota/README.md
Labels: No changelog

#1253 Update audit ignore
  .cargo/audit.toml
  .github/workflows/audit.yml
Labels: No changelog
