Repository iotaledger/identity, pull requests merged in 2023-04, with the labels that each got.

#1153 Update wiki cli 0.5
  documentation/.yarn/releases/yarn-3.2.0.cjs
  documentation/.yarnrc.yml
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/concepts/verifiable_credentials/revoke.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/install.mdx
  documentation/docs/getting_started/overview.md
  documentation/docs/libraries/rust/getting_started.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/didcomm/resources/credential-info.md
  documentation/docs/specs/didcomm/resources/problem-reports.md
  documentation/docs/tutorials/validate_university_degree.mdx
  documentation/package.json
  documentation/yarn.lock
Labels: No changelog

#1154 Update wiki cli 0.6
  documentation/.yarn/releases/yarn-3.2.0.cjs
  documentation/.yarnrc.yml
  documentation/docs/concepts/advanced/storage_interface.mdx
  documentation/docs/concepts/decentralized_identifiers/create.mdx
  documentation/docs/concepts/verifiable_credentials/revocation.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/install.mdx
  documentation/docs/getting_started/overview.md
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/didcomm/resources/credential-info.md
  documentation/docs/specs/didcomm/resources/problem-reports.md
  documentation/docs/specs/revocation_bitmap_2022.md
  documentation/package.json
  documentation/yarn.lock
Labels: No changelog

#1155 Update wiki cli main
  documentation/.yarn/releases/yarn-3.2.0.cjs
  documentation/.yarnrc.yml
  documentation/docs/concepts/decentralized_identifiers/resolve.mdx
  documentation/docs/concepts/decentralized_identifiers/update.mdx
  documentation/docs/concepts/verifiable_credentials/revocation.mdx
  documentation/docs/getting_started/create_and_publish.mdx
  documentation/docs/getting_started/install.mdx
  documentation/docs/getting_started/overview.md
  documentation/docs/specs/didcomm/overview.md
  documentation/docs/specs/didcomm/protocols/authentication.md
  documentation/docs/specs/didcomm/protocols/connection.md
  documentation/docs/specs/didcomm/protocols/issuance.md
  documentation/docs/specs/didcomm/protocols/post.md
  documentation/docs/specs/didcomm/protocols/presentation.md
  documentation/docs/specs/didcomm/protocols/revocation-options.md
  documentation/docs/specs/didcomm/protocols/revocation.md
  documentation/docs/specs/didcomm/protocols/signing.md
  documentation/docs/specs/didcomm/protocols/termination.md
  documentation/docs/specs/didcomm/resources/credential-info.md
  documentation/docs/specs/didcomm/resources/problem-reports.md
  documentation/docs/specs/revocation_bitmap_2022.md
  documentation/package.json
  documentation/yarn.lock
Labels: No changelog

#1159 Fix 0.6 Wasm build
  identity_iota_client/Cargo.toml
Labels: Chore, No changelog

#1132 Upgrade Stronghold to 1.0 in identity 0.6
  identity_account_storage/Cargo.toml
  identity_account_storage/src/stronghold/wrapper.rs
Labels: Chore, Rust, Patch
