Repository iotaledger/identity, pull requests merged in 2024-03, with the labels that each got.

#1326 Wasm bindings for `BlockChainAccountId` verification method.
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/verification/wasm_method_data.rs
  bindings/wasm/src/verification/wasm_method_type.rs
  identity_verification/src/verification_method/material.rs
Labels: Wasm, Added

#1333 use latest release of sd-jwt-payload
  bindings/wasm/src/sd_jwt/wasm_sd_jwt.rs
  examples/Cargo.toml
  identity_credential/Cargo.toml
Labels: Chore, Rust, Patch

#1336 Fix readme links
  README.md
  identity_iota/README.md
Labels: No changelog

#1340 Refactor `RevocationTimeframeStatus` to align with other setups
  examples/1_advanced/10_zkp_revocation.rs
  identity_credential/Cargo.toml
  identity_credential/src/error.rs
  identity_credential/src/presentation/jwp_presentation_builder.rs
  identity_credential/src/revocation/validity_timeframe_2024/revocation_timeframe_status.rs
  identity_credential/src/validator/jpt_credential_validation/jpt_credential_validator_utils.rs
  identity_credential/src/validator/jwt_credential_validation/error.rs
  identity_document/src/document/core_document.rs
Labels: No changelog, Rust

#1337 Add domain linkage grpc
  bindings/grpc/Cargo.toml
  bindings/grpc/README.md
  bindings/grpc/build.rs
  bindings/grpc/proto/domain_linkage.proto
  bindings/grpc/src/services/domain_linkage.rs
  bindings/grpc/src/services/mod.rs
  bindings/grpc/tests/api/domain_linkage.rs
  bindings/grpc/tests/api/main.rs
  bindings/grpc/tooling/domain-linkage-test-server/.well-known/did-configuration.json
  bindings/grpc/tooling/start-http-server.sh
  bindings/grpc/tooling/start-rpc-server.sh
  identity_credential/src/credential/linked_domain_service.rs
  identity_credential/src/error.rs
Labels: Added, Rust

#1338 Feat/grpc status list 2021
  bindings/grpc/Cargo.toml
  bindings/grpc/README.md
  bindings/grpc/proto/credentials.proto
  bindings/grpc/proto/status_list_2021.proto
  bindings/grpc/src/services/credential/validation.rs
  bindings/grpc/src/services/mod.rs
  bindings/grpc/src/services/status_list_2021.rs
  bindings/grpc/tests/api/credential_validation.rs
  bindings/grpc/tests/api/main.rs
  bindings/grpc/tests/api/status_list_2021.rs
  identity_credential/src/revocation/status_list_2021/credential.rs
Labels: Added, Rust, gRPC

#1339 Use latest releases of zkryptium/json-proof-token and add new BLS key representation
  Cargo.toml
  identity_jose/src/jwk/curve/bls.rs
  identity_jose/src/jwk/curve/mod.rs
  identity_jose/src/jwk/jwk_ext.rs
  identity_storage/src/key_storage/jwk_storage.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/storage/timeframe_revocation_ext.rs
Labels: Chore, Rust, Patch

#1342 Chore: allow large result err variants
  Cargo.toml
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_did/Cargo.toml
  identity_document/Cargo.toml
  identity_eddsa_verifier/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_jose/Cargo.toml
  identity_resolver/Cargo.toml
  identity_storage/Cargo.toml
  identity_stronghold/Cargo.toml
  identity_verification/Cargo.toml
Labels: Chore, Rust, Patch

#1303 Support %-encoded characters in DID method id
  identity_did/Cargo.toml
  identity_did/src/did.rs
  identity_did/src/did_url.rs
  identity_did/src/error.rs
  identity_did/src/lib.rs
  identity_document/Cargo.toml
Labels: Bug, Rust, Patch
