Repository iotaledger/identity, pull requests merged in 2024-12, with the labels that each got.

#1464 Add Move tests to verify delegate's permissions
  identity_iota_core/packages/iota_identity/sources/controller.move
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/multicontroller.move
  identity_iota_core/packages/iota_identity/sources/permissions.move
Labels: Chore, Rust, Patch, Move

#1466 Fix Move Identity creation warning
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/migration.move
  identity_iota_core/src/rebased/iota/move_calls/identity/create.rs
Labels: Chore, Rust, Patch, Move

#1473 Add support for "fauceting" test/example transaction via local active address
  examples/utils/utils.rs
  identity_iota_core/README.md
  identity_iota_core/src/rebased/client/full_client.rs
  identity_iota_core/src/rebased/utils.rs
  identity_iota_core/tests/e2e/common.rs
Labels: Rust, Patch

#1472 Enhance coin retrieval logic in Iota client
  identity_iota_core/src/rebased/client/full_client.rs
Labels: Chore, No changelog, Rust

#1471 Add devnet package information
  examples/utils/utils.rs
  identity_iota_core/Cargo.toml
  identity_iota_core/src/network/network_name.rs
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/iota/mod.rs
  identity_iota_core/src/rebased/iota/well_known_networks.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/tests/e2e/client.rs
  identity_iota_core/tests/e2e/common.rs
Labels: Breaking change, Rust

#1476 Fix formatting issue
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/iota/well_known_networks.rs
Labels: No changelog, Rust

#1477 Fix dprint issue and add license header
  identity_iota_core/Cargo.toml
  identity_iota_core/src/rebased/iota/well_known_networks.rs
Labels: No changelog, Rust

#1478 Add testnet package metadata
  identity_iota_core/src/rebased/iota/well_known_networks.rs
Labels: Added, Chore, Rust

#1479 Update readme includes
  README.md
  identity_iota/README.md
Labels: No changelog

#1480 Add `v1.6.0-alpha.1` changelog
  CHANGELOG.md
Labels: No changelog

#1481 Fix README.md example code and instructions
  README.md
  identity_iota/README.md
Labels: Bug, Chore, No changelog

#1482 Fix failing DID IOTA tests and add NetworkName alias for well known networks
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/iota/well_known_networks.rs
Labels: Bug, Added, Rust, Patch

#1483 Fix gRPC binding build issues
  bindings/grpc/src/main.rs
  bindings/grpc/src/services/document.rs
  bindings/grpc/src/services/utils.rs
Labels: No changelog, Rust, gRPC

#1487 Add support for CI in PRs that target `feat/...` branches
  .github/workflows/audit.yml
  .github/workflows/build-and-test-grpc.yml
  .github/workflows/build-and-test.yml
  .github/workflows/clippy.yml
  .github/workflows/format.yml
Labels: Chore, No changelog

#1485 Update rebased readme
  README.md
  identity_iota/README.md
Labels: No changelog

#1486 Add Rebased banner for Stardust
  README.md
  identity_iota/README.md
Labels: No changelog
