Repository iotaledger/identity, pull requests merged in 2024-11, with the labels that each got.

#1424 Replace `stardust-test` Move package with IOTA's official `stardust`
  identity_iota_core/packages/identity_iota/Move.toml
  identity_iota_core/packages/identity_iota/sources/migration.move
  identity_iota_core/packages/stardust-test/.gitignore
  identity_iota_core/packages/stardust-test/Move.lock
  identity_iota_core/packages/stardust-test/Move.toml
  identity_iota_core/packages/stardust-test/README.md
  identity_iota_core/packages/stardust-test/basic_migration_graph.svg
  identity_iota_core/packages/stardust-test/design.md
  identity_iota_core/packages/stardust-test/sources/alias/alias.move
  identity_iota_core/packages/stardust-test/sources/alias/alias_output.move
  identity_iota_core/packages/stardust-test/sources/basic/basic_output.move
  identity_iota_core/packages/stardust-test/sources/capped_coin.move
  identity_iota_core/packages/stardust-test/sources/nft/irc27.move
  identity_iota_core/packages/stardust-test/sources/nft/nft.move
  identity_iota_core/packages/stardust-test/sources/nft/nft_output.move
  identity_iota_core/packages/stardust-test/sources/unlock_condition/address_unlock_condition.move
  identity_iota_core/packages/stardust-test/sources/unlock_condition/expiration_unlock_condition.move
  identity_iota_core/packages/stardust-test/sources/unlock_condition/storage_deposit_return_unlock_condition.move
  identity_iota_core/packages/stardust-test/sources/unlock_condition/timelock_unlock_condition.move
  identity_iota_core/packages/stardust-test/sources/utilities.move
  identity_iota_core/packages/stardust-test/tests/alias_tests.move
  identity_iota_core/packages/stardust-test/tests/basic_tests.move
  identity_iota_core/packages/stardust-test/tests/capped_coin_tests.move
  identity_iota_core/packages/stardust-test/tests/nft_tests.move
  identity_iota_core/packages/stardust-test/tests/unlock_condition/address_unlock_condition_tests.move
  identity_iota_core/scripts/create_test_alias_output.sh
  identity_iota_core/scripts/create_test_identity.sh
  identity_iota_core/scripts/migrate_alias_output.sh
  identity_iota_core/src/rebased/migration/alias.rs
  identity_iota_core/src/rebased/sui/move_calls/migration.rs
  identity_iota_core/src/rebased/sui/move_calls/mod.rs
  identity_iota_core/tests/e2e/client.rs
  identity_iota_core/tests/e2e/common.rs
  identity_iota_core/tests/e2e/main.rs
  identity_iota_core/tests/e2e/migration.rs
  identity_iota_core/tests/e2e/test.rs
Labels: Enhancement, Rust, Patch

#1427 Polish identity package
  identity_iota_core/packages/identity_iota/Move.lock
  identity_iota_core/packages/identity_iota/sources/owned.move
  identity_iota_core/packages/iota_identity/Move.toml
  identity_iota_core/packages/iota_identity/sources/asset.move
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/migration.move
  identity_iota_core/packages/iota_identity/sources/migration_registry.move
  identity_iota_core/packages/iota_identity/sources/multicontroller.move
  identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
  identity_iota_core/packages/iota_identity/sources/proposals/config.move
  identity_iota_core/packages/iota_identity/sources/proposals/did_deactivation.move
  identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
  identity_iota_core/packages/iota_identity/sources/proposals/value.move
  identity_iota_core/packages/iota_identity/sources/public_vc.move
  identity_iota_core/packages/iota_identity/sources/utils.move
  identity_iota_core/scripts/publish_identity_package.sh
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/tests/e2e/common.rs
Labels: Chore, Rust, Patch

#1430 Remove stardust related code
  bindings/grpc/Cargo.toml
  bindings/grpc/src/main.rs
  bindings/grpc/src/server.rs
  bindings/grpc/src/services/credential/jwt.rs
  bindings/grpc/src/services/credential/mod.rs
  bindings/grpc/src/services/credential/revocation.rs
  bindings/grpc/src/services/credential/validation.rs
  bindings/grpc/src/services/document.rs
  bindings/grpc/src/services/domain_linkage.rs
  bindings/grpc/src/services/mod.rs
  bindings/grpc/src/services/sd_jwt.rs
  bindings/grpc/tests/api/did_document_creation.rs
  bindings/grpc/tests/api/domain_linkage.rs
  bindings/grpc/tests/api/helpers.rs
  bindings/grpc/tests/api/jwt.rs
  bindings/wasm/Cargo.toml
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/0_basic/8_legacy_stronghold.rs
  examples/1_advanced/10_zkp_revocation.rs
  examples/1_advanced/11_linked_verifiable_presentation.rs
  examples/1_advanced/4_identity_history.rs
  examples/1_advanced/5_custom_resolution.rs
  examples/1_advanced/6_domain_linkage.rs
  examples/1_advanced/9_zkp.rs
  examples/Cargo.toml
  identity_credential/Cargo.toml
  identity_iota/src/lib.rs
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_iota_core/src/client/iota_client.rs
  identity_iota_core/src/client/mod.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/did_resolution/did_resolution_handler.rs
  identity_iota_core/src/did_resolution/mod.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/error.rs
  identity_iota_core/src/lib.rs
  identity_iota_core/src/network/network_name.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/tests/e2e/identity.rs
  identity_resolver/Cargo.toml
  identity_resolver/src/resolution/resolver.rs
  identity_storage/Cargo.toml
Labels: Breaking change, Rust

#1432 Emit Move events when performing operations on on-chain identities
  identity_iota_core/packages/iota_identity/sources/asset.move
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
  identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
Labels: Enhancement, Added, Rust

#1431 Onchain identity controller delegation
  identity_iota_core/packages/iota_identity/sources/asset.move
  identity_iota_core/packages/iota_identity/sources/controller.move
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/migration.move
  identity_iota_core/packages/iota_identity/sources/multicontroller.move
  identity_iota_core/packages/iota_identity/sources/permissions.move
  identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
  identity_iota_core/packages/iota_identity/sources/proposals/config.move
  identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
  identity_iota_core/packages/iota_identity/sources/proposals/value.move
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/borrow_asset.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/config.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/create.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/deactivate.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/proposal.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/send_asset.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/update.rs
  identity_iota_core/src/rebased/sui/move_calls/utils.rs
  identity_iota_core/tests/e2e/identity.rs
Labels: Enhancement, Added, Rust

#1450 Update examples
  README.md
  examples/0_basic/1_update_did.rs
  examples/0_basic/2_resolve_did.rs
  examples/0_basic/3_deactivate_did.rs
  examples/1_advanced/10_zkp_revocation.rs
  examples/1_advanced/4_identity_history.rs
  examples/1_advanced/9_zkp.rs
  examples/README.md
  examples/utils/utils.rs
  identity_iota/README.md
  identity_iota_core/src/did_resolution/did_resolution_handler.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/state_metadata/document.rs
Labels: Documentation, No changelog, Rust

#1435 Versioning of on-chain `Identity`
  identity_iota_core/Cargo.toml
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/proposals/upgrade.move
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/upgrade.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/mod.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/upgrade.rs
Labels: Enhancement, Added, Rust

#1455 Fix clippy and fmt issues
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/upgrade.rs
  identity_iota_core/src/rebased/sui/move_calls/identity/mod.rs
  identity_iota_core/tests/e2e/identity.rs
Labels: No changelog, Rust

#1457 Fix gRPC build in CI
  bindings/grpc/Cargo.toml
Labels: No changelog, Rust, gRPC

#1459 Update wording to "identity"
  examples/1_advanced/4_identity_history.rs
  identity_iota_core/src/did/iota_did.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/rebased/migration/identity.rs
Labels: Documentation, No changelog, Rust

#1458 Fix CI issues
  .github/actions/iota-rebase-sandbox/setup/action.yml
  .github/workflows/build-and-test.yml
  README.md
  bindings/grpc/Cargo.toml
  bindings/grpc/tests/api/helpers.rs
  examples/Cargo.toml
  examples/utils/utils.rs
  identity_credential/src/credential/jwt_serialization.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/revocation/status_list_2021/entry.rs
  identity_credential/src/revocation/validity_timeframe_2024/revocation_timeframe_status.rs
  identity_document/src/document/core_document.rs
  identity_document/src/utils/did_url_query.rs
  identity_iota/Cargo.toml
  identity_iota/README.md
  identity_iota_core/Cargo.toml
  identity_iota_core/packages/iota_identity/Move.toml
  identity_iota_core/scripts/publish_identity_package.sh
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/rebased/assets/asset.rs
  identity_iota_core/src/rebased/migration/alias.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/config_change.rs
  identity_iota_core/src/rebased/proposals/controller.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/send.rs
  identity_iota_core/tests/e2e/common.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/encoding/utils.rs
  identity_jose/src/jws/recipient.rs
  identity_storage/src/storage/storage_signer.rs
Labels: Chore, No changelog

#1463 Rename internal `sui` module to `iota`
  identity_iota_core/src/rebased/assets/asset.rs
  identity_iota_core/src/rebased/iota/mod.rs
  identity_iota_core/src/rebased/iota/move_calls/asset/create.rs
  identity_iota_core/src/rebased/iota/move_calls/asset/delete.rs
  identity_iota_core/src/rebased/iota/move_calls/asset/mod.rs
  identity_iota_core/src/rebased/iota/move_calls/asset/transfer.rs
  identity_iota_core/src/rebased/iota/move_calls/asset/update.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/borrow_asset.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/config.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/controller_execution.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/create.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/deactivate.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/mod.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/proposal.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/send_asset.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/update.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/upgrade.rs
  identity_iota_core/src/rebased/iota/move_calls/migration.rs
  identity_iota_core/src/rebased/iota/move_calls/mod.rs
  identity_iota_core/src/rebased/iota/move_calls/utils.rs
  identity_iota_core/src/rebased/iota/types/mod.rs
  identity_iota_core/src/rebased/iota/types/number.rs
  identity_iota_core/src/rebased/migration/alias.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/migration/multicontroller.rs
  identity_iota_core/src/rebased/mod.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/config_change.rs
  identity_iota_core/src/rebased/proposals/controller.rs
  identity_iota_core/src/rebased/proposals/deactivate_did.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/send.rs
  identity_iota_core/src/rebased/proposals/update_did_doc.rs
  identity_iota_core/src/rebased/proposals/upgrade.rs
Labels: Chore, Rust, Patch
