Repository iotaledger/identity, pull requests merged in 2024-04, with the labels that each got.

#1348 chore(cargo): inherit `repository` in identity_verification
  identity_verification/Cargo.toml
Labels: Chore, No changelog, Rust

#1351 Use zkryptium for cryptographic operations inside Memstore
  Cargo.toml
  examples/1_advanced/10_zkp_revocation.rs
  examples/1_advanced/9_zkp.rs
  identity_credential/src/presentation/jwp_presentation_builder.rs
  identity_jose/src/jwk/curve/bls.rs
  identity_jose/src/jwk/curve/mod.rs
  identity_jose/src/jwk/jwk_ext.rs
  identity_jose/src/jwk/key_params.rs
  identity_storage/src/key_storage/bls.rs
  identity_storage/src/key_storage/jwk_storage.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/key_storage/mod.rs
  identity_storage/src/storage/jwp_document_ext.rs
  identity_storage/src/storage/timeframe_revocation_ext.rs
Labels: No changelog

#1356 Chore: add inx-faucet profile
  .github/actions/iota-sandbox/setup/action.yml
Labels: Chore, No changelog, Patch

#1343 Fix dockerhub workflow
  .github/workflows/grpc-publish-to-dockerhub.yml
  bindings/grpc/README.md
Labels: No changelog

#1350 gRPC/Arbitrary data signing service
  bindings/grpc/proto/utils.proto
  bindings/grpc/src/services/mod.rs
  bindings/grpc/src/services/utils.rs
  bindings/grpc/tests/api/main.rs
  bindings/grpc/tests/api/utils.rs
Labels: Enhancement, Added, No changelog, gRPC

#1363 Use STRONGHOLD_PWD_FILE env variable to pass stronghold's password
  bindings/grpc/src/main.rs
Labels: Added, No changelog, gRPC
