Repository iotaledger/identity, pull requests merged in 2024-05, with the labels that each got.

#1365 Fix findings after clippy update
  .github/actions/rust/rust-setup/action.yml
  bindings/wasm/Cargo.toml
  identity_credential/src/credential/proof.rs
  identity_credential/src/revocation/status_list_2021/credential.rs
  identity_credential/src/validator/test_utils.rs
  identity_iota_core/src/document/test_utils.rs
  identity_jose/src/jwk/key_params.rs
  identity_jose/src/jwt/header.rs
  identity_jose/src/jwu/serde.rs
  identity_storage/src/key_storage/ed25519.rs
  identity_storage/src/key_storage/memstore.rs
  identity_storage/src/key_storage/tests/utils.rs
  identity_storage/src/storage/tests/test_utils.rs
  identity_stronghold/src/ed25519.rs
  identity_stronghold/src/stronghold_jwk_storage.rs
  identity_stronghold/src/tests/test_jwk_storage.rs
  identity_stronghold/src/tests/utils.rs
Labels: Chore, No changelog, Rust

#1353 Add EcDSA verifier
  .github/workflows/build-and-test.yml
  .license_template
  Cargo.toml
  identity_ecdsa_verifier/Cargo.toml
  identity_ecdsa_verifier/README.md
  identity_ecdsa_verifier/src/ecdsa_jws_verifier.rs
  identity_ecdsa_verifier/src/lib.rs
  identity_ecdsa_verifier/src/secp256k1.rs
  identity_ecdsa_verifier/src/secp256r1.rs
  identity_ecdsa_verifier/src/tests/mod.rs
  identity_ecdsa_verifier/src/tests/secp256.rs
  identity_ecdsa_verifier/src/tests/secp256k.rs
Labels: Added, Rust

#1367 Support for specification-compliant verification method type `JsonWebKey2020`
  bindings/wasm/src/verification/wasm_method_type.rs
  bindings/wasm/tests/core.ts
  bindings/wasm/tests/iota.ts
  identity_verification/src/verification_method/method.rs
  identity_verification/src/verification_method/method_type.rs
Labels: Bug, Rust, Patch
