Repository iotaledger/identity, pull requests merged in 2024-02, with the labels that each got.

#1290 Adapt to IOTA sandbox
  .github/actions/iota-sandbox/setup/action.yml
  .github/actions/iota-sandbox/tear-down/action.yml
  .github/actions/private-tangle/setup/action.yml
  .github/actions/private-tangle/tear-down/action.yml
  .github/workflows/build-and-test.yml
  README.md
  bindings/wasm/README.md
  bindings/wasm/examples/src/util.ts
  examples/0_basic/0_create_did.rs
  examples/0_basic/8_stronghold.rs
  examples/utils/utils.rs
  identity_iota/README.md
Labels: No changelog

#1292 Fix RevocationBitmap2022 encoding bug
  identity_credential/Cargo.toml
  identity_credential/src/revocation/revocation_bitmap_2022/bitmap.rs
Labels: Bug, Rust, Patch

#1296 Update `sd-jwt-payload` dependency
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/1_advanced/6_sd_jwt.ts
  bindings/wasm/src/sd_jwt/encoder.rs
  bindings/wasm/tests/sd_jwt.ts
  examples/1_advanced/7_sd_jwt.rs
  examples/1_advanced/8_status_list_2021.rs
  examples/Cargo.toml
  identity_credential/Cargo.toml
  identity_storage/src/storage/tests/kb_jwt.rs
Labels: Wasm, No changelog, Rust

#1306 Fix compilation error caused by the `roaring` crate
  README.md
  identity_credential/Cargo.toml
Labels: Bug, Rust, Patch

#1310 Add dummy client for testing multi resolver handlers
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_resolver/Cargo.toml
  identity_resolver/src/resolution/resolver.rs
Labels: No changelog

#1311 Add `get_public_key` for `StrongholdStorage`
  identity_stronghold/src/stronghold_jwk_storage.rs
  identity_stronghold/src/tests/test_jwk_storage.rs
Labels: Added, Rust

#1304 Support multiple IOTA networks in the `Resolver`
  identity_iota_core/Cargo.toml
  identity_iota_core/src/client/identity_client.rs
  identity_resolver/Cargo.toml
  identity_resolver/src/error.rs
  identity_resolver/src/resolution/resolver.rs
Labels: Added, Rust

#1305 Add new Verification method type
  identity_verification/src/verification_method/material.rs
  identity_verification/src/verification_method/method_type.rs
Labels: Wasm, Added, Rust

#1314 Allow setting additional controllers for `IotaDocument`.
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/iota/iota_document.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/state_metadata/document.rs
Labels: Added, Rust

#1317 Fix example crate compilation with `--no-default-features`
  examples/Cargo.toml
Labels: Bug, No changelog

#1319 Include examples in cargo check
  .github/workflows/build-and-test.yml
Labels: No changelog
