Repository iotaledger/identity, pull requests merged in 2024-09, with the labels that each got.

#1393 Make `bls12_381_plus` dependency more flexible again
  .github/workflows/build-and-test.yml
  Cargo.toml
  bindings/wasm/Cargo.toml
  identity_credential/Cargo.toml
  identity_eddsa_verifier/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_jose/Cargo.toml
  identity_jose/src/tests/rfc8037.rs
  identity_storage/Cargo.toml
  identity_stronghold/Cargo.toml
Labels: Chore, Rust, Patch

#1404 Add support for `did:jwk` resolution
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/src/did/did_jwk.rs
  bindings/wasm/src/did/mod.rs
  bindings/wasm/src/did/wasm_core_document.rs
  identity_did/Cargo.toml
  identity_did/src/did_jwk.rs
  identity_did/src/lib.rs
  identity_document/src/document/core_document.rs
  identity_iota_core/src/document/iota_document.rs
  identity_resolver/src/resolution/resolver.rs
  identity_verification/src/verification_method/method.rs
Labels: Enhancement, Wasm, Added, Rust

#1396 Add WASM bindings for EcDSA JWS Verifier
  bindings/wasm/Cargo.toml
  bindings/wasm/docs/api-reference.md
  bindings/wasm/src/credential/domain_linkage_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/jwt_credential_validation/sd_jwt_validator.rs
  bindings/wasm/src/credential/jwt_presentation_validation/jwt_presentation_validator.rs
  bindings/wasm/src/did/wasm_core_document.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/verification/custom_verification.rs
  bindings/wasm/src/verification/jws_verifier.rs
Labels: Documentation, Wasm, Added

#1399 Use Typedoc for Wasm API docs
  .github/actions/publish/publish-wasm/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-wasm.yml
  .github/workflows/upload-docs.yml
  .gitignore
  bindings/wasm/build/docs.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/sd_jwt/encoder.rs
  bindings/wasm/tsconfig.typedoc.json
  bindings/wasm/typedoc.json
Labels: No changelog

#1414 Fix crate version in readme
  README.md
  identity_iota/README.md
Labels: No changelog
