Repository iotaledger/identity, pull requests merged in 2024-01, with the labels that each got.

#1268 Support Selective Disclosure SD-JWT
  bindings/wasm/Cargo.toml
  bindings/wasm/cypress/e2e/1_advanced/6_sd_jwt.cy.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/1_advanced/6_sd_jwt.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/6_sd_jwt.ts
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/jwt_credential_validation/kb_validation_options.rs
  bindings/wasm/src/credential/jwt_credential_validation/mod.rs
  bindings/wasm/src/credential/jwt_credential_validation/sd_jwt_validator.rs
  bindings/wasm/src/error.rs
  bindings/wasm/src/iota/iota_document.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/sd_jwt/decoder.rs
  bindings/wasm/src/sd_jwt/disclosure.rs
  bindings/wasm/src/sd_jwt/encoder.rs
  bindings/wasm/src/sd_jwt/key_binding_jwt_claims.rs
  bindings/wasm/src/sd_jwt/mod.rs
  bindings/wasm/src/sd_jwt/wasm_sd_jwt.rs
  bindings/wasm/tests/sd_jwt.ts
  examples/0_basic/5_create_vc.rs
  examples/0_basic/6_create_vp.rs
  examples/0_basic/7_revoke_vc.rs
  examples/1_advanced/6_domain_linkage.rs
  examples/1_advanced/7_sd_jwt.rs
  examples/Cargo.toml
  examples/README.md
  examples/utils/utils.rs
  identity_credential/Cargo.toml
  identity_credential/src/lib.rs
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator.rs
  identity_credential/src/validator/mod.rs
  identity_credential/src/validator/sd_jwt/error.rs
  identity_credential/src/validator/sd_jwt/kb_validation_options.rs
  identity_credential/src/validator/sd_jwt/mod.rs
  identity_credential/src/validator/sd_jwt/validator.rs
  identity_document/src/document/core_document.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_storage/src/storage/jwk_document_ext.rs
  identity_storage/src/storage/tests/kb_jwt.rs
  identity_storage/src/storage/tests/mod.rs
  identity_stronghold/src/lib.rs
Labels: Wasm, Added, Rust

#1232 Add code owners file
  .github/CODEOWNERS
Labels: No changelog

#1252 Update cargo release
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#1278 Fix cargo release invocation
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#1273 Feat/status list 2021
  bindings/wasm/Cargo.toml
  bindings/wasm/cypress/e2e/1_advanced/7_status_list_2021.cy.js
  bindings/wasm/docs/api-reference.md
  bindings/wasm/examples/README.md
  bindings/wasm/examples/src/1_advanced/7_status_list_2021.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/examples/src/tests/7_status_list_2021.ts
  bindings/wasm/src/credential/credential.rs
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/mod.rs
  bindings/wasm/src/credential/revocation/mod.rs
  bindings/wasm/src/credential/revocation/status_list_2021/credential.rs
  bindings/wasm/src/credential/revocation/status_list_2021/entry.rs
  bindings/wasm/src/credential/revocation/status_list_2021/mod.rs
  bindings/wasm/src/credential/revocation/status_list_2021/status_list.rs
  bindings/wasm/src/credential/types.rs
  bindings/wasm/src/error.rs
  examples/1_advanced/8_status_list_2021.rs
  examples/Cargo.toml
  examples/README.md
  identity_credential/Cargo.toml
  identity_credential/src/credential/builder.rs
  identity_credential/src/credential/status.rs
  identity_credential/src/revocation/mod.rs
  identity_credential/src/revocation/revocation_bitmap_2022/bitmap.rs
  identity_credential/src/revocation/revocation_bitmap_2022/document_ext.rs
  identity_credential/src/revocation/revocation_bitmap_2022/mod.rs
  identity_credential/src/revocation/status_list_2021/credential.rs
  identity_credential/src/revocation/status_list_2021/entry.rs
  identity_credential/src/revocation/status_list_2021/mod.rs
  identity_credential/src/revocation/status_list_2021/status_list.rs
  identity_credential/src/validator/jwt_credential_validation/error.rs
  identity_credential/src/validator/jwt_credential_validation/jwt_credential_validator_utils.rs
  identity_iota/Cargo.toml
Labels: Documentation, Wasm, Added, Rust

#1279 Split cargo release command
  .github/actions/publish/publish-rust/action.yml
Labels: No changelog

#1280 Remove local versions from Wasm crate
  .github/actions/release/bump-versions/action.yml
  bindings/wasm/Cargo.toml
Labels: No changelog

#1282 Remove dev dependency version
  identity_credential/Cargo.toml
Labels: No changelog

#1284 Credentials cannot be unrevoked with StatusList2021
  identity_credential/src/revocation/status_list_2021/credential.rs
Labels: Bug, Rust, Patch
