Repository iotaledger/identity, pull requests merged in 2025-03, with the labels that each got.

#1581 WASM: make KeytoolSigner extend the `TransactionSigner` interface
  bindings/wasm/iota_interaction_ts/src/bindings/keytool_signer.rs
Labels: Wasm, Chore, No changelog, Patch

#1582 Fix interaction web build
  bindings/wasm/build/web.js
Labels: No changelog

#1585 Add smaller test and debug improvements
  .github/actions/iota-rebase-sandbox/setup/action.yml
  .github/workflows/build-and-test.yml
  bindings/grpc/tests/api/helpers.rs
  bindings/wasm/identity_wasm/package.json
  identity_iota_core/scripts/publish_identity_package.sh
  identity_iota_core/tests/e2e/common.rs
Labels: No changelog

#1587 Fix Transaction handling for WASM on testnet
  bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/identity_wasm/examples/src/util.ts
  bindings/wasm/identity_wasm/src/rebased/identity.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
  bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
  identity_iota_core/src/iota_interaction_rust/iota_client_rust_sdk.rs
Labels: Bug, Wasm, Rust, Patch

#1588 Fix Interaction Wasm build
  bindings/wasm/iota_interaction_ts/lib/index.ts
  bindings/wasm/iota_interaction_ts/src/asset_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
  bindings/wasm/iota_interaction_ts/src/migration_move_calls.rs
Labels: No changelog

#1583 Re-export interaction bindings
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/iota_interaction_ts/lib/index.ts
  bindings/wasm/iota_interaction_ts/lib/tsconfig.json
  bindings/wasm/iota_interaction_ts/lib/tsconfig.web.json
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
  bindings/wasm/iota_interaction_ts/tsconfig.json
Labels: No changelog

#1601 Exclude interaction docs, fix docs path
  .github/workflows/upload-docs.yml
  bindings/wasm/identity_wasm/tsconfig.typedoc.json
  bindings/wasm/identity_wasm/typedoc.json
Labels: No changelog

#1606 Upstream changes v0.10.3-rc
  .cargo/audit.toml
  .github/actions/iota-rebase-sandbox/setup/action.yml
  bindings/grpc/Cargo.toml
  bindings/wasm/identity_wasm/Cargo.toml
  bindings/wasm/iota_interaction_ts/Cargo.toml
  examples/Cargo.toml
  identity_credential/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_interaction/Cargo.toml
  identity_iota_interaction/src/sdk_types/iota_types/balance.rs
  identity_iota_interaction/src/sdk_types/iota_types/coin.rs
  identity_iota_interaction/src/sdk_types/iota_types/crypto.rs
  identity_iota_interaction/src/sdk_types/iota_types/id.rs
  identity_iota_interaction/src/sdk_types/iota_types/iota_types_lib.rs
  identity_iota_interaction/src/sdk_types/mod.rs
  identity_iota_interaction/src/sdk_types/move_command_line_common/mod.rs
  identity_iota_interaction/src/sdk_types/move_core_types/account_address.rs
  identity_iota_interaction/src/sdk_types/move_core_types/annotated_value.rs
  identity_iota_interaction/src/sdk_types/move_core_types/annotated_visitor.rs
  identity_iota_interaction/src/sdk_types/move_core_types/identifier.rs
  identity_iota_interaction/src/sdk_types/move_core_types/language_storage.rs
  identity_iota_interaction/src/sdk_types/move_core_types/mod.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parser.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parsing/address.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parsing/mod.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parsing/parser.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parsing/types.rs
  identity_iota_interaction/src/sdk_types/move_core_types/parsing/values.rs
  identity_iota_interaction/src/sdk_types/move_core_types/runtime_value.rs
  identity_iota_interaction/src/sdk_types/move_core_types/u256.rs
  identity_resolver/Cargo.toml
  identity_storage/Cargo.toml
  identity_stronghold/Cargo.toml
Labels: Wasm, No changelog, Rust

#1613 Harmonize example Readmes, replace Wiki links
  README.md
  bindings/wasm/identity_wasm/README.md
  bindings/wasm/identity_wasm/examples/README.md
  examples/README.md
  identity_credential/README.md
  identity_iota/README.md
  identity_iota_core/README.md
Labels: No changelog

#1615 Bump rust versions
  bindings/wasm/iota_interaction_ts/Cargo.toml
  examples/Cargo.toml
  identity_core/Cargo.toml
  identity_credential/Cargo.toml
  identity_did/Cargo.toml
  identity_document/Cargo.toml
  identity_ecdsa_verifier/Cargo.toml
  identity_eddsa_verifier/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_interaction/Cargo.toml
  identity_jose/Cargo.toml
  identity_resolver/Cargo.toml
  identity_storage/Cargo.toml
  identity_stronghold/Cargo.toml
  identity_verification/Cargo.toml
Labels: No changelog

#1616 Delete DID
  bindings/wasm/identity_wasm/examples/src/0_basic/4_delete_did.ts
  bindings/wasm/identity_wasm/examples/src/main.ts
  bindings/wasm/identity_wasm/src/rebased/identity.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/update_did.rs
  examples/0_basic/4_delete_did.rs
  examples/Cargo.toml
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/update_did_doc.rs
  identity_iota_core/tests/e2e/identity.rs
Labels: Wasm, Added, Rust

#1622 Pin `derange` version to avoid conflicts in `iota-sdk`
  .github/actions/rust/rust-setup/action.yml
  identity_core/Cargo.toml
Labels: Bug, Rust, Patch

#1624 Include `IotaIdentity` Move.lock file
  .gitignore
  identity_iota_core/packages/iota_identity/Move.lock
Labels: Chore, No changelog
