Repository iotaledger/identity, pull requests merged in 2025-02, with the labels that each got.

#1523 Shared `StorageSigner` implementation for WASM
  bindings/wasm/identity_wasm/src/kinesis/client_dummy/identity.rs
  bindings/wasm/identity_wasm/src/kinesis/identity.rs
  bindings/wasm/identity_wasm/src/kinesis/wasm_identity_client.rs
  bindings/wasm/identity_wasm/src/kinesis/wasm_identity_client_read_only.rs
  bindings/wasm/identity_wasm/src/storage/mod.rs
  bindings/wasm/identity_wasm/src/storage/storage_signer_owned.rs
  bindings/wasm/identity_wasm/src/storage/wasm_storage.rs
  bindings/wasm/identity_wasm/src/storage/wasm_storage_signer.rs
  bindings/wasm/identity_wasm/src/storage/wasm_transaction_signer.rs
  identity_storage/src/storage/storage_signer.rs
Labels: Enhancement, Wasm, Patch

#1526 Re-add Resolver API for WASM builds
  .github/actions/rust/rust-setup/action.yml
  bindings/wasm/identity_wasm/Cargo.toml
  bindings/wasm/identity_wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts
  bindings/wasm/identity_wasm/examples/src/main.ts
  bindings/wasm/identity_wasm/lib/index.ts
  bindings/wasm/identity_wasm/lib/resolver.ts
  bindings/wasm/identity_wasm/src/error.rs
  bindings/wasm/identity_wasm/src/iota/iota_document.rs
  bindings/wasm/identity_wasm/src/resolver/mod.rs
  bindings/wasm/identity_wasm/src/resolver/resolver_config.rs
  bindings/wasm/identity_wasm/src/resolver/wasm_did_resolution_handler.rs
  bindings/wasm/identity_wasm/src/resolver/wasm_resolver.rs
  examples/1_advanced/10_zkp_revocation.rs
  examples/1_advanced/9_zkp.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_resolver/src/resolution/resolver.rs
Labels: Enhancement, Wasm, Added

#1530 Replace did-key dependency to fix tests
  bindings/wasm/examples/src/1_advanced/4_custom_resolution.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
Labels: No changelog

#1531 Fix did key test rebased
  bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
Labels: No changelog

#1539 Add waiting for transaction block availability to TS variant of `execute_transaction`
  bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
  bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
  identity_iota_core/src/iota_interaction_rust/iota_client_rust_sdk.rs
  identity_iota_interaction/src/iota_client_trait.rs
  identity_iota_interaction/src/sdk_types/generated_types.rs
Labels: Bug, Wasm, Added

#1536 Reenable Wasm tests
  .github/workflows/build-and-test.yml
  .github/workflows/shared-build-wasm.yml
  bindings/wasm/.cargo/config.toml
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/iota_interaction_ts/Cargo.toml
  bindings/wasm/iota_interaction_ts/lib/tsconfig.web.json
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
Labels: No changelog

#1542 Update did fetching in wasm examples
  bindings/wasm/identity_wasm/examples/src/0_basic/0_create_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/identity_wasm/examples/src/1_advanced/4_custom_resolution.ts
Labels: Wasm, Chore, No changelog

#1543 Remove stardust artifacts
  bindings/wasm/identity_wasm/README.md
  bindings/wasm/identity_wasm/cypress/support/setup.js
  bindings/wasm/identity_wasm/examples/README.md
  bindings/wasm/identity_wasm/examples/src/0_basic/1_update_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/2_resolve_did.ts
  bindings/wasm/identity_wasm/examples/src/0_basic/3_deactivate_did.ts
  bindings/wasm/identity_wasm/examples/tsconfig.web.json
  bindings/wasm/identity_wasm/lib/index.ts
  bindings/wasm/identity_wasm/lib/iota_identity_client.ts
  bindings/wasm/identity_wasm/lib/tsconfig.json
  bindings/wasm/identity_wasm/lib/tsconfig.web.json
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/identity_wasm/src/iota/identity_client.rs
  bindings/wasm/identity_wasm/src/iota/identity_client_ext.rs
  bindings/wasm/identity_wasm/src/iota/iota_document.rs
  bindings/wasm/identity_wasm/src/iota/mod.rs
  bindings/wasm/identity_wasm/src/lib.rs
  bindings/wasm/identity_wasm/src/obsolete/identity_client.rs
  bindings/wasm/identity_wasm/src/obsolete/mod.rs
  bindings/wasm/iota_interaction_ts/lib/tsconfig.json
  bindings/wasm/iota_interaction_ts/lib/tsconfig.web.json
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
Labels: No changelog

#1544 Fix format issues
  bindings/wasm/identity_wasm/Cargo.toml
  bindings/wasm/identity_wasm/src/iota/iota_document.rs
  bindings/wasm/identity_wasm/src/rebased/client_dummy/identity.rs
  bindings/wasm/identity_wasm/src/rebased/client_dummy/mod.rs
  bindings/wasm/identity_wasm/src/rebased/client_dummy/multicontroller.rs
  bindings/wasm/identity_wasm/src/rebased/identity.rs
  bindings/wasm/identity_wasm/src/rebased/mod.rs
  bindings/wasm/identity_wasm/src/rebased/multicontroller.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/config_change.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/mod.rs
  bindings/wasm/identity_wasm/src/rebased/types.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client_read_only.rs
  bindings/wasm/iota_interaction_ts/Cargo.toml
  bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/update.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/utils.ts
  bindings/wasm/iota_interaction_ts/src/asset_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/bindings/mod.rs
  bindings/wasm/iota_interaction_ts/src/bindings/types.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
  bindings/wasm/iota_interaction_ts/src/common/types.rs
  bindings/wasm/iota_interaction_ts/src/common/utils.rs
  bindings/wasm/iota_interaction_ts/src/identity_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
  bindings/wasm/iota_interaction_ts/src/migration_move_calls.rs
  identity_iota_core/src/iota_interaction_rust/identity_move_calls.rs
  identity_iota_core/src/iota_interaction_rust/iota_client_rust_sdk.rs
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/migration/alias.rs
  identity_iota_core/src/rebased/mod.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/transaction.rs
  identity_iota_core/src/rebased/utils.rs
  identity_iota_core/src/state_metadata/document.rs
  identity_iota_interaction/Cargo.toml
  identity_iota_interaction/src/move_call_traits.rs
  identity_iota_interaction/src/sdk_types/iota_types/iota_serde.rs
  identity_iota_interaction/src/sdk_types/iota_types/iota_types_lib.rs
  identity_iota_interaction/src/sdk_types/iota_types/timelock/timelock.rs
Labels: Wasm, Chore, No changelog, Rust

#1540 Add Rust deploy docs workflow
  .github/workflows/rust-deploy-docs.yml
Labels: No changelog

#1549 Add Rust docs link
  README.md
  identity_iota/README.md
Labels: No changelog

#1546 Clean packages
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
Labels: No changelog

#1552 Fix typedoc issues
  bindings/wasm/identity_wasm/lib/resolver.ts
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/entry.rs
  bindings/wasm/identity_wasm/tsconfig.json
  bindings/wasm/identity_wasm/tsconfig.typedoc.json
  bindings/wasm/identity_wasm/typedoc.json
  bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
  bindings/wasm/tsconfig.json
Labels: Documentation, Chore, No changelog

#1560 Limit parallel test execution
  .github/workflows/build-and-test.yml
Labels: No changelog

#1563 Bump iota version
  .github/actions/iota-rebase-sandbox/setup/action.yml
  README.md
  bindings/grpc/Cargo.toml
  examples/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota/README.md
  identity_iota_core/Cargo.toml
  identity_iota_core/packages/iota_identity/Move.toml
  identity_iota_core/tests/e2e/common.rs
  identity_iota_interaction/Cargo.toml
Labels: No changelog

#1567 Bump iota sdk version and interaction to v0.9.2-rc
  .github/workflows/clippy.yml
  bindings/wasm/identity_wasm/examples/README.md
  bindings/wasm/iota_interaction_ts/package.json
  identity_iota_interaction/src/sdk_types/error.rs
  identity_iota_interaction/src/sdk_types/iota_json_rpc_types/iota_event.rs
  identity_iota_interaction/src/sdk_types/iota_json_rpc_types/iota_move.rs
  identity_iota_interaction/src/sdk_types/iota_json_rpc_types/iota_object.rs
  identity_iota_interaction/src/sdk_types/iota_json_rpc_types/iota_transaction.rs
  identity_iota_interaction/src/sdk_types/iota_types/base_types.rs
  identity_iota_interaction/src/sdk_types/iota_types/crypto.rs
  identity_iota_interaction/src/sdk_types/iota_types/error.rs
  identity_iota_interaction/src/sdk_types/iota_types/event.rs
  identity_iota_interaction/src/sdk_types/iota_types/execution_status.rs
  identity_iota_interaction/src/sdk_types/iota_types/gas_coin.rs
  identity_iota_interaction/src/sdk_types/iota_types/stardust/output/nft.rs
  identity_iota_interaction/src/sdk_types/iota_types/timelock/timelock.rs
  identity_iota_interaction/src/sdk_types/shared_crypto/intent.rs
Labels: Wasm, No changelog, Rust

#1565 Fix typedoc issues
  bindings/wasm/identity_wasm/lib/resolver.ts
  bindings/wasm/identity_wasm/src/common/timestamp.rs
  bindings/wasm/identity_wasm/src/credential/credential.rs
  bindings/wasm/identity_wasm/src/credential/jpt_credential_validator/jwp_verification_options.rs
  bindings/wasm/identity_wasm/src/credential/linked_domain_service.rs
  bindings/wasm/identity_wasm/src/credential/linked_verifiable_presentation_service.rs
  bindings/wasm/identity_wasm/src/credential/presentation/presentation.rs
  bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/credential.rs
  bindings/wasm/identity_wasm/src/did/jws_verification_options.rs
  bindings/wasm/identity_wasm/src/iota/iota_metadata_encoding.rs
  bindings/wasm/identity_wasm/src/jose/jwk.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client_read_only.rs
  bindings/wasm/identity_wasm/src/storage/signature_options.rs
  bindings/wasm/typedoc.json
  examples/1_advanced/8_status_list_2021.rs
Labels: Documentation, Wasm, No changelog

#1571 Update brew update command
  .github/actions/rust/sccache/setup-sccache/action.yml
Labels: No changelog

#1572 Rename types in iota interaction ts and iota interaction rust
  bindings/wasm/identity_wasm/src/rebased/identity.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/config_change.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/deactivate_did.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/send.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/update_did.rs
  bindings/wasm/identity_wasm/src/rebased/wasm_identity_client.rs
  bindings/wasm/iota_interaction_ts/lib/iota_client_helpers.ts
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_iota_client.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
  bindings/wasm/iota_interaction_ts/src/iota_client_ts_sdk.rs
  bindings/wasm/iota_interaction_ts/src/lib.rs
  identity_iota_core/src/iota_interaction_rust/mod.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/config_change.rs
  identity_iota_core/src/rebased/proposals/controller.rs
  identity_iota_core/src/rebased/proposals/deactivate_did.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/send.rs
  identity_iota_core/src/rebased/proposals/update_did_doc.rs
  identity_iota_core/src/rebased/proposals/upgrade.rs
Labels: Wasm, No changelog, Rust

#1570 Credential's context is a set even when a single context value is present
  bindings/wasm/src/resolver/wasm_resolver.rs
  identity_credential/src/credential/credential.rs
Labels: Bug, Wasm, Rust, Patch

#1564 Prepare interactions release
  .github/workflows/build-and-test.yml
  bindings/wasm/identity_wasm/lib/tsconfig.json
  bindings/wasm/identity_wasm/lib/tsconfig.web.json
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/identity_wasm/tsconfig.json
  bindings/wasm/iota_interaction_ts/LICENSE
  bindings/wasm/iota_interaction_ts/lib/tsconfig.json
  bindings/wasm/iota_interaction_ts/lib/tsconfig.web.json
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
  bindings/wasm/iota_interaction_ts/tsconfig.typedoc.json
  bindings/wasm/iota_interaction_ts/typedoc.json
Labels: No changelog

#1568 Move: Bare Identity, Removed DeactivateDid Proposal, DID Deletion, Identity Deletion
  bindings/wasm/identity_wasm/src/common/imported_document_lock.rs
  bindings/wasm/identity_wasm/src/did/wasm_core_document.rs
  bindings/wasm/identity_wasm/src/error.rs
  bindings/wasm/identity_wasm/src/iota/iota_document.rs
  bindings/wasm/identity_wasm/src/macros.rs
  bindings/wasm/identity_wasm/src/rebased/identity.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/config_change.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/deactivate_did.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/mod.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/send.rs
  bindings/wasm/identity_wasm/src/rebased/proposals/update_did.rs
  bindings/wasm/identity_wasm/src/resolver/wasm_resolver.rs
  bindings/wasm/identity_wasm/src/storage/wasm_storage.rs
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/create.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/deactivate.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/index.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/update.ts
  bindings/wasm/iota_interaction_ts/src/identity_move_calls.rs
  identity_iota_core/packages/iota_identity/sources/controller.move
  identity_iota_core/packages/iota_identity/sources/identity.move
  identity_iota_core/packages/iota_identity/sources/migration.move
  identity_iota_core/packages/iota_identity/sources/multicontroller.move
  identity_iota_core/packages/iota_identity/sources/proposals/borrow.move
  identity_iota_core/packages/iota_identity/sources/proposals/config.move
  identity_iota_core/packages/iota_identity/sources/proposals/controller.move
  identity_iota_core/packages/iota_identity/sources/proposals/delete.move
  identity_iota_core/packages/iota_identity/sources/proposals/did_deactivation.move
  identity_iota_core/packages/iota_identity/sources/proposals/transfer.move
  identity_iota_core/packages/iota_identity/sources/proposals/value.move
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/iota_interaction_rust/identity_move_calls.rs
  identity_iota_core/src/rebased/client/read_only.rs
  identity_iota_core/src/rebased/migration/identity.rs
  identity_iota_core/src/rebased/proposals/deactivate_did.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/update_did_doc.rs
  identity_iota_core/tests/e2e/client.rs
  identity_iota_core/tests/e2e/identity.rs
  identity_iota_interaction/src/move_call_traits.rs
Labels: Enhancement, Wasm, Added, Rust, Move

#1575 Release `identity_iota` Move package to Testnet & Devnet
  identity_iota_core/src/rebased/iota/well_known_networks.rs
Labels: Chore, No changelog

#1576 Use published interaction package
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
Labels: No changelog
