Repository iotaledger/identity, pull requests merged in 2025-01, with the labels that each got.

#1494 test identity package in CI
  .github/workflows/build-and-test.yml
Labels: Chore, No changelog

#1493 WASM Bindings for SD-JWT VC
  bindings/wasm/Cargo.toml
  bindings/wasm/examples/src/1_advanced/10_sd_jwt_vc.ts
  bindings/wasm/examples/src/main.ts
  bindings/wasm/package-lock.json
  bindings/wasm/package.json
  bindings/wasm/src/error.rs
  bindings/wasm/src/jose/jwk.rs
  bindings/wasm/src/lib.rs
  bindings/wasm/src/macros.rs
  bindings/wasm/src/sd_jwt_vc/builder.rs
  bindings/wasm/src/sd_jwt_vc/claims.rs
  bindings/wasm/src/sd_jwt_vc/metadata/claim.rs
  bindings/wasm/src/sd_jwt_vc/metadata/issuer.rs
  bindings/wasm/src/sd_jwt_vc/metadata/mod.rs
  bindings/wasm/src/sd_jwt_vc/metadata/vc_type.rs
  bindings/wasm/src/sd_jwt_vc/mod.rs
  bindings/wasm/src/sd_jwt_vc/presentation.rs
  bindings/wasm/src/sd_jwt_vc/resolver.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/builder.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/disclosure.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/hasher.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/kb_jwt.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/mod.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/sd_jwt.rs
  bindings/wasm/src/sd_jwt_vc/sd_jwt_v2/signer.rs
  bindings/wasm/src/sd_jwt_vc/status.rs
  bindings/wasm/src/sd_jwt_vc/token.rs
  identity_core/src/common/url.rs
  identity_credential/src/sd_jwt_vc/builder.rs
  identity_credential/src/sd_jwt_vc/metadata/vc_type.rs
  identity_credential/src/sd_jwt_vc/mod.rs
  identity_credential/src/sd_jwt_vc/resolver.rs
  identity_credential/src/sd_jwt_vc/token.rs
  identity_iota/Cargo.toml
  identity_iota/src/lib.rs
  identity_jose/src/jwk/key_set.rs
Labels: Enhancement, Wasm, Added, Rust

#1490 Chain execution for user-driven proposals
  identity_iota_core/src/rebased/iota/move_calls/identity/borrow_asset.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/controller_execution.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/mod.rs
  identity_iota_core/src/rebased/iota/move_calls/identity/send_asset.rs
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/controller.rs
  identity_iota_core/src/rebased/proposals/mod.rs
  identity_iota_core/src/rebased/proposals/send.rs
  identity_iota_core/tests/e2e/identity.rs
Labels: Enhancement, Rust, Patch

#1496 Support %-encoded characters in DID URL
  bindings/wasm/src/common/imported_document_lock.rs
  bindings/wasm/src/error.rs
  identity_credential/src/credential/jwt_serialization.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/revocation/status_list_2021/entry.rs
  identity_credential/src/revocation/validity_timeframe_2024/revocation_timeframe_status.rs
  identity_did/Cargo.toml
  identity_did/src/did_url.rs
  identity_document/benches/deserialize_document.rs
  identity_document/src/document/core_document.rs
  identity_document/src/utils/did_url_query.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/state_metadata/document.rs
  identity_jose/src/jws/decoder.rs
  identity_jose/src/jws/encoding/utils.rs
  identity_jose/src/jws/recipient.rs
Labels: Bug, Wasm, Rust, Patch

#1415 Use separate PAT as GitHub token
  .github/workflows/shared-release.yml
  .github/workflows/upload-docs.yml
Labels: No changelog

#1504 SD-JWT VC: use latest SD-JWT crate version
  identity_credential/Cargo.toml
Labels: Dependencies, No changelog

#1505 Repair identity-wasm build
  bindings/wasm/identity_wasm/Cargo.toml
  bindings/wasm/identity_wasm/src/error.rs
  bindings/wasm/identity_wasm/src/resolver/mod.rs
Labels: Wasm, No changelog, Rust

#1511 Feat/ts move calls ext
  .github/actions/rust/sccache/setup-sccache/action.yml
  identity_iota_core/src/rebased/proposals/borrow.rs
  identity_iota_core/src/rebased/proposals/controller.rs
Labels: Wasm, No changelog

#1499 WASM Move Calls
  .github/actions/rust/sccache/setup-sccache/action.yml
  bindings/wasm/iota_interaction_ts/Cargo.toml
  bindings/wasm/iota_interaction_ts/lib/index.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/asset/create.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/asset/delete.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/asset/index.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/asset/transfer.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/asset/update.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/borrow_asset.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/config.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/controller_execution.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/create.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/deactivate.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/index.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/proposal.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/send_asset.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/update.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/identity/upgrade.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/index.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/migration.ts
  bindings/wasm/iota_interaction_ts/lib/move_calls/utils.ts
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/src/asset_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/bindings/wasm_types.rs
  bindings/wasm/iota_interaction_ts/src/error.rs
  bindings/wasm/iota_interaction_ts/src/identity_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/migration_move_calls.rs
  bindings/wasm/iota_interaction_ts/src/transaction_builder.rs
Labels: Wasm, Added
