Repository iotaledger/identity, pull requests merged in 2025-04, with the labels that each got.

#1623 Pin `derange` version to avoid conflicts in `iota-sdk` on alpha branch
  identity_core/Cargo.toml
Labels: Bug, Rust, Patch

#1618 Remove legacy Stardust IotaDocument metadata properties #1607
  bindings/wasm/identity_wasm/src/iota/iota_document.rs
  bindings/wasm/identity_wasm/src/iota/iota_document_metadata.rs
  identity_iota_core/src/document/iota_document.rs
  identity_iota_core/src/document/iota_document_metadata.rs
  identity_iota_core/src/state_metadata/document.rs
  identity_storage/src/storage/tests/api.rs
Labels: Wasm, Rust, Removed

#1633 Upstream changes v0.11.6-rc
  .github/actions/iota-rebase-sandbox/setup/action.yml
  .github/workflows/build-and-test.yml
  bindings/grpc/Cargo.toml
  bindings/wasm/identity_wasm/Cargo.toml
  bindings/wasm/identity_wasm/cypress/app/package-lock.json
  bindings/wasm/identity_wasm/cypress/app/package.json
  bindings/wasm/identity_wasm/package-lock.json
  bindings/wasm/identity_wasm/package.json
  bindings/wasm/iota_interaction_ts/Cargo.toml
  bindings/wasm/iota_interaction_ts/package-lock.json
  bindings/wasm/iota_interaction_ts/package.json
  examples/Cargo.toml
  identity_iota/Cargo.toml
  identity_iota_core/Cargo.toml
  identity_iota_core/packages/iota_identity/Move.lock
  identity_iota_interaction/Cargo.toml
  identity_iota_interaction/src/sdk_types/iota_json_rpc_types/iota_event.rs
  identity_iota_interaction/src/sdk_types/iota_types/balance.rs
  identity_iota_interaction/src/sdk_types/iota_types/coin.rs
  identity_iota_interaction/src/sdk_types/iota_types/dynamic_field.rs
  identity_iota_interaction/src/sdk_types/iota_types/id.rs
  identity_iota_interaction/src/sdk_types/iota_types/transaction.rs
  identity_iota_interaction/src/sdk_types/move_core_types/annotated_value.rs
  identity_storage/Cargo.toml
Labels: Wasm, No changelog, Rust

#1632 Select iota binary from GitHub releases
  .github/actions/iota-rebase-sandbox/setup/action.yml
  .github/workflows/build-and-test.yml
Labels: No changelog

#1642 Revert deranged version pinning
  bindings/wasm/src/credential/jpt_credential_validator/jpt_credential_validation_options.rs
  bindings/wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/src/credential/revocation/status_list_2021/credential.rs
  bindings/wasm/src/credential/revocation/validity_timeframe_2024/status.rs
  bindings/wasm/tests/storage.ts
  identity_core/Cargo.toml
  identity_core/src/common/ordered_set.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/revocation/status_list_2021/status_list.rs
  identity_credential/src/validator/jwt_credential_validation/error.rs
  identity_credential/src/validator/sd_jwt/error.rs
  identity_credential/src/validator/sd_jwt/validator.rs
  identity_jose/src/error.rs
  identity_jose/src/jws/encoding/utils.rs
  identity_storage/src/storage/tests/kb_jwt.rs
  identity_stronghold/src/storage/mod.rs
Labels: No changelog

#1643 Disable changelog generation
  .github/workflows/shared-create-hotfix-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
Labels: No changelog

#1647 Add updates from main
  .github/workflows/shared-create-hotfix-pr.yml
  .github/workflows/shared-create-main-release-pr.yml
  CHANGELOG.md
  bindings/wasm/identity_wasm/CHANGELOG.md
  bindings/wasm/identity_wasm/src/credential/jpt_credential_validator/jpt_credential_validation_options.rs
  bindings/wasm/identity_wasm/src/credential/jwt_credential_validation/jwt_credential_validator.rs
  bindings/wasm/identity_wasm/src/credential/revocation/status_list_2021/credential.rs
  bindings/wasm/identity_wasm/src/credential/revocation/validity_timeframe_2024/status.rs
  bindings/wasm/identity_wasm/tests/storage.ts
  identity_core/src/common/ordered_set.rs
  identity_credential/src/domain_linkage/domain_linkage_validator.rs
  identity_credential/src/domain_linkage/error.rs
  identity_credential/src/presentation/jwt_serialization.rs
  identity_credential/src/revocation/status_list_2021/status_list.rs
  identity_credential/src/validator/jwt_credential_validation/error.rs
  identity_credential/src/validator/sd_jwt/error.rs
  identity_credential/src/validator/sd_jwt/validator.rs
  identity_jose/src/error.rs
  identity_storage/src/storage/tests/kb_jwt.rs
  identity_stronghold/src/storage/mod.rs
Labels: No changelog

#1641 Add Move deploy actions
  .github/actions/iota-rebase-sandbox/load-keytool/action.yml
  .github/actions/iota-rebase-sandbox/setup/action.yml
  .github/workflows/deploy-move-package.yml
Labels: No changelog

#1657 Fix script action
  .github/workflows/deploy-move-package.yml
  .gitignore
Labels: No changelog
